### ISSUE TITLE
[Python] Release 4.21.0 broke multiple Google Cloud client libraries ("TypeError: Descriptors cannot not be created directly.")

### ISSUE THREAD

**Issue by lgruen** [protocolbuffers/protobuf#10051]
Example error for the `google-cloud-logging==3.1.1` library using `protobuf==4.21.0`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/google/cloud/logging/__init__.py", line 18, in <module>
    from google.cloud.logging_v2 import __version__
  File "/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/__init__.py", line 25, in <module>
    from google.cloud.logging_v2.client import Client
  File "/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/client.py", line 25, in <module>
    from google.cloud.logging_v2._helpers import _add_defaults_to_filter
  File "/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/_helpers.py", line 25, in <module>
    from google.cloud.logging_v2.entries import LogEntry
  File "/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/entries.py", line 31, in <module>
    import google.cloud.audit.audit_log_pb2  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Note that this works fine with the previous `protobuf==3.20.1` release.

To reproduce:

```sh
docker run -it python:3.10 /bin/bash
# Within the Docker container:
pip3 install google-cloud-logging==3.1.1 protobuf==4.21.0
python3 -c "import google.cloud.logging"
```

**Comment by chelseas** [comment]
Same issue when using onnx to convert network formats.

**Comment by JanuszL** [comment]
Same for the TensorFlow 1.15.5.

**Comment by gpmahanta** [comment]
Same issue for the google-cloud-datastore as well.

**Comment by hagen00** [comment]
Upgrading the following packages to latest fixed it for me. Not sure which packages actually needed upgrading. 
```
google-api-core==2.8.0
google-auth==2.6.6
google-cloud-core==2.3.0
google-cloud-storage==2.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.1
```

**Comment by stephanie-gillespie** [comment]
I've set protobuf==3.20.1 and it resolved the issue

**Comment by peterdudfield** [comment]
> I've set protobuf==3.20.1 and it resolved the issue

Thanks, this also worked for me

**Comment by gpmahanta** [comment]
> I've set protobuf==3.20.1 and it resolved the issue

yes, this thing works but this is not a permanent fix.

Many libraries like **google-cloud-datastore** are having the dependency on protobuf >= 3.19.0 and most of the platforms like Databricks are already pre-installed with protobuf == 3.17.2 by default which is causing an issue in various platforms and frameworks.

**Comment by EduMorenoJ** [comment]
setting protobuf==3.20.x or setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python works

**Comment by mike-luabase** [comment]
> setting protobuf==3.20.x or setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python works



Note that PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python will use pure-Python parsing and will be much slower

**Comment by jacobg** [comment]
@mike-luabase I got this error deploying to Cloud Functions. Is that due to needing to set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`, or due to other libraries not compatible with the new protobuf?

**Comment by vitas-pm** [comment]
Since the traceback points to 
```
  File "/usr/local/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

`"/usr/local/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py"`

Am I wrong to assume that the error comes from Google's own _pb2.py file that has not been regenerated with protoc >= 3.19.0?
The file in their repository hasn't been updated since last year.
https://github.com/googleapis/python-audit-log/blob/main/google/cloud/audit/audit_log_pb2.py

**Comment by mike-luabase** [comment]
> @mike-luabase I got this error deploying to Cloud Functions. Is that due to needing to set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`, or due to other libraries not compatible with the new protobuf?

Try adding

```
protobuf==3.20.1
```

to your requirements, if that fixes it, don't set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`

**Comment by EduMorenoJ** [comment]
> > setting protobuf==3.20.x or setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python works
> 
> Note that PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python will use pure-Python parsing and will be much slower

True, I would just set it if freezing the protobuf version does not work

**Comment by FreeBee34** [comment]
I would assume that the Google Cloud client libraries have tests  on protobuff to ensure that new releases dont break them. I am wondering how this happened

**Comment by le4m** [comment]
4.21.0 is broken for torch tensorboard as well. As mentioned above, easy fix is to uninstall it and install `protobuf==3.20.1`.

**Comment by RafaelFazzolino** [comment]
I've set protobuf==3.20.0 and it resolved the issue here

**Comment by haberman** [comment]
Please file bugs against the individual projects with out-of-date `_pb2.py` files. This is not a bug in protobuf itself.

For protobuf this was a planned breaking change, which is why we rev'd the major version number. Please see the error message for possible workarounds that you can use until the other projects have regenerated their files:

1. Downgrade to protobuf 3.20.0
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

**Comment by adamjstewart** [comment]
> For protobuf this was a planned breaking change, which is why we rev'd the major version number.

You bumped the minor version number, not the major version number. According to [semver](https://semver.org/), you should bump the major version number for forward-incompatible changes. Of course, it's up to you how closely you want to follow semver (Python is removing distutils without bumping the major version), but at a minimum I think a deprecation warning for a couple of minor releases would avoid a lot of headaches.

**Comment by cliffwoolley** [comment]
> You bumped the minor version number, not the major version number. 

It was both, interestingly -- as far as non-RC package versions on PyPI, we went from 3.20.1 to 4.21.0.  Fortunately for the moment 4.21.0 has been yanked from PyPI, but we have as yet no indicator of whether another breaking-change version will appear presently, so the instant reaction among many packages I'm seeing has been to pin our dependencies to protobuf<4.  This is unfortunate in numerous respects for the ecosystem; I hope a proper fallback path can be implemented so that we're not forever held to older versions.

**Comment by perezd** [comment]
We do plan to roll forward w/ 4.21.0, We've discovered python cloud libraries were not adequately testing against our RCs and they discovered this late, despite our communications both [here](https://developers.google.com/protocol-buffers/docs/news/2022-05-06) and [here](https://groups.google.com/g/protobuf/c/qBgEzyvtvoY).

This will be a breaking change, and folks will need to either pin to 3.20.x, or simply update your usages to be compatible, that's a great option. :)

**Comment by cliffwoolley** [comment]
@perezd - Respectfully, a relnote from two weeks ago and a forum post with < 50 views are arguably not enough notice for the whole ecosystem to react.  It's normal for packages not to look at RCs of their countless transitive dependencies; they won't even get installed unless you explicitly request `pip install --pre`.  Over a dozen engineers just within my group have had to scramble today to deal with fallout here from the many packages we depend on (only some of which we control).

**Comment by perezd** [comment]
What would you suggest we do differently? I'm open to suggestions.

**Comment by cliffwoolley** [comment]
>  and if mission critical systems are negatively impacted by their loose dependency definitions,

Well, this includes for example TensorFlow, which had its dependency specification as only >= until 6 days ago: https://github.com/tensorflow/tensorflow/commit/60d5bfbf0241e00267884b0dc1723bbdfee1806a

I'm not saying this is great practice, but it's also incredibly common among Python packages (see the rest of that TensorFlow setup.py for example), which can and do bump major versions all the time without necessarily being indicative of breaking changes.  There's not much way for consumers of Python packages to know whether semver is or isn't going to be followed.

My suggestion would have been to give a deprecation period as @adamjstewart said, and better still to provide a fallback path to the 3.x-ish behavior wherever possible.

**Comment by perezd** [comment]
FWIW, TensorFlow identified this regression and worked with us during the RC phase, I'd call that working as intended.

> My suggestion would have been to give a deprecation period as @adamjstewart said, and better still to provide a fallback path to the 3.x-ish behavior wherever possible.

You're not required to upgrade to 4.21.x, we do follow semver for mitigating breaking changes, and the fallback is to accurately pin your dependencies.

We're here to support community engagements and follow best practices, and I believe our team has done that here.

**Comment by adamjstewart** [comment]
As much as I would love to see a deprecation period, I can sympathize with the protobuf developers here. It can difficult with large refactors to have periods where both the old and new behavior is supported. I agree with @perezd that libraries that depend on protobuf really should be using `~=3.X` or `>=3.X,<4` until they've verified that their code works with 4.X. Once it works with 4.X, they should bump that to `>=3.X,<5`.

**Comment by haberman** [comment]
We did provide a deprecation period of sorts: 4.21.0 is compatible with generated code from protoc >= 3.19.0, which was released Oct 20, 2021. It would follow that anyone who was broken by 4.21.0 was using generated code that is at least seven months old.

For the deprecation window to really be effective though, users need to be made aware that some action is required on their part. We didn't make this clear back in October. However it's not clear how we could have done that. The communications channels we tried earlier this month (the [news page](https://developers.google.com/protocol-buffers/docs/news/2022-05-06), the [post to protobuf@googlegroups.com](https://groups.google.com/g/protobuf/c/qBgEzyvtvoY?pli=1), and the release candidates) clearly did not reach all of the interested parties.

I suppose we could have made the protobuf library log a warning starting back in October that users should update their generated code (and that the warning will soon become an error). Would that have been an effective way to signal that a change is coming, to make the deprecation period more effective?

> I agree with @perezd that libraries that depend on protobuf really should be using ~=3.X or >=3.X,<4 until they've verified that their code works with 4.X. 

With this model, how are people made aware that a new version is available that they should test with? Does pinning to 3.X run the risk of keeping people on the old library indefinitely, simply because they are not aware that a new and improved version is available?

**Comment by adamjstewart** [comment]
> With this model, how are people made aware that a new version is available that they should test with? Does pinning to 3.X run the risk of keeping people on the old library indefinitely, simply because they are not aware that a new and improved version is available?

Yes, that is the risk. Hopefully one of the developers or users will notice eventually. Developers can also "watch releases" on GitHub or other platforms, and if you use dependabot that should eventually notify you.

**Comment by stellaraccident** [comment]
Adding this to our docker files worked:

```
RUN python3 -m pip install protobuf==3.20.1 --force-reinstall
```

I hope this was a mistake and not an example of explicitly poor reasoning about version compatibility for generated code. The explicitness of that error message tells me that this was intentional. If so, that is an exceptionally poor decision to break compatibility in this way.

**Comment by cliffwoolley** [comment]
> It can difficult with large refactors to have periods where both the old and new behavior is supported.
Sure -- though it looks like there was an option here:
```
  File "/usr/local/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
...
If this call came from a _pb2.py file, 
```
It did, and we can know that programmatically.

This part would be part of a fine _warning_ message:
```
your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```
...followed by then having the code just automatically do this step:
```
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python 
```
 Great!  Not broken.  Maybe not as fast as we want, but compatible.
 
 
I recognize that Protobuf followed semver here.  I do wish that version specifiers were more carefully handled across the Python ecosystem, but the simple fact is that they aren't, so wherever we can smooth over incompatibilities and warn rather than error out, it really helps people.  Code having been generated using a protoc of seven months ago and not touched since then seems entirely plausible IMO.

**Comment by perezd** [comment]
>  If so, that is an exceptionally poor decision to break compatibility in this way.

[stellaraccident](https://github.com/stellaraccident) Was bumping the major version too subtle? I'm not sure what else we could have done here, do you have suggestions? I'd rather hear from you about how you'd like to have us manage and deliver breaking changes in a world where we are strictly adhering to semver guidelines.

**Comment by perezd** [comment]
> > It can difficult with large refactors to have periods where both the old and new behavior is supported.
> 
> Sure -- though it looks like there was an option here:
> 
> ```
>   File "/usr/local/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
>     _descriptor.FieldDescriptor(
>   File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
> ...
> If this call came from a _pb2.py file, 
> ```
> 
> It did, and we can know that programmatically.
> 
> This part would be part of a fine _warning_ message:
> 
> ```
> your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> ```
> 
> ...followed by then having the code just automatically do this step:
> 
> ```
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python 
> ```
> 
> Great! Not broken. Maybe not as fast as we want, but compatible.
> 
> I recognize that Protobuf followed semver here. I do wish that version specifiers were more carefully handled across the Python ecosystem, but the simple fact is that they aren't, so wherever we can smooth over incompatibilities and warn rather than error out, it really helps people. Code having been generated using a protoc of seven months ago and not touched since then seems entirely plausible IMO.

We generally do not recommend people checkin generated source code, but instead generate it just in time as part of their builds to prevent this sorta thing. However, if it has to happen, I would also expect end users to pin the runtime to the exact version they generated said code with.

**Comment by TBBle** [comment]
> I suppose we could have made the protobuf library log a warning starting back in October that users should update their generated code (and that the warning will soon become an error). Would that have been an effective way to signal that a change is coming, to make the deprecation period more effective?

I think this would have been the right way to go. The [Python stdlib `warnings` module](https://docs.python.org/3/library/warnings.html) is probably the best way to communicate such future changes in a way that downstream developers will see (or should, in their test-suite), but that doesn't immediately break end-user code.

> However, if it has to happen, I would also expect end users to pin the runtime to the exact version they generated said code with.

It has been pointed out to me that this would be infeasible because Python resolves dependencies across a whole project, so different protobuf-using libraries cannot pin to different specific versions of protobuf.

I agree that the blast-radius from this change was worsened by widespread use of `>= 3.x` in place of `~= 3.x` but using the major version of the Python package version in SemVer-style is only a good idea (a recommendation at strongest) in Python packages, not a requirement unlike some other languages, so `~=` is not the habitiual default for a lot of Python users, sadly.

**Comment by Rubbyrunner8828** [comment]
try 

pip install protobuf==4.21.1

**Comment by Petros626** [comment]
> Same for the TensorFlow 1.15.5.

did you solve it I must use TF 1.15 with GPU

**Comment by TBBle** [comment]
You can always work around this by adding `protobuf<4` to the pip install line or e.g., requirements.txt or setup.cfg, you're using to install the library that depends on `protobuf>=3.X`, if you're unable to upgrade to a version of the library that has the fix.

**Comment by Petros626** [comment]
> I've set protobuf==3.20.1 and it resolved the issue



> I've set protobuf==3.20.0 and it resolved the issue here

@RafaelFazzolino can you show me how to do it? i try to install tensorflow gpu, but the message is the same like for creator if this issue

**Comment by TBBle** [comment]
You'll need to show us how you're installing tensorflow, then we can tell you how to change that.

**Comment by Petros626** [comment]
@TBBle I follow this guide here: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/tensorflow-1.14/install.html#install-cuda-toolkit. I use Anaconda with virtual environment and just follow the steps from the tutorial, but when I try to import tensorflow at my venv. it throws me the error:
```

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by TBBle** [comment]
There's no install command in your post. Please share the actual command you're using, as that's probably the one that needs `protobuf<4` added to it.

**Comment by stellaraccident** [comment]
> > If so, that is an exceptionally poor decision to break compatibility in this way.
> 
> @stellaraccident Was bumping the major version too subtle? I'm not sure what else we could have done here, do you have suggestions? I'd rather hear from you about how you'd like to have us manage and deliver breaking changes in a world where we are strictly adhering to semver guidelines.

I would go so far as to not label this "too subtle" but wrong in the context of understanding how these things are deployed and used.

The comment above about not checking in generated source, and thinking that semver fixes anything in a python/system wide installation reveals the bias that the authors are not actually using this in the same way their users are and seem to be running on a largely theoretical understanding of the python deployment ecosystem (I'll just be blunt about this versus dancing around it because it is a common bias in Google oss).

Concrete critiques:

* This isn't about checking in generated code. This is about pypi being full of (now read only) packages which include generated code from your code generator which you just decided it was fine to break on an arbitrary day in may, 2022. Some of these are "classic" versions of things that are years old and pinned to various lts release schedules. Not making a value judgment on that state, just saying how it is. A seven month, single version hard break like this would have been exceptionally user unfriendly no matter how you messaged it.
* It is true that there should be more diligence in downstream version specs with respect to allowable ranges, however I am not aware of anyone, without a good reason, who would defensively pin all of their deps with a complicated expression guarding against theoretical major version incompatibility for a project like this. You have to consider that you've effectively signaled a compatibility policy of forward compatibility for basically the life of the project and then just changed this in one step. Most of the people hitting this aren't protobuf users but users of users of the ecosystem you've built. When Tensorflow didn't change their version spec at head to a major version constraint until ~8 days before, you should have taken that as a strong signal and not just his behind semver. If this has been my project, I would have strictly considered yanking the release based on this bug if I hadn't had the foresight.
* Versions need to be satisfied system wide. For a common "basement level" dep like this to introduce a hard break and advise that people start actively aging constraints on major version ranges... This will create a ripple effect over the coming months of people failing to be able to install any version that matches all constraints.
* As mentioned above, you have a fallback. It is common courtesy in python land to not require system level hacks (ie. An env var) for things to just work.
* A "basement level" dep like this, which has signaled a defacto lts/forward compatibility state on the order of many years probably needs O(years) notice and diligence to introduce a hard break. I know it's hard to be a code generator and deal with the various horizons but that's kind of the job of a library like this... It needs to bias towards a pragmatic, user sensitive compromise when worse comes to worse and things have to change in unsupportable ways. Semver is definitely a tool, but it is not a hammer for hitting users with, imo... And it doesn't actually solve the things you think it does in practice.

Feel free to take our leave my feedback. You asked, so I attempted to answer directly. In response to "strict adherence to semver guidelines", I would say -- put your users at least on equal footing as your beliefs on this front and reach for pragmatism and care with respect to how you pursue that end. Things break... That is life. But if I have a choice as a user, I avoid deps for basic things like this where the authors apply these kind of theoretical calculations.

**Comment by Petros626** [comment]
> There's no install command in your post. Please share the actual command you're using, as that's probably the one that needs `protobuf<4` added to it.

sorry for asking but where I find this file to add `protobuf<4` ?

**Comment by TBBle** [comment]
Ah, sorry, I didn't see you'd edited your post.

Try adding it to the end of the `pip install` line, i.e.
```
pip install --upgrade tensorflow-gpu==1.15 protobuf<4
```

**Comment by Petros626** [comment]
yeah Ive updated it, but the command can't not be found like this it's only working with ` pip install --upgrade tensorflow-gpu==1.15` ....ah damn

**Comment by TBBle** [comment]
I'm not sure what you mean about "updated it". What happened when you tried the command I gave?

**Comment by Petros626** [comment]
I run it in the Anaconda Prompt terminal like you suggest me and it says: `"The system cannot find the specified file."`

**Comment by TBBle** [comment]
Ah, you're in Windows using `cmd`, I guess. Try
```
pip install --upgrade tensorflow-gpu==1.15 "protobuf<4"
```

**Comment by TBBle** [comment]
Glad to know it's working. When you're able to upgrade to a newer Tensorflow, [version 2.9.1](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.1) has included the fix so you won't need to manually override the `protobuf` version.

**Comment by Petros626** [comment]
Yes I've read about this the problem is I need a model from Model Zoo 1 for my bachelor thesis, so it could be easier, but with clever people like you it can be solved too. :)

**Comment by SudeshnaBora** [comment]
Same issue is present in protobuf 4.21.1

**Comment by SudeshnaBora** [comment]
> > Same issue is present in protobuf 4.21.1
> 
> What did you try? Installing TensorFlow or what?

Not sure what downloaded it as dependency . But I do have tensorflow 2.4.1 as one of my dependency .

**Comment by Petros626** [comment]
Figure out which version you have installed and then search for compatible protobuf version. The newest isn't the best, I'm sure other people had the same problem, like you. You could try reinstalling with another protobuf version like one user here suggests me:
`pip install --upgrade tensorflow-gpu==2.4 "protobuf<4"` ?
CPU:
`pip install --upgrade tensorflow==2.4 "protobuf<4"` ?

**Comment by TBBle** [comment]
Note that in TensorFlow 2, [you don't need `tensorflow-gpu` anymore](https://github.com/tensorflow/tensorflow/issues/48640#issuecomment-825064981), GPUs are supported by the `tensorflow` package. Although that's getting off-topic here.

But yeah, in general to work around this issue, add `"protobuf<4"` to whatever command you used to install the thing you're using, whether you're using tensorflow directly or as a dependency of some other project.

**Comment by kushan-gunasekera** [comment]
For anyone who is looking for a proper solution,

answer:- [https://stackoverflow.com/a/72493690/6194097](https://stackoverflow.com/a/72493690/6194097)

**Comment by TBBle** [comment]
The permanent fix is to regenerate affected _pb2.py files with protoc 3.19 or later, as mentioned in the initial post. (If you are not the owner of the affected files, you'll need to file a bug with the relevant project to do that.)

**Comment by gchacaltana** [comment]
> I've set protobuf==3.20.1 and it resolved the issue

It work!

**Comment by MrMegaMango** [comment]
are we all just using a super old version of protobuf package to get by?
