### ISSUE TITLE
Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by asdxiaoqex** [protocolbuffers/protobuf#10134]
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:142)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:527)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320)
	at com.lebang.autoroot.model.t.ProductTagInfo$vo.<init>(ProductTagInfo.java:189)
	at com.lebang.autoroot.model.t.ProductTagInfo$vo.<init>(ProductTagInfo.java:119)
	at com.lebang.autoroot.model.t.ProductTagInfo$vo$1.parsePartialFrom(ProductTagInfo.java:1082)
	at com.lebang.autoroot.model.t.ProductTagInfo$vo$1.parsePartialFrom(ProductTagInfo.java:1076)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:339)
	at com.lebang.autoroot.model.t.ProductTagInfo$vo.parseFrom(ProductTagInfo.java:527)
	at com.lebang.autoroot.utils.OkHttpProxyUtil.getRequestJsonProto(OkHttpProxyUtil.java:344)
	at com.lebang.autoroot.service.TikTokMsgTaskService.msg1(TikTokMsgTaskService.java:149)
	at com.lebang.autoroot.AutorootApplicationTests.sda(AutorootApplicationTests.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by asdxiaoqex** [comment]
message vo {
}

**Comment by asdxiaoqex** [comment]
[1f 8b 08 00 00 00 00 00 00 03 ec 9a 5f 6c 1b 49 1d c7 9b ea 38 c0 a7 13 47 ee 74 f4 81 87 95 85 44 25 e2 66 ff cd ee ac a1 82 38 7f ea ba 76 9a 5e 92 4b 9b 03 99 d9 dd d9 dd 89 f7 5f 76 c7 71 9c 2a 12 1c ed 51 09 1e 2a ae 27 1d 08 e9 80 93 0a 9c ee d0 89 07 c4 03 20 10 12 e2 8f 04 42 20 5e 10 2f 27 24 24 d4 47 1e 4e e2 10 8c 93 38 b1 eb d4 d9 18 db 75 a5 e4 21 eb 9d f9 cd f8 bb f3 fd ec ec 78 e7 f7 81 b7 4e 3f f5 f2 eb dc 99 53 e9 d3 97 2f 9d 3d 25 de bb 31 f6 cf f1 7f dc 18 4b dd 7d 2c f5 09 3e 2b 64 55 1e 2a 50 56 34 20 69 12 2f c8 0a 14 59 99 c0 3e 41 59 e2 65 c8 2b 40 96 25 08 9e 1a 3b f3 d2 57 bf f0 eb b7 fe f0 dd 3f e9 dc ab 77 ee fd ec 07 df 7f f7 f4 d9 9b 2f be f6 93 ef 7c eb 6f 7f d4 f9 f7 c3 2f de 7a e9 ed af ff ee 9d 5f e9 39 72 3d 4d e2 19 6c a1 aa 4b d3 59 0b b9 31 9e 48 53 bc c9 4e d2 0e 49 4f b0 da b2 81 22 73 bf ce 5b c4 be b9 48 51 44 97 88 87 d3 59 41 01 80 c9 52 05 f6 1f b0 ea d8 ce 13 bf d1 9a b5 45 35 bc 54 0f 59 90 ca f3 db 85 8f a6 3e 42 3c d6 99 eb ea c8 a8 94 63 8a 68 95 75 1e 98 78 7c 8c 2f 3c 91 7a 3c ce 7a 7b 27 1f 4e 7d 30 ce ea 64 ab 8c 88 39 fe 98 20 40 be f0 c9 d4 d3 71 d6 70 09 f6 69 d9 c3 71 8c 6c 5c 66 95 1f d3 b1 a4 28 08 e8 19 09 6b 42 46 06 18 65 90 a2 c0 8c 00 55 49 c3 bc c1 0b 40 29 3c 93 4a 19 0e a2 e5 d8 c0 3e 1e 7f dc 0f 22 0f b9 85 67 53 4f c6 59 76 7d 31 8d 90 6f e3 68 fc 7d 3b d7 c8 a2 9f 88 b3 d8 37 a2 7a 48 b1 d9 2c 3d bb 2b 7f 57 41 cc 06 a1 cc ae b5 4c d9 20 8c 3f d9 1c 04 c0 2b 4c ea 78 2a 15 07 d5 c8 c0 07 f2 17 fe fe f6 bd bf bc c2 5f 3d f5 f9 53 ce cf ff fa 9f f7 be f1 f2 97 de 7b 36 2a 96 16 e5 5a 71 6d 2a 37 c5 fe 16 a7 f9 f9 ba 22 66 a6 14 db c9 5d 2b d5 9c 02 d4 2a 57 cc a2 89 85 cc 3c 2d aa b3 a5 65 6b 26 bf 45 af 06 95 75 90 9f b6 f9 42 09 e4 e7 97 74 6f fe 8a 9c 89 04 fe 8d b1 53 a9 57 3f 73 6c 50 6e df fa fd dd 06 15 dc 57 be fd db 5f bc f1 7a 1b 28 1f 6a 01 e5 c5 f3 d7 d3 6b 41 05 47 6c b8 88 c1 8e 71 3a fb 02 83 87 91 c1 4f a4 4d 12 87 2e aa 97 7d d4 60 22 5d 24 94 ba 98 cb 05 75 ee 39 8c 0c 4a 02 9f bb 70 71 8e d3 eb dc b4 43 5c 33 c2 fe c7 63 ae 44 22 64 b0 b0 79 4c 6b 41 54 e1 f2 41 1c 12 ca 06 9b a1 53 23 26 75 d2 59 51 63 4c 39 98 d8 0e 43 4a e4 d9 37 35 b0 21 46 b9 1a b9 e9 ec f5 34 3b 94 5d 12 b3 ca 17 d2 0e a5 61 9c 9d 9c f4 b0 49 90 74 ce 26 a1 53 3f 67 04 de 6e c1 a4 a4 1b da b5 a2 08 af ac 10 29 bc b6 45 84 70 92 75 c8 c2 ac 4f 1b c4 3c af 02 15 0a a6 02 9d 50 a5 75 53 26 6b 5b b5 50 22 6b 6b 9b c4 57 71 c8 4b 1b bc b9 19 ab 82 a3 7b b6 65 6e 40 e3 b3 55 9e 17 95 88 b5 dc eb 65 b7 c0 a0 e7 ed f4 e7 26 98 30 d2 b8 07 b6 d9 4d e0 13 0f 51 fc 08 29 de 1b 62 ba 73 eb a6 59 60 fa e0 2a da 0a f7 48 d8 2b 14 da 31 28 bb ec a6 6a 5c 31 f6 fb 42 84 1b b0 a9 a3 0f 3d 6d 6f 4f 3c 08 db 79 14 06 2e 66 fd cd d4 59 09 a1 98 cb 63 d7 0d 9a dd 8b 3c 75 b8 69 76 fb 57 a3 3a 37 17 6c b2 4e 3d cc cd fa 14 47 14 11 df 63 35 07 e4 4a 8a d6 1b b9 72 07 07 c4 58 9e bd 18 ad f9 cb d5 b9 e9 95 99 cd b9 70 79 38 1c 24 25 77 74 14 0f 82 dc be 40 d1 84 b7 0f 9d 75 e1 77 26 b0 db fb 5b a8 da ec 79 d5 38 b4 4c a9 12 ec 0d 4c b1 c3 e6 cb 61 6e 4a f4 2f 5d 09 6c b5 38 3b bf 05 2f 5b c3 b1 39 29 98 a3 a3 78 10 60 76 77 bb 49 5c b7 a8 2e 28 4d 79 2c 32 c0 8e 8b a3 f6 e6 4b 18 79 dc 74 60 04 2d 44 35 20 ea 85 a8 ce 47 de 4a 78 71 61 91 9f 59 99 0f 4b 9e 5c b1 4a cf 47 c3 f1 27 29 51 a3 a3 78 10 44 25 32 bd 09 56 82 e0 2e 7c ad 60 37 66 53 5d 10 d9 a4 bd 75 11 6d d5 77 cb fb 00 58 e7 93 c9 59 b7 67 14 3d 30 9e cb 3b b3 6b c8 cb 2d 4c 0d c7 ae a4 80 8d 8e e2 41 00 96 cc f5 26 61 49 a2 bb 20 b6 14 78 dc 94 6f 72 05 1c b1 a7 69 5b 07 f9 dc 65 ae 84 36 5b 56 6b 40 e9 8d 30 a1 c3 2f 3f a8 e7 f0 fc 5a 5e f6 75 7a f5 79 b0 5a 1c 92 5f 49 09 1b 1d c5 83 20 2c 91 e9 4d c0 12 04 77 e1 6b d6 f5 82 f6 46 8b 38 66 55 dc 22 8d 30 6e f9 29 20 4a 6a bf e0 92 c2 55 12 ae d7 03 21 5e cf cf 58 85 0b 74 6b 38 56 f5 0e d7 c3 52 3c 08 b8 8e 76 bc 49 d6 51 91 5d b0 ba 10 04 26 57 0a 22 9f f8 f7 ad dc 8a 53 dc 25 56 d8 fa 7a a4 d7 07 e3 21 2f 1b 02 65 95 ba 6a 10 a1 4b 9e bc 5a d0 bc da 70 7c 4a 4a d6 e8 28 1e 04 59 89 4c 6f c2 95 20 b8 db ca cb 41 34 e6 96 c3 fb 7e 15 a0 aa cb ad 10 df 74 f1 01 5e 02 90 7b c3 ab 73 1a 70 65 c1 5d 74 8c 2a aa d2 f5 99 55 03 90 e1 78 95 94 ae 91 11 3c 08 b8 92 38 be bf e6 3a 32 f6 88 15 57 1e f9 95 f8 a0 f5 01 4c 72 af 73 15 df e1 cd e6 92 76 d1 be 00 f8 39 5d 2d 11 3e 8c 72 d3 c3 31 27 29 4d a3 a3 78 10 38 1d ee 72 eb 9a ea fe da ed 6d 26 ca 67 5f b0 c7 49 35 c6 11 50 80 c0 43 55 80 40 14 c5 03 01 07 bb 0a 0a 54 20 90 79 45 13 14 01 aa b2 28 aa b0 03 38 87 d1 64 91 8d 96 29 4b 12 5b de 6e ed 9c 1c 4d 59 28 28 99 0d 94 a1 a4 42 83 ca 39 a2 d7 29 26 9e bd e3 5e a0 af 4d 7a d5 98 34 76 ad ea 19 0f b9 84 05 36 0a 65 99 97 55 41 06 32 86 9a 89 35 59 e4 25 00 2c 8c 1a 3b 61 50 95 e4 63 83 d3 8b 08 4b 57 04 4b 84 86 26 1a 6c b4 2c d3 32 4d 28 4b 9a 02 90 c1 8b 96 85 ba b1 10 fa 76 27 0b 35 ac 87 87 c1 10 44 c4 26 7e 39 44 46 65 77 df ed 7e 7b 44 00 35 f6 ac d8 60 06 92 c0 6f dc df 0c 4c 4d 84 bc 06 64 a0 76 a3 a9 c5 c2 26 42 fb 45 fb 53 4d fb 97 01 a8 28 62 07 0b 46 e0 db 11 9b bc 1e 02 0b 92 c6 f3 aa 0a 2d 36 ea 92 61 f0 92 20 88 50 87 32 52 91 66 aa a2 32 14 16 64 1d 4a 3a d4 65 dd 60 34 6a 82 a0 88 82 01 0c c9 02 26 fb 84 90 f4 28 b0 d0 62 61 93 85 fd a2 07 b0 a0 02 5e 56 3a 58 a8 a1 87 31 27 00 5d 91 2d 49 c2 02 64 73 02 54 64 55 c7 92 c4 26 09 5d 54 54 51 35 f5 a1 70 80 2c 45 51 4d 53 03 82 a2 6a 86 2c a9 6c 36 c0 16 62 64 60 a4 40 6c 3c 0a 1c ec d9 d7 64 60 e7 94 3d 43 1a 29 04 cf c4 d9 08 d7 22 c2 f4 59 51 e0 95 51 18 ee ec b1 8b 92 74 58 d6 40 5b 56 c1 e1 fb fa 5c ea 4c 9c 35 83 b2 1f d0 32 61 95 18 c5 cc 14 9f 1d 59 27 34 aa e2 07 a6 1e 00 d1 82 92 6c 82 8c c4 06 3a 23 03 1d 66 74 a4 e2 0c 40 02 0f 64 19 9a 48 30 59 f7 4c d4 06 89 89 ee e2 f1 a7 0f d9 98 5f f8 f2 dd 1b ff ba d3 48 0d 18 73 de fd e9 d7 de bc 7d e3 cf ff 1e 40 6a c0 2b c7 4e 0d b8 79 fb f6 0f bf b7 93 1a 70 f7 47 bf e9 4c 0d b8 79 eb 97 77 be f9 e3 77 de d4 73 ff fd d4 49 6a 40 4f ab b3 04 53 c0 88 29 1e c4 7a f2 ff 27 e2 24 35 60 d8 1b ed 49 c9 1d 1d c5 83 20 b7 2f 50 9c a4 06 f4 d3 e6 a4 60 8e 8e e2 41 80 79 92 1a d0 3f 7f 92 12 35 3a 8a 07 41 54 22 d3 4f 52 03 7a b1 2b 29 60 a3 a3 78 10 80 25 73 fd 24 35 a0 17 bf 92 12 36 3a 8a 07 41 58 22 d3 4f 52 03 8e 6b 55 ef 70 3d 2c c5 83 80 eb 68 c7 4f 52 03 8e eb 53 52 b2 46 47 f1 20 c8 4a 64 fa 49 6a c0 b1 bd 4a 4a 57 ff 04 ff 0f 00 00 ff ff a2 d0 c1 b4 48 5c c4 c4 f8 e8 d2 00 22 22 87 d8 d4 34 78 5c 4c 8b e4 44 f9 d2 00 af 52 a0 75 79 c0 a6 57 69 52 a6 a9 39 c2 f6 d1 75 01 24 38 62 74 5d c0 e8 ba 80 d1 75 01 a3 eb 02 46 cc ba 00 f2 66 fe 71 cd eb 27 27 a5 9a 9b a4 9a 99 e8 9a 9b 26 a5 ea 9a 18 27 5b e8 26 02 73 ae 2e d0 fd 86 a9 89 96 96 26 89 a9 e6 e8 f3 fa 98 33 e8 44 2c 2c c0 bb 9c 21 e0 e3 52 e8 ba 00 86 8c 0f 33 2e 2c c5 b2 2e c0 43 37 dc c8 49 d7 cb 20 37 af c8 22 38 d9 27 d3 34 d7 5d b7 20 3f a7 2a 27 20 df 37 c3 d2 0b e8 1d a3 b0 4a 8b 20 dd aa b4 00 4f 4b cf 20 ff cc bc f0 28 af 5c ff d0 e0 b2 9c 44 6f cf e0 9c 55 8c 0c 02 b0 b9 7d 09 06 2b 25 60 4c 18 19 98 19 1a 1b 98 9b 00 eb 31 03 a0 9f 2c 8d 80 d9 08 58 70 19 99 38 3a 3b 39 99 3a 06 f4 ef 9c f6 60 aa 41 c4 62 30 05 00 00 00 ff ff 03 00 19 35 92 c0 b1 42 00 00]

**Comment by asdxiaoqex** [comment]
byte[] bytes = response.body().bytes();
                    String s = bytes2hex(bytes);
                    System.out.println(s);
                    // JSONObject jsonObject = OkHttpUtil.postRequestJson("http://localhost:18698/md", bytes);
                    ProductTagInfo.vo vo = ProductTagInfo.vo.parseFrom(bytes1);

**Comment by jorgbrown** [comment]
What code was it, that generated these bytes in the first place?  If it wasn't generate by our code, then it's not our bug...

**Comment by asdxiaoqex** [comment]
java
