### ISSUE TITLE
No Module Named 'python' 

### ISSUE THREAD

**Issue by andrewkatson** [protocolbuffers/protobuf#10955]
**What version of protobuf and what language are you using?**
Version: main
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.7

**What did you do?**
1. git clone --recurisve_submodules https://github.com/protocolbuffers/protobuf.git in msys
2. cd protobuf
3. bazel build :protobuf_python

**What did you expect to see**
successful build

**What did you see instead?**
```
INFO: Repository pip_deps instantiated at:
  C:/users/katso/documents/protobuf/WORKSPACE:60:12: in <toplevel>
  C:/msys64/home/katso/_bazel_katso/t6xap2t5/external/rules_python/python/pip.bzl:97:19: in pip_install
Repository rule pip_repository defined at:
  C:/msys64/home/katso/_bazel_katso/t6xap2t5/external/rules_python/python/pip_install/pip_repository.bzl:295:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_deps':
   Traceback (most recent call last):
        File "C:/msys64/home/katso/_bazel_katso/t6xap2t5/external/rules_python/python/pip_install/pip_repository.bzl", line 179, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (/usr/bin/python.exe: Error while finding module specification for 'python.pip_install.extract_wheels' (ModuleNotFoundError: No module named 'python')
)
ERROR: C:/users/katso/documents/protobuf/WORKSPACE:60:12: fetching pip_repository rule //external:pip_deps: Traceback (most recent call last):
        File "C:/msys64/home/katso/_bazel_katso/t6xap2t5/external/rules_python/python/pip_install/pip_repository.bzl", line 179, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (/usr/bin/python.exe: Error while finding module specification for 'python.pip_install.extract_wheels' (ModuleNotFoundError: No module named 'python')
)
ERROR: C:/users/katso/documents/protobuf/BUILD.bazel:264:6: //:protobuf_python depends on //python:protobuf_python in repository @ which failed to fetch. no such package '@pip_deps//': rules_python failed:  (/usr/bin/python.exe: Error while finding module specification for 'python.pip_install.extract_wheels' (ModuleNotFoundError: No module named 'python')
)
ERROR: Analysis of target '//:protobuf_python' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.484s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

```

**Comment by andrewkatson** [comment]
Actually this is fixed in your non main branch. So I will close it.
