### ISSUE TITLE
Assigning wrong type to field results in segfault

### ISSUE THREAD

**Issue by ichernev** [protocolbuffers/protobuf#11280]
**What version of protobuf and what language are you using?**
Python 3.10.4
protobuf 4.21.9 (from pip)
Linux kernel 6.0.10-arch2-1 (arch, latest)

**What did you do?**
1. Compile the following proto file

       syntax = "proto3";
          
       package pkg;
          
       message Bar {
           int32 a = 1;
       }
          
       message Bar2 {
           string a = 1;
       }
          
       message Foo {
           Bar b = 1;
       }
2. Run the following code
       
       import example_pb2 as pb2
        
       bar = pb2.Bar(a=42)
       bar2 = pb2.Bar2(a="42")
       foo = pb2.Foo(b=bar2) # segfault here, b is type Bar not Bar2
        
**What did you expect to see**

I expect the code to die in a more civilized manner -- i.e exception, or at least a print before it dies saying the error comes from protobuf.

**What did you see instead?**

The code segfaulted: `segmentation fault (core dumped)`

**Comment by ichernev** [comment]
A similar situation produce exceptions (not segfault):
```
bar = pb2.Bar(a="42") # a is an int32
# Traceback (most recent call last):
#  File "code.py", line 3, in <module>
#    bar = pb2.Bar(a="42")
# TypeError: 'str' object cannot be interpreted as an integer

foo = pb2.Foo()
foo.b.MergeFrom(bar2)  # b is type Bar, not Bar2
# Traceback (most recent call last):
#   File "code.py", line 6, in <module>
#     foo.b.MergeFrom(bar2)
# TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'example_pb2.Bar'> got <class 'example_pb2.Bar2'>
``` 

So I'd expect the case presented above to also behave :)

**Comment by anandolee** [comment]
Tried to reproduce but there's no segfault anymore

C++ extension I got:
```
in testPythonicInit
    foo = test_proto3_optional_pb2.Foo(b=bar2)
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.python.internal.Bar got google.protobuf.python.internal.Bar2.
```

upb I got:
```
in testPythonicInit
    foo = test_proto3_optional_pb2.Foo(b=bar2)
TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'google.protobuf.internal.test_proto3_optional_pb2.Bar'> got <class 'google.protobuf.internal.test_proto3_optional_pb2.Bar2'>.
```

pure python I got:
```
Traceback (most recent call last):
  File "/build/work/9069ce5270a1c2a78244da48282fab0cf82f/google3/runfiles/google3/third_party/py/google/protobuf/internal/message_test.py", line 1577, in testPythonicInit
    foo = test_proto3_optional_pb2.Foo(b=bar2)
  File "/build/work/9069ce5270a1c2a78244da48282fab0cf82f/google3/runfiles/google3/third_party/py/google/protobuf/internal/python_message.py", line 541, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/build/work/9069ce5270a1c2a78244da48282fab0cf82f/google3/runfiles/google3/third_party/py/google/protobuf/internal/python_message.py", line 466, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/build/work/9069ce5270a1c2a78244da48282fab0cf82f/google3/runfiles/google3/third_party/py/google/protobuf/internal/python_message.py", line 539, in init
    copy.MergeFrom(new_val)
  File "/build/work/9069ce5270a1c2a78244da48282fab0cf82f/google3/runfiles/google3/third_party/py/google/protobuf/internal/python_message.py", line 1289, in MergeFrom
    raise TypeError(
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.internal.test_proto3_optional_pb2.Bar got google.protobuf.internal.test_proto3_optional_pb2.Bar2. for field Foo.b
```


I guess this issue has been resolved already some where
