### ISSUE TITLE
Test failures in Python bindings on 32-bit

### ISSUE THREAD

**Issue by thesamesam** [protocolbuffers/protobuf#11451]
**What version of protobuf and what language are you using?**
Version: 4.21.9
Language: Python

**What operating system (Linux, Windows, ...) and version?**

Gentoo, 5.15.86-gentoo-dist-hardened.

Originally reported in Gentoo at https://bugs.gentoo.org/857570.

**What runtime / compiler are you using (e.g., python version or gcc version)**

Python 3.10, GCC 11.3.1_p20221209.

**What did you do?**
1. Run protobuf-4.21.9's test suite on a 32-bit architecture like x86.

**What did you expect to see**

Passing tests.

**What did you see instead?**

Full log: [build.log](https://github.com/protocolbuffers/protobuf/files/10341815/build.log)

Snippet:
```
======================================================================
FAIL: testNonStandardSingleScalarBoundsChecking_proto2 (google.protobuf.internal.reflection_test.ReflectionTest)
testNonStandardSingleScalarBoundsChecking_proto2(<module 'google.protobuf.unittest_pb2' from '/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/_parameterized.py", line 229, in BoundParamTest
    test_method(self, *testcase_params)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 473, in testNonStandardSingleScalarBoundsChecking
    self.assetIntegerBoundsChecking(
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 456, in assetIntegerBoundsChecking
    TestMinAndMaxIntegers('optional_uint32', 0, 0xffffffff)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 449, in TestMinAndMaxIntegers
    self.assertEqual(expected_max, getattr(pb, field_name))
AssertionError: NonStandardInteger(4294967295) != -1

======================================================================
FAIL: testNonStandardSingleScalarBoundsChecking_proto3 (google.protobuf.internal.reflection_test.ReflectionTest)
testNonStandardSingleScalarBoundsChecking_proto3(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/_parameterized.py", line 229, in BoundParamTest
    test_method(self, *testcase_params)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 473, in testNonStandardSingleScalarBoundsChecking
    self.assetIntegerBoundsChecking(
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 456, in assetIntegerBoundsChecking
    TestMinAndMaxIntegers('optional_uint32', 0, 0xffffffff)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 449, in TestMinAndMaxIntegers
    self.assertEqual(expected_max, getattr(pb, field_name))
AssertionError: NonStandardInteger(4294967295) != -1

======================================================================
FAIL: testSingleScalarBoundsChecking_proto2 (google.protobuf.internal.reflection_test.ReflectionTest)
testSingleScalarBoundsChecking_proto2(<module 'google.protobuf.unittest_pb2' from '/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/_parameterized.py", line 229, in BoundParamTest
    test_method(self, *testcase_params)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 470, in testSingleScalarBoundsChecking
    self.assetIntegerBoundsChecking(lambda x: x, message_module)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 456, in assetIntegerBoundsChecking
    TestMinAndMaxIntegers('optional_uint32', 0, 0xffffffff)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 449, in TestMinAndMaxIntegers
    self.assertEqual(expected_max, getattr(pb, field_name))
AssertionError: 4294967295 != -1

======================================================================
FAIL: testSingleScalarBoundsChecking_proto3 (google.protobuf.internal.reflection_test.ReflectionTest)
testSingleScalarBoundsChecking_proto3(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/_parameterized.py", line 229, in BoundParamTest
    test_method(self, *testcase_params)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 470, in testSingleScalarBoundsChecking
    self.assetIntegerBoundsChecking(lambda x: x, message_module)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 456, in assetIntegerBoundsChecking
    TestMinAndMaxIntegers('optional_uint32', 0, 0xffffffff)
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/reflection_test.py", line 449, in TestMinAndMaxIntegers
    self.assertEqual(expected_max, getattr(pb, field_name))
AssertionError: 4294967295 != -1

======================================================================
FAIL: testAllFieldsToJson (google.protobuf.internal.json_format_test.JsonFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/json_format_test.py", line 152, in testAllFieldsToJson
    self.assertEqual(
AssertionError: {'boolValue': True, 'int32Value': 20, 'int6[733 chars]11}]} != {'int32Value': 20, 'int64Value': '-20', 'ui[730 chars]AR']}
Diff is 997 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: testDifferentCustomOptionTypes (google.protobuf.internal.descriptor_test.DescriptorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/descriptor_test.py", line 272, in testDifferentCustomOptionTypes
    self.assertEqual(kuint32max, message_options.Extensions[
AssertionError: 4294967295 != -1

======================================================================
FAIL: testDifferentCustomOptionTypes (google.protobuf.internal.descriptor_test.NewDescriptorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/protobuf-python-4.21.9/work/protobuf-21.9/python/google/protobuf/internal/descriptor_test.py", line 272, in testDifferentCustomOptionTypes
    self.assertEqual(kuint32max, message_options.Extensions[
AssertionError: 4294967295 != -1

----------------------------------------------------------------------
Ran 911 tests in 6.100s

FAILED (failures=7, skipped=7)
Test failed: <unittest.runner.TextTestResult run=911 errors=0 failures=7>
error: Test failed: <unittest.runner.TextTestResult run=911 errors=0 failures=7>
```

**Comment by anandolee** [comment]
I believe 32-bit python is not what we want support. @haberman correct me if I am wrong
