### ISSUE TITLE
google::protobuf::internal::ArenaStringPtr::Set(std::string const&, google::protobuf::Arena*) Error

### ISSUE THREAD

**Issue by risemeup1** [protocolbuffers/protobuf#11829]
**What version of protobuf and what language are you using?**
Version: v21.12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc8
**What did you do?**
Run unit test of Paddle 

**What did you expect to see**

**What did you see instead?**
C++ Traceback (most recent call last):
815: --------------------------------------
815: 0   paddle::distributed::DistModel::Init()
815: 1   paddle::distributed::DistModel::PrepareFleetExe()
815: 2   google::protobuf::internal::ArenaStringPtr::Set(std::string const&, google::protobuf::Arena*)
815: 
815: ----------------------
815: Error Message Summary:
815: ----------------------
815: FatalError: `Segmentation fault` is detected by the operating system.
815:   [TimeInfo: *** Aborted at 1675738412 (unix time) try "date -d @1675738412" if you are using GNU date ***]
815:   [SignalInfo: *** SIGSEGV (@0x8) received by PID 30217 (TID 0x7f1da62d1700) from PID 8 ***]
815: 
815: Segmentation fault
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/62429225/217143765-42fc47dd-4895-4495-9d1a-7a905f27f41c.png">

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by esorot** [comment]
What are the values in `config_.trainer_endpoints[i]` Can you provide a smaller repro that doesn't rely on any external config?

**Comment by raakasf** [comment]
I see something very similar too but only when I use `fsanitizer=thread` during compilation. All I'm doing is setting a string an a protobuf object
```sh
ThreadSanitizer:DEADLYSIGNAL
==456935==ERROR: ThreadSanitizer: SEGV on unknown address 0x0000ffffffe8 (pc 0x00000046296c bp 0x000100000000 sp 0x7ffc955a45d0 T456935)
==456935==The signal is caused by a READ memory access.
    #0 std::string::size() const /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3817 (test_bin+0x46296c)
    #1 std::string::assign(char const*, unsigned long) /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:712 (test_bin+0x46296c)
    #2 std::string::assign(char const*) /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:4314 (test_bin+0x560550)
    #3 std::string::operator=(char const*) /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3637 (test_bin+0x560550)
```
Weird that I don't see this with address sanitized builds.

**Comment by raakasf** [comment]
Managed to get it down to 
```sh
[libprotobuf FATAL /tmp/grpc/third_party/protobuf/src/google/protobuf/arenastring.h:409] CHECK failed: tagged_ptr_.UnsafeGet() != nullptr: 
unknown file: Failure
C++ exception with description "CHECK failed: tagged_ptr_.UnsafeGet() != nullptr: " thrown in the test body.
```
while calling a set function on a field (set string).

**Comment by PARKGIBAEK** [comment]
I've been plagued by this for quite some time, too.
This problem has been occurring not only from the current version but also from the lower version.
There is something wrong with the string type.

**Comment by KongQBin** [comment]
我也发现这个问题，它在大多数操作系统中没问题，但是在少数的系统环境中会存在这个问题。
我的版本是`libprotoc 3.14.0`
```
[libprotobuf FATAL /****/**/******/****/*****/google/protobuf/arenastring.h:364] CHECK failed: tagged_ptr_.UnsafeGet() != nullptr: 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: tagged_ptr_.UnsafeGet() != nullptr: 

Thread 32 "JYNZDFY2" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdab93700 (LWP 33054)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff782b859 in __GI_abort () at abort.c:79
#2  0x00007ffff7c058d1 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7c1137c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7c113e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7c11699 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000006f0cba in google::protobuf::internal::LogMessage::Finish() ()
#7  0x00000000006f0cf6 in google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&) ()
#8  0x00000000004c9ed1 in google::protobuf::internal::ArenaStringPtr::UnsafeMutablePointer (this=0x7fffdab92570) at /****/****/*********/***/****/google/protobuf/arenastring.h:364
#9  0x00000000006c04cf in google::protobuf::internal::ArenaStringPtr::Set(std::string const*, std::string const&, google::protobuf::Arena*) ()
#10 0x00000000006c084a in google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::string const&, google::protobuf::Arena*) ()
#11 0x00000000004a7050 in TESTBUF::TESTMsg::_internal_set_source_file_info (this=0x7fffdab92500, Python Exception <class 'gdb.error'> No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.: 
value=) at /****/****/*********/***/****/../******/********/**********/*****/********/ipc_proto/testbuf.pb.h:4614
```
我将自己的代码中的`set_source_file_info(const std::string &)`调用修改为`set_source_file_info(const void*, size_t size)`就不会出现这个错误了。
