### ISSUE TITLE
newSchemaForRawMessageInfo function throw "StringIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by shuiyouwen** [protocolbuffers/protobuf#12025]
i am use protobuf-javalite-3.19.1 in my android project。
But an exception StringIndexOutOfBoundsException（length=1; index=1） is thrown on some Android version 4.2.2 devices
The exception stack is as follows：

at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:271)
at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:85)
at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
at com.yst.projection.remote.CloudProjectionUtil.register(CloudProjectionUtil.java:215)

**Comment by googleberg** [comment]
Are you also using protoc version 3.19.1 to generate the Java bindings?
