### ISSUE TITLE
import paddle error on protobuf 3.20.0

### ISSUE THREAD

**Issue by risemeup1** [protocolbuffers/protobuf#12116]
What version of protobuf and what language are you using?
Version: 3.20.0
Language: Python

What operating system (Linux, Windows, ...) and version?
MacOS Monterey 12.5, M1 Version

What runtime / compiler are you using (e.g., python version or gcc version)
Python 3.10.10

What did you do?
Install paddle whl package
If I update protobuf to 4.21.x，I can import paddle successfully，but I need protobuf 3.x

1 brew install python3.10
2 pip3.10 install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-Build-Mac-M1/61611786fa7e2607b51c19ed4d83a6a4d1a3d01d/paddlepaddle-0.0.0-cp310-cp310-macosx_11_0_arm64.whl
3 python3.10 -> import paddle

>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/__init__.py", line 64, in <module>
    import paddle.distributed  # noqa: F401
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/__init__.py", line 17, in <module>
    from .spawn import spawn  # noqa: F401
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/spawn.py", line 22, in <module>
    from paddle.distributed.cloud_utils import (
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/cloud_utils.py", line 17, in <module>
    from paddle.distributed.utils.launch_utils import (
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/utils/launch_utils.py", line 25, in <module>
    from paddle.distributed.fleet.launch_utils import get_backend_by_compile_flag
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/fleet/__init__.py", line 19, in <module>
    from .base.distributed_strategy import DistributedStrategy  # noqa: F401
  File "/opt/homebrew/lib/python3.10/site-packages/paddle/distributed/fleet/base/distributed_strategy.py", line 29, in <module>
    import google.protobuf.pyext._message as _message
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_message.cpython-310-darwin.so' (no such file), '/usr/lib/_message.cpython-310-darwin.so' (no such file)

**Comment by deannagarcia** [comment]
Why do you need protobuf 3.20 instead of using 4.22?
