### ISSUE TITLE
HEAD broken when built as an external bazel repository.

### ISSUE THREAD

**Issue by qzmfranklin** [protocolbuffers/protobuf#12523]
**What version of protobuf and what language are you using?**

Language: Python

983dac24c34f07a278d45fdfd30348775d95d12a (recent main)

It's broken at `v22.0`.

It's not broken at `v21.12`.

**What operating system (Linux, Windows, ...) and version?**

WSL2-Ubuntu 22.04

**What runtime / compiler are you using (e.g., python version or gcc version)**

clang: clang-16.0.0
Python: 3.9.0 (this should be irrelevant though)

**What did you do?**

`bazel build @com_google_protobuf//python:all`

**What did you expect to see**

Everything is built properly without error.

**What did you see instead?**
```text
 %  bazel build @com_google_protobuf//python:all
ERROR: /home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/python/BUILD.bazel:191:20: in internal_copy_files_impl rule @com_google_protobuf//python:copied_test_messages_proto2_files: 
Traceback (most recent call last):
        File "/home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/python/internal.bzl", line 11, column 17, in _internal_copy_files_impl
                fail("Source does not start with %s: %s" %
Error in fail: Source does not start with src/: ../com_google_protobuf/src/google/protobuf/test_messages_proto2.proto
```

**Other information that might be relevant**

bazel version: 7.0.0-pre.20230405.2

This error could be avoided by checking `ctx.workspace_name`, which would be non-empty if protobuf is built as an external bazel repository.

I did an initial triage like the following:

```diff
 % git diff
     for src in ctx.files.srcs:
-        if src.short_path[:len(strip_prefix)] != strip_prefix:
-            fail("Source does not start with %s: %s" %
-                 (strip_prefix, src.short_path))
-        dest = ctx.actions.declare_file(src.short_path[len(strip_prefix):])
+        if not ctx.workspace_name:
+            if src.short_path[:len(strip_prefix)] != strip_prefix:
+                fail("Source does not start with %s: %s" %
+                    (strip_prefix, src.short_path))
+            dest = ctx.actions.declare_file(src.short_path[len(strip_prefix):])
+        else:
+            strip_prefix = 'external/com_google_protobuf/' + strip_prefix
+            dest = ctx.actions.declare_file(src.path[len(strip_prefix):])
+            # If this rule is called from a workspace other than protobuf, the
+            # workspace_name would be non-empty.  In that case, the short_path
+            # will be like ../com_google_protobuf/{strip_prefix}/(snip).  The
+            # path will be like external/com_google_protobuf.
+            # # print(dir(src))
+            # print(src.root, src.basename, src.dirname, src.extension)
+            # print(dir(src.root))
         src_dests.append([src, dest])
 
```

Then I got the following error:

```text
%  bb build @com_google_protobuf//python:all
ERROR: /home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/python/BUILD.bazel:377:11: no such target '//external:python_headers': target 'python_headers' not declared in package 'external' defined by /home/zhongmingqu/code/monorepo/WORKSPACE (Tip: use `query "//external:*"` to see all the targets in that package) and referenced by '@com_google_protobuf//python:proto_api'
ERROR: /home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/python/BUILD.bazel:40:26: in _proto_gen rule @com_google_protobuf//python:well_known_types_py_pb2_genproto: 
Traceback (most recent call last):
        File "/home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/protobuf.bzl", line 161, column 41, in _proto_gen_impl
                outs = [ctx.actions.declare_file(out, sibling = src) for out in outs]
Error in declare_file: the output artifact 'external/com_google_protobuf/_pb2.py' is not under package directory 'external/com_google_protobuf/python' for target '@com_google_protobuf//python:well_known_types_py_pb2_genproto'
ERROR: /home/zhongmingqu/.cache/bazel/_bazel_zhongmingqu/33d097c4393d1ec801bb3e6d74ed212d/external/com_google_protobuf/python/BUILD.bazel:40:26: Analysis of target '@com_google_protobuf//python:well_known_types_py_pb2_genproto' failed
```

Looks like it'd be a systematic fix to how the proto files are copied for making the python runtime.

**Comment by qzmfranklin** [comment]
Looks like `upb` also ran into this issue. They vendored a patch here to solve it:

https://github.com/protocolbuffers/upb/blob/ec75a3cbb60ba714b14efafa76304544dbf38624/bazel/protobuf.patch#L60

However, this patch probably included more stuff than necessary to fix this. They did not provide enough context in the patch.

I'm still looking.

**Comment by qzmfranklin** [comment]
Alright, the following patch on `bc127f2b5605e5454d1c15d3325ecdd5ceaad6cf` worked:

```diff
 % git diff --cached 
diff --git a/python/internal.bzl b/python/internal.bzl
index 7441721e9..b0f590adc 100644
--- a/python/internal.bzl
+++ b/python/internal.bzl
@@ -1,5 +1,11 @@
 # Internal helpers for building the Python protobuf runtime.
 
+def _remove_cross_repo_path(path):
+    parts = path.split('/')
+    if parts[0] == '..':
+        return '/'.join(parts[2:])
+    return path
+
 def _internal_copy_files_impl(ctx):
     strip_prefix = ctx.attr.strip_prefix
     if strip_prefix[-1] != "/":
@@ -7,10 +13,11 @@ def _internal_copy_files_impl(ctx):
 
     src_dests = []
     for src in ctx.files.srcs:
-        if src.short_path[:len(strip_prefix)] != strip_prefix:
+        short_path = _remove_cross_repo_path(src.short_path)
+        if short_path[:len(strip_prefix)] != strip_prefix:
             fail("Source does not start with %s: %s" %
-                 (strip_prefix, src.short_path))
-        dest = ctx.actions.declare_file(src.short_path[len(strip_prefix):])
+                 (strip_prefix, short_path))
+        dest = ctx.actions.declare_file(short_path[len(strip_prefix):])
         src_dests.append([src, dest])
 
     if ctx.attr.is_windows:
```

**Comment by qzmfranklin** [comment]
Basically, upb's fix is good. But its patch included other irrelevant stuff.
