### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Serializing tc.i to a byte array threw an IOException (should never happen).

### ISSUE THREAD

**Issue by PrachiPardeshi09** [protocolbuffers/protobuf#12563]
**What version of protobuf and what language are you using?**
[com.sunstone.hub_issue_e8b10b95ae2f6218a1def6e48c60f178_crash_session_6440228502A4000147CD72082B259509_DNE_0_v2_stacktrace.txt](https://github.com/protocolbuffers/protobuf/files/11329955/com.sunstone.hub_issue_e8b10b95ae2f6218a1def6e48c60f178_crash_session_6440228502A4000147CD72082B259509_DNE_0_v2_stacktrace.txt)

  firebase_performance: ^0.9.0+15
Language: flutter
os: MacOS

Fatal Exception: java.lang.RuntimeException: Serializing tc.i to a byte array threw an IOException (should never happen).
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:26)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:12)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:38)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:18)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:38)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:2)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:20)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:52)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:50)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Caused by com.google.protobuf.l$d: CodedOutputStream was writing to a flat byte array and ran out of space.
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeStringNoTag(CodedOutputStream.java:70)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeString(CodedOutputStream.java:4)
       at com.google.protobuf.CodedOutputStreamWriter.writeString(CodedOutputStreamWriter.java:2)
       at com.google.protobuf.MessageSchema.writeString(MessageSchema.java:6)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:1061)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:16)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:4)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessageList(CodedOutputStreamWriter.java:11)
       at com.google.protobuf.SchemaUtil.writeMessageList(SchemaUtil.java:8)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:778)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:16)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:4)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:1048)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:12)
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:10)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:12)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:38)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:18)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:38)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:2)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:20)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:52)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:50)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.lang.ArrayIndexOutOfBoundsException: Failed writing a at index 261
       at com.google.protobuf.Utf8$SafeProcessor.encodeUtf8(Utf8.java:249)
       at com.google.protobuf.Utf8.encode(Utf8.java:2)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeStringNoTag(CodedOutputStream.java:32)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeString(CodedOutputStream.java:4)
       at com.google.protobuf.CodedOutputStreamWriter.writeString(CodedOutputStreamWriter.java:2)
       at com.google.protobuf.MessageSchema.writeString(MessageSchema.java:6)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:1061)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:16)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:4)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessageList(CodedOutputStreamWriter.java:11)
       at com.google.protobuf.SchemaUtil.writeMessageList(SchemaUtil.java:8)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:778)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:16)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:4)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:1048)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:20)
       at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:12)
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:10)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:12)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:38)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:18)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:38)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:2)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:20)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:52)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:50)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by PrachiPardeshi09** [comment]
firebase_performance: ^0.9.0+15

**Comment by somePeopleFireAndWood** [comment]
I'm  using version protobuf-java-3.12.2 .This exception can also occur, but it is not inevitable and the probability of it happening is very small.

**Comment by somePeopleFireAndWood** [comment]
> I'm using version protobuf-java-3.12.2 .This exception can also occur, but it is not inevitable and the probability of it happening is very small.

I use message.toByteArray() in a concurrent environment, and this problem does occur. But what I don't understand is that even if multiple threads calculate getSerializedSize() concurrently, the result should be the same value. Why is there a calculation error?

**Comment by somePeopleFireAndWood** [comment]
> > I'm using version protobuf-java-3.12.2 .This exception can also occur, but it is not inevitable and the probability of it happening is very small.
> 
> I use message.toByteArray() in a concurrent environment, and this problem does occur. But what I don't understand is that even if multiple threads calculate getSerializedSize() concurrently, the result should be the same value. Why is there a calculation error?

In a concurrent environment, I will set a new value for the builder's field in one thread, call the build() method of the same builder object, and call the toByteArray method of the same mesaage object in several other threads.
It is worth emphasizing that 1. I will not add to the collection of builders that have been placed in the concurrent environment. All collections are created in a single thread to create a builder object, fill the collection, and after the filling is completed, assign this builder object to other builders. ;2. All builder objects will not be set filed in multiple threads. For a builder object, field will only be set in one thread.
I can't understand why this exception occurs.
The probability of this exception occurring in my program is very low, probably one in hundreds of millions.
