### ISSUE TITLE
Address Sanitizer failure during unit tests

### ISSUE THREAD

**Issue by keith-bennett-airmap** [protocolbuffers/protobuf#12653]
**What version of protobuf and what language are you using?**
Version: reproduced with v22.2 and main (currently at d96032d1a501d8d8ee2f581d0a9597d631797c5f). **Not reproducible with v21.12**.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 20.04 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 11
```
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**What did you do?**

This is reproducible with the attached Dockerfile (`.txt` because Github): [Dockerfile.txt](https://github.com/protocolbuffers/protobuf/files/11391575/Dockerfile.txt)
```bash
docker build --target toolchain --tag toolchain -f Dockerfile.txt ./
docker build --target protobuf-build-test-install --tag protobuf -f Dockerfile.txt ./
```

Or manual steps to reproduce the behavior:
```bash
mkdir -p ~/src/public
cd ~/src/public
git clone https://github.com/protocolbuffers/protobuf
cd protobuf
git checkout v22.2
git submodule update --init --recursive
mkdir build
cd build
export CC_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
export CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
export LDFLAGS="-fsanitize=address -fno-omit-frame-pointer"
cmake -DCMAKE_BUILD_TYPE="Debug" ../
make -j$(nproc)
make test
```

**What did you expect to see**
`make test` -> should all pass.

**What did you see instead?**
`make test` ->
```
Running tests...
Test project /home/kbennett/src/public/protobuf/build
    Start 1: lite-test
1/2 Test #1: lite-test ........................   Passed    0.03 sec
    Start 2: full-test
2/2 Test #2: full-test ........................***Failed   21.08 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =  21.12 sec

The following tests FAILED:
          2 - full-test (Failed)
Errors while running CTest
Output from these tests are in: /home/kbennett/src/public/protobuf/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```

then, `tail -n 40 ./Testing/Temporary/LastTest.log` ->
```
[       OK ] Utf8ValidationTest.ParseRepeatedString (0 ms)
[ RUN      ] Utf8ValidationTest.OldVerifyUTF8String
AddressSanitizer:DEADLYSIGNAL
=================================================================
==604529==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f45735966e5 bp 0x7fff6d19d450 sp 0x7fff6d19cbe8 T0)
==604529==The signal is caused by a READ memory access.
==604529==Hint: address points to the zero page.
    #0 0x7f45735966e5  (/lib/x86_64-linux-gnu/libc.so.6+0x1886e5)
    #1 0x7f4573a3da2b in __interceptor_strlen ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:387
    #2 0x555bd719c0c8 in std::char_traits<char>::length(char const*) /usr/include/c++/11/bits/char_traits.h:371
    #3 0x555bd719d3fd in std::basic_string_view<char, std::char_traits<char> >::basic_string_view(char const*) /usr/include/c++/11/string_view:133
    #4 0x555bd8409b5d in google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*) /home/kbennett/src/public/protobuf/src/google/protobuf/wire_format_lite.cc:642
    #5 0x555bd7701308 in google::protobuf::internal::WireFormat::VerifyUTF8String(char const*, int, google::protobuf::internal::WireFormat::Operation) /home/kbennett/src/public/protobuf/src/google/protobuf/wire_format.h:360
    #6 0x555bd76f3440 in TestBody /home/kbennett/src/public/protobuf/src/google/protobuf/wire_format_unittest.inc:1554
    #7 0x555bd85164d8 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2601
    #8 0x555bd850ffa0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2637
    #9 0x555bd84ede15 in testing::Test::Run() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2676
    #10 0x555bd84ee8e8 in testing::TestInfo::Run() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2855
    #11 0x555bd84ef226 in testing::TestSuite::Run() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:3014
    #12 0x555bd84ff458 in testing::internal::UnitTestImpl::RunAllTests() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:5872
    #13 0x555bd85173a5 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2601
    #14 0x555bd8510f9e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:2637
    #15 0x555bd84fda7a in testing::UnitTest::Run() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/src/gtest.cc:5446
    #16 0x555bd845d7a3 in RUN_ALL_TESTS() /home/kbennett/src/public/protobuf/third_party/googletest/googletest/include/gtest/gtest.h:2293
    #17 0x555bd845d71c in main /home/kbennett/src/public/protobuf/third_party/googletest/googlemock/src/gmock_main.cc:70
    #18 0x7f4573432082 in __libc_start_main ../csu/libc-start.c:308
    #19 0x555bd71963ed in _start (/home/kbennett/src/public/protobuf/build/tests+0x1ab3ed)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x1886e5) 
==604529==ABORTING
<end of output>
Test time =  21.08 sec
----------------------------------------------------------
Test Failed.
"full-test" end time: May 03 13:00 CDT
"full-test" time elapsed: 00:00:21
----------------------------------------------------------

End testing: May 03 13:00 CDT
```
**Anything else we should know about your project / environment**
Tag `v21.12` does not exhibit this problem.
Log attached: [LastTest.log](https://github.com/protocolbuffers/protobuf/files/11389674/LastTest.log)

I can reproduce this in a Docker environment with Ubuntu 20.04. Dockerfile attached (`.txt` because Github): [Dockerfile.txt](https://github.com/protocolbuffers/protobuf/files/11391575/Dockerfile.txt)

**Comment by acozzette** [comment]
Thank you for the detailed bug report. This is now fixed in d38ba32c49bbb5a256746c7dc99eb5e543b0105a.
