### ISSUE TITLE
Stack smashing before `main()` caused by adding `import` to quick start's greeter proto file

### ISSUE THREAD

**Issue by keith-bennett-airmap** [protocolbuffers/protobuf#12732]
Note that I originally thought this is a bug in the gRPC generator, so I filed an issue [here](https://github.com/grpc/grpc/issues/33039). However, I have since realized that this is an issue in protobuf: I can reproduce the issue without grpc.

**What version of protobuf and what language are you using?**
Version: [v21.12](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/29d40d2e965add7292b03afc5f139145503bd17b)
Version: [v20.2](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/2cea6ecfce1c550d4c402be1a3176de535218cb1)
Version: [v19.5](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/a68a4539f6049234677364b640ee8f5345147d12)
Version: [v18.3](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/9f7b9e42c0946dfd091c817d429dd22b12ffeb6c)
Version: [v16.2](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/85d62995192dc4acf0e3bceb87c93c4270b1b11e)
Version: [v3.10.1](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/2abf3e2d167f769f62f580451ae568a45b9f0560)
Version: [v3.6.1.3](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/59019c58adaea01a566e246d2fea741e14b36c4b)

Language: C++

**What operating system (Linux, Windows, ...) and version?**
[Ubuntu 20.04 LTS](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/docker/ubuntu-2004-toolchain.Dockerfile#L2)

**What runtime / compiler are you using (e.g., python version or gcc version)**
`gcc --version` ->
```
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**What did you do?**
1. Use the `Greeter` service quickstart example from `grpc.io` found [here](https://grpc.io/docs/languages/cpp/quickstart/).
    1. Copy-pasted the first proto file text found in the quick start website into [`./src/proto/greeter.proto`](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/src/proto/greeter.proto)
    2. **I did _not_** copy [the .proto file from the grpc repository](https://github.com/grpc/grpc/blob/7155c92910aca35720d88b70bf827b051555cf9f/examples/protos/helloworld.proto)
2. [Add `import "google/api/field_behavior.proto";`](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/7155c92910aca35720d88b70bf827b051555cf9f) to import a `.proto` file from `googleapis` repository [here](https://github.com/googleapis/googleapis/blob/6f5d107aadb4782b71c530f4dc17ec86c922d8a9/google/api/field_behavior.proto).
3. Compile the .proto files to generate C++ header and source files into [a static library](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/proto/CMakeLists.txt)
4. [Instantiate](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/greeter-service/main.cpp#L14-L15) `HelloRequest` and `HelloReply` in [an executable which links against the static library](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/greeter-service/CMakeLists.txt#L6-L9)
5. [Run the built executable](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh#L10)

This is verified in a repository I created with a demonstration [here](https://github.com/keith-bennett-airmap/grpc-stacksmash).

You can run `./build.sh`. It will:
1. :warning: [Prune Docker then remove existing `protobuf-toolchain` and `protobuf-stacksmash` images](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh#L3-L4) to keep Docker from using tons of resources while iterating changes to the source tree
2. :information_source: [Find or create a few toolchain images](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/build.sh#L5)
    1. [Find, or create and tag, `ubuntu-2004-toolchain` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/docker/build.sh#L5-L7) which includes only the Ubuntu packages required to compile
        1. this takes a couple minutes
        2. `gcc-11` is [installed from ubuntu-toolchain PPA](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/ubuntu-2004-toolchain.Dockerfile#L16-L24)
    2. [Find, or create and tag, `cmake-toolchain` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/docker/build.sh#L8-L10) which builds and installs cmake from source
    3. [Find, or create and tag, `protobuf-toolchain` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/docker/build.sh#L11-L13) which builds and installs `protobuf` from source
        1. **NOTE: this image [enables Address Sanitizer via environment variables](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L4-L6) to enforce ASAN throughout the demonstration.**
        2. [Here](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L30) is `protobuf` version. Note that I use version `v21.12` due to [a separate issue found](https://github.com/protocolbuffers/protobuf/issues/12653) while constructing this demonstration.
        3. [Here](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L49) is `grpc` version
3. :information_source: [Create and tag a new `protobuf-stacksmash` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh#L9) which compiles a demonstration
4. :exclamation: [Runs the newly-created `protobuf-stacksmash` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh#L10) to demonstrate whether the resulting executable is viable

**What did you expect to see**
:heavy_check_mark: Per initial commit [here](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/e5d2b931dc2f86e68d85ace675050f2739be116d):
`./build.sh` ->
```
Successfully built 55df7a9eb834
Successfully tagged grpc-stacksmash:latest
greeter service created -- no stacksmash
```

**What did you see instead?**
:exclamation: :stop_sign: `./build.sh` ->
```
Successfully tagged protobuf-stacksmash:latest
*** stack smashing detected ***: terminated
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7f5ca1291941 bp 0x7ffcad720d20 sp 0x7ffcad720ac0 T0)
==1==The signal is caused by a READ memory access.
==1==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7f5ca1291941 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x22941)
    #1 0x7f5ca12fc26d  (/lib/x86_64-linux-gnu/libc.so.6+0x8d26d)
    #2 0x7f5ca139eab9 in __fortify_fail (/lib/x86_64-linux-gnu/libc.so.6+0x12fab9)
    #3 0x7f5ca139ea85 in __stack_chk_fail (/lib/x86_64-linux-gnu/libc.so.6+0x12fa85)
    #4 0x7f5ca1958f90 in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) google/protobuf/descriptor_database.cc:322
    #5 0x7f5ca1925663 in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) google/protobuf/descriptor.cc:1358
    #6 0x7f5ca191c49d in protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptorsImpl() google/protobuf/any.pb.cc:97
    #7 0x7f5ca17f84de in __pthread_once_slow (/lib/x86_64-linux-gnu/libpthread.so.0+0x114de)
    #8 0x7f5ca191c65e in __gthread_once /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:700
    #9 0x7f5ca191c65e in void std::call_once<void (&)()>(std::once_flag&, void (&)()) /usr/include/c++/11/mutex:783
    #10 0x7f5ca191c65e in void google::protobuf::internal::call_once<std::once_flag&, void (&)()>(std::once_flag&, void (&)()) google/protobuf/stubs/once.h:91
    #11 0x7f5ca191c65e in protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors() google/protobuf/any.pb.cc:105
    #12 0x7f5ca24b3b99  (/lib64/ld-linux-x86-64.so.2+0x11b99)
    #13 0x7f5ca24b3ca0  (/lib64/ld-linux-x86-64.so.2+0x11ca0)
    #14 0x7f5ca24a3139  (/lib64/ld-linux-x86-64.so.2+0x1139)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x22941) in abort
==1==ABORTING
```

**Anything else we should know about your project / environment**

[`./build.sh`](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh) is the driver for the demo.

`./docker` contains Dockerfiles and scripts to set up the build toolchain.
`./docker/ubuntu-2004-toolchain.Dockerfile` installs GCC
`./docker/cmake-toolchain.Dockerfile` inherits `FROM ubuntu-2004-toolchain` and builds & installs cmake
`./docker/protobuf-toolchain.Dockerfile` inherits `FROM cmake-toolchain` and builds & installs protobufs (especially protoc). The version of protobuf [can be configured as an argument](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/docker/protobuf-toolchain.Dockerfile#L8).
`./Dockerfile` inherits `FROM protobuf-toolchain` and builds the project with cmake.

`./src` contains the stack smashing demo
`./src/proto/external` contains [a static library](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/proto/external/CMakeLists.txt#L2-L5) whose only purpose is to compile external proto files -- eg [proto files](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/proto/external/google/api/field_behavior.proto) that were nominally downloaded from elsewhere (eg, [here](https://github.com/googleapis/googleapis/blob/6f5d107aadb4782b71c530f4dc17ec86c922d8a9/google/api/field_behavior.proto).
`./src/proto` contains [a static library](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/proto/CMakeLists.txt#L6-L9) whose only purpose is to compile proto files into a static library. It contains [the greeter service proto](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/proto/greeter.proto). It then links to and imports the external protos.
`./src/greeter-service` contains an executable. Its only purpose is [to link against the static proto library](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/greeter-service/CMakeLists.txt#L6-L9) and [instantiate the objects that were generated](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/src/greeter-service/main.cpp#L14-L15).

The [`./Dockerfile` then sets greeter-service as its entrypoint](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/Dockerfile#L28) so that [`docker run` will run the demo](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/59019c58adaea01a566e246d2fea741e14b36c4b/build.sh#L10).

**Comment by keith-bennett-airmap** [comment]
Note: other (golang) projects in the larger product use protobuf v22.2. I couldn't use that because of build issues.

I've tracked those build issues down to a problem with Address Sanitizer which I normally have turned on for all debug builds. I have created [a separate issue](https://github.com/protocolbuffers/protobuf/issues/12734) for that problem.

However, other than the build issue with Address Sanitizer, [v22.4 does not appear to have this stack smashing issue](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/817efe0577bb440572b51c516b37b895d0378372).

**Comment by keith-bennett-airmap** [comment]
This stack smashing issue has cropped up, in a private repository, once or twice since last posting here. The most recent workaround seems to be to use the minimal grpc lib instead of the full grpc lib, but I'm not convinced that truly solves the problem since it appears to be related to protobuf itself.
