### ISSUE TITLE
google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_pb.rb:13: [BUG] Segmentation fault at 0x0000000000003920 ruby 3.2.2 (2023-03-30 revision e51014f9c0)

### ISSUE THREAD

**Issue by dwilkie** [protocolbuffers/protobuf#13411]
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc. (NOTE: please try updating to the latest version of protoc/runtime possible beforehand to attempt to resolve your problem)
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

Version: google-protobuf gem 3.24.0.rc.2
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Linux ruby:3.2-alpine

**What runtime / compiler are you using (e.g., python version or gcc version)**

ruby 3.2.2

**What did you do?**

Run our build in Docker (the failing step is rake assets:precompile)

**What did you expect to see**

A successful build with no errors

**What did you see instead?**

A segfault

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Our tests run fine, this is the docker build

Here is the backtrace of the error:

```
#19 [build-env 11/13] RUN bundle exec rails assets:precompile
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_pb.rb:13: [BUG] Segmentation fault at 0x0000000000003920
#19 300.3 ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux-musl]
#19 300.3 
#19 300.3 -- Control frame information -----------------------------------------------
#19 300.3 c:0053 p:---- s:0382 e:000381 CFUNC  :add_serialized_file
#19 300.3 c:0052 p:0022 s:0377 e:000376 TOP    /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_pb.rb:13 [FINISH]
#19 300.3 c:0051 p:---- s:0367 e:000366 CFUNC  :require
#19 300.3 c:0050 p:0011 s:0362 e:000361 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0049 p:0158 s:0347 e:000346 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0048 p:0055 s:0337 e:000336 METHOD /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38
#19 300.3 c:0047 p:0013 s:0329 e:000328 TOP    /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_dsl.rb:9 [FINISH]
#19 300.3 c:0046 p:---- s:0325 e:000324 CFUNC  :require
#19 300.3 c:0045 p:0011 s:0320 e:000319 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0044 p:0158 s:0305 e:000304 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0043 p:0055 s:0295 e:000294 METHOD /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38
#19 300.3 c:0042 p:0070 s:0287 e:000286 TOP    /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf.rb:57 [FINISH]
#19 300.3 c:0041 p:---- s:0284 e:000283 CFUNC  :require
#19 300.3 c:0040 p:0011 s:0279 e:000278 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0039 p:0158 s:0264 e:000263 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0038 p:0055 s:0254 e:000253 METHOD /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38
#19 300.3 c:0037 p:0005 s:0246 e:000245 TOP    /app/vendor/bundle/ruby/3.2.0/gems/pg_query-4.2.1/lib/pg_query/pg_query_pb.rb:4 [FINISH]
#19 300.3 c:0036 p:---- s:0243 e:000242 CFUNC  :require
#19 300.3 c:0035 p:0011 s:0238 e:000237 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0034 p:0158 s:0223 e:000222 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0033 p:0055 s:0213 e:000212 METHOD /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38
#19 300.3 c:0032 p:0017 s:0205 e:000204 TOP    /app/vendor/bundle/ruby/3.2.0/gems/pg_query-4.2.1/lib/pg_query.rb:4 [FINISH]
#19 300.3 c:0031 p:---- s:0202 e:000201 CFUNC  :require
#19 300.3 c:0030 p:0011 s:0197 e:000196 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0029 p:0158 s:0182 e:000181 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0028 p:0055 s:0172 e:000171 METHOD /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38
#19 300.3 c:0027 p:0025 s:0164 e:000163 BLOCK  /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:60 [FINISH]
#19 300.3 c:0026 p:---- s:0159 e:000158 CFUNC  :each
#19 300.3 c:0025 p:0042 s:0155 e:000154 BLOCK  /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:55 [FINISH]
#19 300.3 c:0024 p:---- s:0148 e:000147 CFUNC  :each
#19 300.3 c:0023 p:0026 s:0144 e:000143 METHOD /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:44
#19 300.3 c:0022 p:0013 s:0139 e:000138 METHOD /usr/local/bundle/gems/bundler-2.4.17/lib/bundler.rb:187
#19 300.3 c:0021 p:0070 s:0134 e:000133 TOP    /app/config/application.rb:15 [FINISH]
#19 300.3 c:0020 p:---- s:0131 e:000130 CFUNC  :require
#19 300.3 c:0019 p:0011 s:0126 e:000125 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0018 p:0158 s:0111 e:000110 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0017 p:0011 s:0101 e:000100 TOP    /app/Rakefile:4 [FINISH]
#19 300.3 c:0016 p:---- s:0098 e:000097 CFUNC  :load
#19 300.3 c:0015 p:0005 s:0093 e:000092 METHOD /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29
#19 300.3 c:0014 p:0141 s:0088 e:000087 METHOD /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710
#19 300.3 c:0013 p:0003 s:0082 e:000081 BLOCK  /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104
#19 300.3 c:0012 p:0002 s:0079 e:000078 METHOD /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186
#19 300.3 c:0011 p:0004 s:0074 e:000073 METHOD /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103
#19 300.3 c:0010 p:0019 s:0070 e:000069 BLOCK  /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:20
#19 300.3 c:0009 p:0023 s:0066 e:000065 METHOD /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59
#19 300.3 c:0008 p:0009 s:0060 e:000059 METHOD /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18
#19 300.3 c:0007 p:0181 s:0053 e:000052 METHOD /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51
#19 300.3 c:0006 p:0038 s:0041 e:000040 TOP    /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18 [FINISH]
#19 300.3 c:0005 p:---- s:0036 e:000035 CFUNC  :require
#19 300.3 c:0004 p:0011 s:0031 e:000030 METHOD <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37
#19 300.3 c:0003 p:0158 s:0016 e:000015 METHOD /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
#19 300.3 c:0002 p:0024 s:0006 e:000005 EVAL   bin/rails:4 [FINISH]
#19 300.3 c:0001 p:0000 s:0003 E:0011e0 DUMMY  [FINISH]
#19 300.3 
#19 300.3 -- Ruby level backtrace information ----------------------------------------
#19 300.3 bin/rails:4:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
#19 300.3 /app/Rakefile:4:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/config/application.rb:15:in `<main>'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler.rb:187:in `require'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `require'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `each'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `block in require'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `each'
#19 300.3 /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/pg_query-4.2.1/lib/pg_query.rb:4:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/pg_query-4.2.1/lib/pg_query/pg_query_pb.rb:4:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf.rb:57:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_dsl.rb:9:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_pb.rb:13:in `<main>'
#19 300.3 /app/vendor/bundle/ruby/3.2.0/gems/google-protobuf-3.24.0.rc.2-aarch64-linux/lib/google/protobuf/descriptor_pb.rb:13:in `add_serialized_file'
#19 300.3 
#19 300.3 -- Machine register context ------------------------------------------------
#19 300.3   x0: 0x000000550301cf5d  x1: 0x00000055229c5edd  x2: 0x0000000000000003
#19 300.3   x3: 0x00000000000001c3  x4: 0x00000055229c5a30  x5: 0x0000000000000000
#19 300.3   x6: 0x0000000000000088  x7: 0xfffffffffffffff6 x18: 0x00000055224e0de0
#19 300.3  x19: 0x0000000000000003 x20: 0x0000005525548000 x21: 0x00000055254e9c80
#19 300.3  x22: 0x00000055255487f0 x23: 0x000000550301cf40 x24: 0x000000550301d4f0
#19 300.3  x25: 0x0000005525548000 x26: 0x00000055229c5edd x27: 0x0000000000000003
#19 300.3  x28: 0x0000005523618150 x29: 0x000000550301cef0  sp: 0x000000550301cef0
#19 300.3  fau: 0x0000000000003920
```

**Comment by dwilkie** [comment]
Very similar to https://github.com/protocolbuffers/protobuf/issues/10815

**Comment by fowles** [comment]
I think alpine is using musl and we don't support that for our binary gems https://github.com/protocolbuffers/protobuf/issues/12904#issuecomment-1589718935 has more details
