### ISSUE TITLE
upb_proto_library does not respect strip_import_prefix

### ISSUE THREAD

**Issue by bholmes-sc** [protocolbuffers/protobuf#13747]
When using `strip_include_prefix` in the proto_library() declaration, the upb_proto_library rule will fail.

```
ERROR: /Users/bholmes/Dev/upb/upb/test/BUILD:174:14: in //bazel:upb_proto_library.bzl%upb_proto_library_aspect aspect on proto_library rule //upb/test:test_stripped_prefix_proto:
Traceback (most recent call last):
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 320, column 34, in upb_proto_library_aspect_impl
		return _upb_proto_aspect_impl(target, ctx, "upb", UpbWrappedCcInfo, UpbWrappedGeneratedSrcsInfo)
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 299, column 32, in _upb_proto_aspect_impl
		files = _compile_upb_protos(ctx, generator, proto_info, proto_info.direct_sources)
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 235, column 34, in _compile_upb_protos
		srcs = [_generate_output_file(ctx, name, ext + ".c") for name in proto_sources]
	File "/Users/bholmes/Snapchat/Dev/upb/bazel/upb_proto_library.bzl", line 90, column 39, in _generate_output_file
		real_short_path = paths.relativize(real_short_path, package)
	File "/private/var/tmp/_bazel_bholmes/3427c17ac33700191f21c746618a87c9/external/bazel_skylib/lib/paths.bzl", line 182, column 13, in _relativize
		fail("Path '%s' is not beneath '%s'" % (path, start))
```

The build configuration I have looks like this:
```
proto_library(
    name = "test_stripped_prefix_proto",
    srcs = ["test_stripped_prefix.proto"],
    strip_import_prefix = "",
)

upb_proto_library(
    name = "test_stripped_prefix_upb_proto",
    testonly = 1,
    visibility = ["//:__subpackages__"],
    deps = [":test_stripped_prefix_proto"],
)
```

**Comment by haberman** [comment]
We are now using `proto_common.compile()`, so this issue should be resolved: https://github.com/protocolbuffers/protobuf/blob/df57e5474bf3ce211329e55993cb991a7ce1c5e0/bazel/upb_proto_library_internal/aspect.bzl#L95-L101
