### ISSUE TITLE
Generated message class "Foo" missing method "Bar".

### ISSUE THREAD

**Issue by nbali** [protocolbuffers/protobuf#13837]
**What version of protobuf and what language are you using?**
com.google.protobuf:protobuf-java:3.22.5
- works
com.google.protobuf:protobuf-java:3.23.0
- fails
com.google.protobuf:protobuf-java:3.24.2
- fails

My guess is that https://github.com/protocolbuffers/protobuf/commit/2a55706f9d36afd1742c97fd0d611ea8af0ac3f8 is the culprit.

The replacements with `hasPresence()` introduced a new condition that sets `hasHasMethod` to true:
https://github.com/protocolbuffers/protobuf/blob/8f1c050c2a2407215061b5872d891e61935efd1f/java/core/src/main/java/com/google/protobuf/Descriptors.java#L1304

**What operating system (Linux, Windows, ...) and version?**
w10pro dev, ubuntu-latest cicd

**What runtime / compiler are you using (e.g., python version or gcc version)**
```proto
syntax = "proto3";

package XXX;

option go_package = "./XXX/experiments";
option java_multiple_files = true;
option java_package = "com.XXX.experiments";
option java_outer_classname = "ProtoCTestDescriptors";
option php_namespace = "XXX\\Experiments";

message ProtoCTest {
    uint32 id = 1;

    oneof variant_nullable {
         uint32 variant = 2;
    }

    oneof real_ctest_id_nullable {
         uint32 real_ctest_id = 3;
    }
}

**What did you do?**
```java
ProtoCTest.Builder builder = ProtoCTest.newBuilder();
builder.getField(null /* input is irrelevant */);
```

**What did you expect to see**
Shouldn't fail.

**What did you see instead?**
```
Exception in thread "main" java.lang.IllegalStateException: Generated message class "com.XXX.experiments.ProtoCTest" missing method "hasVariant".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:2014)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2399)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2465)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2163)
	at com.XXX.experiments.ProtoCTest$Builder.internalGetFieldAccessorTable(ProtoCTest.java:440)
	at com.google.protobuf.GeneratedMessageV3$Builder.getField(GeneratedMessageV3.java:752)
	at XXX.main(XXX.java:38)
Caused by: java.lang.NoSuchMethodException: com.XXX.experiments.ProtoCTest.hasVariant()
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:2011)
	... 7 more

```

**Anything else we should know about your project / environment**

**Comment by hlopko** [comment]
The change you mention has been rolled back already, could you try to reproduce with the latest protobuf version?

**Comment by zhangskz** [comment]
Hi, this was rolled back in v24.4 and v25.x releases per https://github.com/protocolbuffers/protobuf/commit/2a55706f9d36afd1742c97fd0d611ea8af0ac3f8#r128350688 and https://github.com/protocolbuffers/protobuf/issues/14245 since this behavior change was known but unintentionally broke compatibility with old gencode. We still intend to reintroduce this change in 26.x, when we intend to increase the Java major version.

In general, Protobuf should idelaly be used with gencode and runtime from *the same* version number. Stale gencode from a old major version will not be expected to work with new runtimes of a newer major version. See https://protobuf.dev/support/cross-version-runtime-guarantee/

Feel free to reopen if this still reproduces in the latest releases, or if you have any questions about this change.
