### ISSUE TITLE
Error in repository_rule: invalid user-provided repo name ''

### ISSUE THREAD

**Issue by mbwmbw1337** [protocolbuffers/protobuf#13883]
Ubuntu 

```
bazel --version
bazel 6.3.2
```
Trying to build protobuf with bazel 6.3.2.

```
/protobuf-3.20.3 # bazel build :protoc :protobuf
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "/root/protobuf-3.20.3/WORKSPACE", line 65, column 20, in <toplevel>
                kotlin_repositories()
        File "/root/.cache/bazel/_bazel_root/da5a704ea0fa5f9db1b86c42eca361e7/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
                rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
ERROR: Error computing the main repository mapping: at /root/.cache/bazel/_bazel_root/da5a704ea0fa5f9db1b86c42eca361e7/external/io_bazel_rules_kotlin/kotlin/core.bzl:2:5: at /root/.cache/bazel/_bazel_root/da5a704ea0fa5f9db1b86c42eca361e7/external/io_bazel_rules_kotlin/kotlin/internal/opts.bzl:22:5: Encountered error while reading extension file 'jvm/opts.bzl': no such package '@io_bazel_rules_kotlin_configured//jvm': error loading package 'external': Could not load //external package
Loading: 
```

**Comment by mbwmbw1337** [comment]
I'm an idiot - I was in the wrong folder. Apologies.
