### ISSUE TITLE
This is supposed to be overridden by subclasses.感觉是版本不匹配但是找不到合适版本，使用springboot3.x

### ISSUE THREAD

**Issue by 610268874** [protocolbuffers/protobuf#15183]
io.grpc.StatusRuntimeException: INTERNAL: Failed to frame message
	at io.grpc.Status.asRuntimeException(Status.java:529) ~[grpc-api-1.60.0.jar:1.60.0]
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:154) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:66) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.ServerCallImpl.sendMessageInternal(ServerCallImpl.java:168) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:152) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:380) ~[grpc-stub-1.60.0.jar:1.60.0]
	at com.dx.studio.rpc.OrderRpc.create(OrderRpc.java:27) ~[classes/:na]
	at com.dx.studio.order.grpc.OrderGrpc$MethodHandlers.invoke(OrderGrpc.java:302) ~[classes/:na]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.60.0.jar:1.60.0]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[grpc-api-1.60.0.jar:1.60.0]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[grpc-api-1.60.0.jar:1.60.0]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[grpc-api-1.60.0.jar:1.60.0]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[grpc-api-1.60.0.jar:1.60.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.58.0.jar:1.58.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
	at com.google.protobuf.GeneratedMessageV3.getUnknownFields(GeneratedMessageV3.java:302) ~[protobuf-java-3.11.4.jar:na]
	at com.dx.studio.order.grpc.CreateOrderResponse.getSerializedSize(CreateOrderResponse.java:109) ~[classes/:na]
	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108) ~[grpc-protobuf-lite-1.60.0.jar:1.60.0]
	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:208) ~[grpc-core-1.58.0.jar:1.58.0]
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:138) ~[grpc-core-1.58.0.jar:1.58.0]
	... 18 common frames omitted

**Comment by lujiang-web** [comment]
May I ask if you have resolved it？How was it resolved
