### ISSUE TITLE
Kotlin lite: Tried to write the same file twice

### ISSUE THREAD

**Issue by danielesegato** [protocolbuffers/protobuf#15606]
**What version of protobuf and what language are you using?**
Version: 3.21.11
Language: Java 1.8.0 / Kotlin 1.9.20
gradle 8.0
gradle proto plugin version 0.9.1

**What operating system (Linux, Windows, ...) and version?**
does not matter but i'm on the last MacOS with ARM processor.

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 17

**What did you do?**

Adding kotlin lite to a project where I only had java lite started to produce build error "Tried to write the same file twice" with the file name

Errors like:
  mypackage/RespKt.kt: Tried to write the same file twice.

to reproduce you just need two .proto file containing a message with the same name in the same java/kotlin package.

The `foo.proto` file
```proto
syntax = "proto3";

package foo;

option java_package = "mypackage";
option java_outer_classname = "Foo";
option java_multiple_files = false;

message Resp {
    bool success = 1;
}

// other stuff here specific to "Foo"
```

The `bar.proto` file:
```proto
syntax = "proto3";

package bar;

option java_package = "mypackage";
option java_outer_classname = "Bar";
option java_multiple_files = false;

message Resp {
    bool success = 1;
}

// other stuff here specific to "Bar"
```

**What did you expect to see**

When only java lite is configured this compiles and two Java classes are generated: Foo.java and Bar.java

The generated Java class looks like this:

```java
package mypackage;

public final class Foo {
  private Foo() {}
  // ...
  public  static final class Resp extends
      com.google.protobuf.GeneratedMessageLite<
          Resp, Resp.Builder> implements
      // @@protoc_insertion_point(message_implements:foo.Resp)
      RespOrBuilder {
    private Resp() {
    }
  // ...
}
```

And another `Bar` class is created with its own content.

aka: there's a main file for each, with a parent class containing all the messages.

When kotlin is enabled instead, if you do not have duplicates, multiple files are created, one for each message.

- `FooKt.kt` (empty)
- `RespKt.kt` containing a `RespKt` object with Dsl for kotlin

But I do not really "care" about these internals, I just wanted it to build the 2 proto with kotlin DSL.

**What did you see instead?**

Build fails with
```
Execution failed for task ':protobuf_model:generateProto'.
> protoc: stdout: . stderr: mypackage/RespKt.kt: Tried to write the same file twice.
```

and the stacktrace

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':protobuf_model:generateProto'.
[...]
Caused by: org.gradle.api.GradleException: protoc: stdout: . stderr: mypackage/RespKt.kt: Tried to write the same file twice.
	at com.google.protobuf.gradle.GenerateProtoTask.compileFiles(GenerateProtoTask.groovy:710)
	at com.google.protobuf.gradle.GenerateProtoTask.compile(GenerateProtoTask.groovy:655)
```

The reason is obviously because both `Foo.proto` and `Bar.proto` cause the generation of a `RespKt.kt` file.

**Anything else we should know about your project / environment**

This is the `build.gradle.kts` file I used, if you comment out the kotlin lite setup and dependency it compiles, or if you remove one of the two proto file (or rename Resp to something else) it also compiles even with kotlin enabled

```kotlin
import com.google.protobuf.gradle.id

plugins {
    id("java-library")
    kotlin("jvm")
    id("com.google.protobuf")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        // Set JVM target to 8
        jvmTarget = JavaVersion.VERSION_1_8.toString()
        // Treat all Kotlin warnings as errors (disabled by default)
        // Override by setting warningsAsErrors=true in your ~/.gradle/gradle.properties
        val warningsAsErrors: String? by project
        allWarningsAsErrors = warningsAsErrors.toBoolean()
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.11"
    }
    // Generates the java Protobuf-lite code for the Protobufs in this project. See
    // https://github.com/google/protobuf-gradle-plugin#customizing-protobuf-compilation
    // for more information.
    generateProtoTasks {
        // see https://github.com/google/protobuf-gradle-plugin/issues/518
        // see https://github.com/google/protobuf-gradle-plugin/issues/491
        ofSourceSet("main").forEach { task ->
            task.builtins {
                getByName("java") {
                    option("lite")
                }
                id("kotlin") {
                    option("lite")
                }
            }
        }
    }
}

dependencies {
    api("com.google.protobuf:protobuf-javalite:3.21.11")
    api("com.google.protobuf:protobuf-kotlin-lite:3.21.11")
}
```

The full stacktrace

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':protobuf_model:generateProto'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.api.GradleException: protoc: stdout: . stderr: mypackage/RespKt.kt: Tried to write the same file twice.
	at com.google.protobuf.gradle.GenerateProtoTask.compileFiles(GenerateProtoTask.groovy:710)
	at com.google.protobuf.gradle.GenerateProtoTask.compile(GenerateProtoTask.groovy:655)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:93)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:57)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:54)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:166)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeAndStoreInCache(BuildCacheStep.java:139)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$4(BuildCacheStep.java:106)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$5(BuildCacheStep.java:106)
	at org.gradle.internal.Try$Success.map(Try.java:164)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithCache(BuildCacheStep.java:80)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$0(BuildCacheStep.java:69)
	at org.gradle.internal.Either$Left.fold(Either.java:115)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:76)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:37)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:42)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:31)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
```

**Comment by buchgr** [comment]
@danielesegato could you please try and confirm that this issue persists with the latest version of protobuf (3.25.2)

**Comment by WessimBetclic** [comment]
Hello ! I have the exact same problem (I'm on 3.25.3, also tried 4.26.0)

**Comment by kewitschka** [comment]
Could you resolve the issue?

**Comment by ivanempire** [comment]
@buchgr This is still happening, just to answer your question. Stumbled upon this bug because of the same error @danielesegato is seeing above, and I was also able to reproduce their issue locally (with updated dependencies).

There is a workaround, however - I got my project + the one above to build by changing the `java_package` value to something else in the problematic proto. I guess there's some kind of collision happening?

**Comment by danielesegato** [comment]
@buchgr sorry I didn't answer your question before. As you can see from others comments the problem is still there.

**Comment by SashaCube** [comment]
I have encountered the same issue in my project.

Version: 4.28.2
Language: Kotlin 2.0.20
gradle 8.10
gradle proto plugin version 0.9.4

**Comment by feivur** [comment]
facing this issue

**Comment by Choucroute-melba** [comment]
Still facing the issue here, working with the proto files provided by Arduino CLI.

Protobuf version 3.29.3,
gradle plugin version 0.9.4

**Comment by danielesegato** [comment]
I've switched to square wire library for protobuf. It has way better support for kotlin.

**Comment by canatella** [comment]
Still happening on version 4.31.1

**Comment by esrauchg** [comment]
I know this will disappoint some folks here but I think this issue is basically "working as feasibly implemented"

The root cause in the initial report is basically deliberately opting into a collision; it is two different files whose contents which are only not an ODR violation / naming collision because they have different packages set. But, the files each override the java_package to be the same as each-other, which amounts to opting into a collision which was only avoided by the original package being different.

The fact that the specific example manages works at all in JavaProto but not KotlinProto is something of an happy accident, really these files should be understood to be colliding files which manages to work in JavaProto by luck and not really by design under exactly that combination of options. If you changed any one of the options (e.g. java_multiple_files=true) for example it would immediately hard break in JavaProto as well.

[The Best Practices documentation](https://protobuf.dev/best-practices/dos-donts/#:~:text=fully%2Dqualified%20name%20collisions) calls out using different .proto packages but reusing the same java_package as a pattern that may lead to breakages. For that reason it is best practice is to not reuse the same java_package in two files that have a different .proto package, preferably following a deterministic pattern where you decide a common prefix and then set java_package to that project-specific prefix and then the .proto package as a suffix.

Note that java_multiple_files=true is also independently considered best practice and is in the default under Edition 2024 files (where this has been replaced by the feature named [features.(pb.java).nest_in_file_class](https://protobuf.dev/editions/features/#java-nest_in_file) which you would have to affirmatively set to opt back into the java_multiple_files=false behavior).

You may find the file works in other implementations (as it works in our JavaProto implementation but not our KotlinProto one) and it may work in other implementation's including Square's, since they make slightly different code generation decision and won't happen to hit the specific collision here. Unfortunately in all of Google's official implementations and all third party Protobuf implementations it isn't difficult to construct an input .proto file that can result in generated code which has names which illegally collide if you try to.

If people have other cases of a breakage which is not the one in the initial report on this issue (and doesn't opt into a naming collision via a similar mechanism) please open new issues and we can take a look at them on a case by case basis.

Thanks all who commented here and sorry that this specific case is cantfix.

**Comment by danielesegato** [comment]
Alright, the fact this works with java but doesn't just adding kotlin lite is enough to show it's a bug.

When I've a working java lite protobuf and I add kotlin support I expect it to always work, I must not be forced to change the structure of my proto just because I want to add kotlin support.

Outer class name means Resp should become Foo.Resp and Bar.Resp. there should be no collision. The only reason there is a collision is that your project generate the class name as Resp.kt instead of Foo_Resp.kt or even just putting everything in a Foo.kt file or a more dumb Resp.kt, Resp_2.kt, Resp_3.kt handling.

Mine was just an example to show you a problem with your project.

It's your project, do as you please. It took a while to me to dig into what was going on and detail it as good as I could. 

To be honest I switched to square wire for a while now, it's just way better and easier to use in any regards. If you are forced into breaking changes might as well switch to something easier to configure and more reliable.


No hard feeling, just take this as feedback.

Cheers.

**Comment by esrauchg** [comment]
Understand and appreciate the feedback here.

It might be more clear to say that this is a bug of a class of bugs that we have no realistic mechanism to holistically prevent all cases of (in any of our language, and neither does any other third party Protobuf implementation).

So basically the linked best practice is really basically "try not to teeter right on the brink of naming collisions, because if you live one inch from the edge then it foreseeably will fall over when anything is perturbed". Thats very much still true and a good idea when using Square's Protobuf implementation, and true for people who intend to stick with JavaProto regardless if they intend to adopt our KotlinProto.

Using some combination of three options together as a way to try to be right up next to a direct name collision without actually hitting one may be sensible as a short term mitigation fix kind of change before getting things into a healthier state, but its very much teetering right up to the edge of a situtaion where JavaProto itself will have conflicts even if you don't adopt KotlinProto. For example, we also already do generate at least one additional file when java_multiple_files=false, it happens to be suffixed with 'InternalDescriptors' which makes organic collisions unlikely, but its already not the design that you are are exhaustively naming all of the exact class names when you set those options in JavaProto.
