### ISSUE TITLE
JsonFormat does not work for proto with optional fields

### ISSUE THREAD

**Issue by DragFAQ** [protocolbuffers/protobuf#15762]
**What version of protobuf and what language are you using?**
Version: main/v3.23.0
Language: Java

```
message GetRequest {
  int32 amount = 1;
  optional int32 amount_usd = 2;
  int32 range_random = 3;
}
```

When I use `JsonFormat.printer().preservingProtoFieldNames()` for this object, I receive an error 
```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2100)
	at some.v1alpha1.GetRequest.internalGetFieldAccessorTable(GetRequest.java:38)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:139)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:758)
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:367)
```

I found that it is because of OPTIONAL field. 
Here in **GeneratedMessageV3**
```
for(i = 0; i < fieldsSize; ++i) {
    Descriptors.FieldDescriptor field = (Descriptors.FieldDescriptor)this.descriptor.getFields().get(i);
    String containingOneofCamelCaseName = null;
    if (field.getContainingOneof() != null) {
      containingOneofCamelCaseName = this.camelCaseNames[fieldsSize + field.getContainingOneof().getIndex()];
    }
```

this.camelCaseNames tries to get 3rd item of 3 possible in array (0, 1st and 2nd)

It somehow thinks that my OPTIONAL field is ONEOF field and should have 4th element in array...

Is it possible to serialize proto with optional fields at all?

**Comment by DragFAQ** [comment]
fixed in 3.25.2
