### ISSUE TITLE
java.lang.RuntimeException: Generated message class "$packagename.Remotemessage$RemoteMessage$Builder" missing method "getRemoteConfigure".

### ISSUE THREAD

**Issue by dungtrn** [protocolbuffers/protobuf#16311]
What version of protobuf and what language are you using?
Version: 3.11.4
Language: Java + Kotlin
**What runtime / compiler are you using
Java/Kotlin
What did you do?

hi, I use protobuf commutine to my android Tv for remote, when create a createRemoteConfigure, I have this error, I have try bring all the code to another project, and it work well, didnt know where did i wrong

this is proto file 
message RemoteConfigure {
  int32 code1 = 1;
  RemoteDeviceInfo device_info = 2;
}

exception: java.lang.RuntimeException: Generated message class "$packagename.Remotemessage$RemoteConfigure$Builder" missing method "getCode1".

crash by: 
FATAL EXCEPTION: Thread-102
                                         Process: cast.chromecast.tv.screen.mirroring, PID: 25711
                                         java.lang.RuntimeException: Generated message class "com.hoang.androidtvremote.control.remote.Remotemessage$RemoteMessage$Builder" missing method "getRemoteConfigure".
                                         	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
                                         	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2179)
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2252)
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularMessageFieldAccessor.<init>(GeneratedMessageV3.java:2974)
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1970)
                                         	at com.hoang.androidtvremote.control.remote.Remotemessage$RemoteMessage.internalGetFieldAccessorTable(Remotemessage.java:17840)
                                         	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
                                         	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:364)
                                         	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:354)
                                         	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:619)
                                         	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
                                         	at java.lang.String.valueOf(String.java:4092)
                                         	at java.lang.StringBuilder.append(StringBuilder.java:179)
                                         	at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:293)
                                         	at com.hoang.androidtvremote.control.remote.RemotePacketParser.messageBufferReceived(RemotePacketParser.java:59)
                                         	at com.hoang.androidtvremote.control.wire.PacketParser.run(PacketParser.java:33)
                                         Caused by: java.lang.NoSuchMethodException: com.hoang.androidtvremote.control.remote.Remotemessage$RemoteMessage$Builder.getRemoteConfigure []
                                         	at java.lang.Class.getMethod(Class.java:2937)
                                         	at java.lang.Class.getMethod(Class.java:2449)
                                         	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
                                         	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79) 
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2179) 
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2252) 
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularMessageFieldAccessor.<init>(GeneratedMessageV3.java:2974) 
                                         	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1970) 
                                         	at com.hoang.androidtvremote.control.remote.Remotemessage$RemoteMessage.internalGetFieldAccessorTable(Remotemessage.java:17840) 
                                         	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133) 
                                         	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:364) 
                                         	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:354) 
                                         	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:619) 
                                         	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111) 
                                         	at java.lang.String.valueOf(String.java:4092) 
                                         	at java.lang.StringBuilder.append(StringBuilder.java:179) 
                                         	at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:293) 
                                         	at com.hoang.androidtvremote.control.remote.RemotePacketParser.messageBufferReceived(RemotePacketParser.java:59) 
                                         	at com.hoang.androidtvremote.control.wire.PacketParser.run(PacketParser.java:33)

**Comment by dungtrn** [comment]
> Java/Kotlin

Android

**Comment by acozzette** [comment]
This looks to me like it's probably an issue of how the code was built. I would recommend making sure that the protoc version used to generate code exactly matches the version of the protobuf runtime you're using. Also, 3.11.4 is a fairly old version at this point, so it might be a good idea to upgrade to a more recent version.

**Comment by dungtrn** [comment]
I check it again, and turn out, it was my progaurd-rules, how can i set rule for this

**Comment by SodaSurfer** [comment]
hi @dungtrn did you managed to get this to work?

**Comment by dungtrn** [comment]
hi, turn out, it my fail, because I build with proguard-rule and forgot keepclassmemeber
so sorry, will close this issue right now, thanks for your time buddy

**Comment by SodaSurfer** [comment]
@dungtrn I saw you are trying also to implement te voice control on android tv. did you managed to do this? what is your email, let's discuss on it.

**Comment by dungtrn** [comment]
dunglongtrn@gmail.com here is my email buddy, you can contact here
