### ISSUE TITLE
FileDescriptor's GetDebugString method(s) not present in Python API 

### ISSUE THREAD

**Issue by betmix-matt** [protocolbuffers/protobuf#16391]
Version: main/v26.1 
Language: Python

All operating systems

Re-opening #7484

```shell
python3 -m pip install protobuf==5.26.1
```

```python
#!/usr/bin/env python3
import logging
import sys

from google.protobuf.compiler import plugin_pb2 as plugin
from google.protobuf.descriptor_pb2 import FileDescriptorProto
from google.protobuf.descriptor_pool import DescriptorPool


logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)


def pre_process_file(
    proto_file: FileDescriptorProto, pool: DescriptorPool
) -> None:
    logger.info(f"Adding proto file to pool: {proto_file.name}")
    pool.Add(proto_file)

def process_file(
    proto_file: FileDescriptorProto, response: plugin.CodeGeneratorResponse, pool: DescriptorPool
) -> None:
    logger.info(f"Processing proto_file: {proto_file.name}")
    file = response.file.add()
    file.name = proto_file.name
    pool_file = pool.FindFileByName(proto_file.name)
    logger.info(f"Creating new file: {file.name}")
    file.content = pool_file.GetDebugString()


def process(
    request: plugin.CodeGeneratorRequest, response: plugin.CodeGeneratorResponse, pool: DescriptorPool
) -> None:
    for proto_file in request.proto_file:
        pre_process_file(proto_file, pool)
    for proto_file in request.proto_file:
        process_file(proto_file, response, pool)


def main() -> None:
    # Load the request from stdin
    request = plugin.CodeGeneratorRequest.FromString(sys.stdin.buffer.read())

    # Create a response
    response = plugin.CodeGeneratorResponse()

    pool = DescriptorPool()

    process(request, response, pool)

    # Serialize response and write to stdout
    sys.stdout.buffer.write(response.SerializeToString())


if __name__ == "__main__":
    main()

```

Create the following `plugin.py` then execute against any protobuf file:
```shell
protoc --plugin=protoc-gen-custom=./plugin.py --custom_out=out my-proto-file.proto
```

**What did you expect to see**

The `GetDebugString()` function should be called and the appropriate proto file should be output in the `out` directory as the contents of the GetDebugString function.

**What did you see instead?**

```shell
Traceback (most recent call last):
  File "./plugin.py", line 58, in <module>
    main()
  File "./plugin.py", line 51, in main
    process(request, response, pool)
  File "./plugin.py", line 39, in process
    process_file(proto_file, response, pool)
  File "./plugin.py", line 30, in process_file
    file.content = pool_file.GetDebugString()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'google._upb._message.FileDescriptor' object has no attribute 'GetDebugString'

```

**Comment by shaod2** [comment]
We don't support transforming descriptor into valid files. And DebugString() methods are only meant for **debugging** purposes not suitable for re-parsing.
