### ISSUE TITLE
Ruby google-protobuf linux precompiled gem crash with Segmentation fault on linux-musl

### ISSUE THREAD

**Issue by ntkme** [protocolbuffers/protobuf#16853]
**What version of protobuf and what language are you using?**
Version: 3.22.2 or higher on aarch64-linux-musl / 4.29.3 or higher on x86_64-linux-musl
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Alpine Linux any version

**What runtime / compiler are you using (e.g., python version or gcc version)**
Any ruby version

**What did you do?**
```
/ # gem install google-protobuf
Successfully installed google-protobuf-4.26.1-aarch64-linux
1 gem installed
/ # ruby -e "require 'google/protobuf'"
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- google/protobuf_c (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:15:in `rescue in <top (required)>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:12:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
	from -e:1:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.3/protobuf_c.so) - /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.3/protobuf_c.so (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:13:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
	from -e:1:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- google/protobuf (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from -e:1:in `<main>'
```

**What did you expect to see**
google-protobuf should work on linux-musl just like how it works on linux-gnu

**What did you see instead?**
google-protobuf prebuilt library is strictly linked to glibc and it's not compatible with musl-libc 

**Anything else we should know about your project / environment**
Please see rake-compiler's documentation regarding recent changes in rubygems in regarding to -linux, -linux-gnu, and -linux-musl platforms: https://github.com/rake-compiler/rake-compiler-dock?tab=readme-ov-file#linux-gnu-and-musl-important-details

**Comment by ntkme** [comment]
As a workaround, uninstalling the prebuilt gem and reinstall platform ruby to build from source fixes the issue:

```
/ # gem uninstall google-protobuf
Successfully uninstalled google-protobuf-4.26.1-aarch64-linux
/ # apk add alpine-sdk
...
/ # gem install --platform ruby google-protobuf
Fetching google-protobuf-4.26.1.gem
Building native extensions. This could take a while...
Successfully installed google-protobuf-4.26.1
1 gem installed
/ # ruby -e "require 'google/protobuf'"
```

**Comment by ntkme** [comment]
There are a few options here:

1. Do not ship `aarch64-linux` gem, and let both `aarch64-linux-gnu` and `aarch64-linux-musl` platform fallback to platform ruby and compile from source. 
2. Ship the current flavor, but label it as `aarch64-linux-gnu`, so that it does not get installed incorrectly on `aarch64-linux-musl`.
3. Upgrade rake-compiler, and ship separate `aarch64-linux-gnu` and `aarch64-linux-musl` gems.

Again, please refer to rake-compiler's documentation on details: https://github.com/rake-compiler/rake-compiler-dock?tab=readme-ov-file#linux-gnu-and-musl-important-details

**Comment by ntkme** [comment]
Alternative fix can be that simply do not publish `aarch64-linux` in the next release.

**Comment by JasonLunn** [comment]
@dazuma - what's the expect platform support for `linux-musl`?

**Comment by ntkme** [comment]
As said early, even if we don't "officially" support linux-musl, we can avoid it from breaking out of box. - Just ship the gem with label `-linux-gnu` instead of `-linux` using latest `rake-compiler`.

**Comment by henrahmagix** [comment]
I'd really appreciate if @ntkme's comment could be actioned pls ☺️
> ship the gem with label `-linux-gnu` instead of `-linux` using latest `rake-compiler`

**Comment by ntkme** [comment]
I was probably the earliest adaptor of splitting `linux-gnu` and `linux-musl` prebuilt, as I introduced it way before `rake-compiler` added support, using my own custom cross-platform build scripts. I have been through lots of trouble with rubygems/bundler's bug around this area in terms of platform detection and even helped fixing a few bugs in rubygems/bundler.

From my own experience with it, I can say that as of now it's reliable with ruby >=3.1 and the default rubygems/bundler or higher version from them. In fact, `nokogiri`, one of the most downloaded gem of all time, introduced split `-linux-gnu` and `-linux-musl` with 1.18.0 release this month: https://rubygems.org/gems/nokogiri/versions

Now it's time to adopt `-linux-gnu` and `-linux-musl` gems.

**Comment by dazuma** [comment]
I share the desire to split the builds into `-linux-gnu` and `-linux-musl` as soon as possible. However, we cannot until April 2025 because our [support policy](https://cloud.google.com/ruby/getting-started/supported-ruby-versions) doesn't drop Ruby 3.0 until then. Once we're able to drop support for Ruby 3.0, we'll definitely split the builds with the next protobuf release.

**Comment by ntkme** [comment]
@dazuma In fact shipping separate `-gnu` and `-musl` does not require dropping Ruby 3.0.

The way it works is that you can set different ruby version and rubygems version requirements on the platform ruby gem and native prebuilt gems.

For example:
- https://rubygems.org/gems/sass-embedded/versions/1.83.4 - platform ruby requires ruby 3.1
- https://rubygems.org/gems/sass-embedded/versions/1.83.4-aarch64-linux-gnu - native gem requires ruby 3.2

- https://rubygems.org/gems/nokogiri/versions/1.18.1 -platform ruby gem requires ruby 3.1
- https://rubygems.org/gems/nokogiri/versions/1.18.1-x86_64-linux-gnu - native gem requires ruby 3.1 AND rubygems 3.3.22

This allow older version of ruby and rubygems/bundler to install the gem by compiling from source. For google-protobuf, we can require 3.0 on the platform ruby gem, and require ruby 3.0 AND rubygems 3.3.22.


You can learn more here about in this issue: https://github.com/rake-compiler/rake-compiler-dock/issues/117 and why ruby 3.2 instead of rubygems 3.3.22 on native gem might be a better idea in this comment https://github.com/rake-compiler/rake-compiler-dock/issues/117#issuecomment-2101338327

**Comment by dazuma** [comment]
@ntkme It sounds like the above would force ALL users of Ruby 3.0 on Linux to install the gem from source. That's a regression we're trying to avoid.

(The news about Debian-sid and Ruby 3.1 is also disappointing. But I don't think we can wait another year for this.)

**Comment by ntkme** [comment]
Yes, I agree not able to use prebuilt is a “regression”. However, I’d argue it’s way better than segmentation fault on musl-libc, especially that 4.29.3 literally just regressed with segmentation fault on x86_64-linux-musl. It used to have segmentation fault only on aarch64-linux-musl, which is a very tiny user base, but now impacting many more users.

The 4.29.3 segmentation fault regression on all ruby versions on x86_64-linux-musl is much worse than asking ruby 3.0 on any linux to compile from source. I think it’s worth trading the compiling from source “regression” to fix the segmentation fault, especially given that the compiling from source “regression” will likely break much smaller number of installation on ruby 3.0 on Linux without a working compiler. The installation time error will be more trivial for users to deal with than a runtime segmentation fault, and likely only impact a much smaller user base.

After all, I don’t have statistics to proof it, but here are the two things we are trading:
- ruby 3.0-3.4 *-linux-musl crashing with segmentation fault
- ruby 3.0 *-linux-* without a working compiler failing to install

I would recommend that we don’t wait.

**Comment by jeffque** [comment]
The current suggested workaround had some problems to me, as in my CI the `Gemfile.lock` was frozen.

For me, this was the workaround:

```ruby
gem 'google-protobuf', force_ruby_platform: RUBY_PLATFORM.include?('linux-musl')
```

Pretty similar to the one suggested by @ntkme , but the gem is added regardless of platform. In my case, the gem was added as a transitive dependency from `sass-embedded` gem.

Running with my workaround: https://gitlab.com/computaria/blog/-/jobs/9012424269

Running with the workaround from @ntkme: https://gitlab.com/computaria/blog/-/jobs/9012354715

Notice the error:

```none
Installing bundler 2.5.11
Bundler is unlocking ruby, but the lockfile can't be updated because frozen mode
is set
You have added to the Gemfile:
* google-protobuf
Run `bundle install` elsewhere and add the updated Gemfile to version control.
```

**Comment by ntkme** [comment]
@dazuma April is coming soon. Can we formally put this on the roadmap of next v31 release?

**Comment by JasonLunn** [comment]
Work to drop Ruby 3.0 and update to a newer bundler version is in progress, stay tuned for further updates.

**Comment by ntkme** [comment]
I see that we merged the commit to drop Ruby 3.0. Next step would be update rake-compiler / rake-compiler-dock, so that we can relabel the `-linux` gem to `-linux-gnu`, and optionally publish a separate `-linux-musl` gem.

**Comment by ball-hayden** [comment]
Could I please add a request that `-linux-musl` be published.
Using Alpine as a base image is reasonably common (Alpine using MUSL rather than GNU).

**Comment by JasonLunn** [comment]
Please try out the latest release, 4.31.0-rc1, and confirm that it has resolved this issue for you, @ntkme. The [release](https://rubygems.org/gems/google-protobuf/versions) includes binary packages for `-gnu` and `-musl`.

**Comment by henrahmagix** [comment]
@JasonLunn could we kindly get a v3.x.x release of the separate `-musl` binary if possible please, when it's out of release-candidate? Thanks in advance! 🤞

**Comment by ntkme** [comment]
@henrahmagix Unfortunately, based on previous discussions in this thread back-porting is probably not going to happen, because they cannot drop support of ruby `<= 3.0` in a patch release.
