### ISSUE TITLE
error: call to undeclared function '_upb_MiniTable_GetSubByIndex'; ISO C99 and later do not support implicit function declarations 

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/protobuf#17273]
**What version of protobuf and what language are you using?**

today main branch: https://github.com/protocolbuffers/protobuf/commit/de29e3c9aeff8b85913f6bd1a2395e303f932ab4

`_upb_MiniTable_GetSubByIndex` is not exists from source code(grep search not find), but still call from https://github.com/protocolbuffers/protobuf/blob/main/upb/wire/internal/decode_fast.c#L918

**Comment by calvin2021y** [comment]
_upb_MiniTable_GetSubByIndex => _upb_MiniTable_GetSubTableByIndex

**Comment by calvin2021y** [comment]
after _upb_MiniTable_GetSubByIndex => _upb_MiniTable_GetSubTableByIndex:

 error: passing 'const struct upb_MiniTable' to parameter of incompatible type 'union upb_MiniTableSub'

**Comment by calvin2021y** [comment]
https://github.com/protocolbuffers/protobuf/commit/85c7cc24e0084a3beda37b848e7037f8f09c6850

@haberman

**Comment by calvin2021y** [comment]
hi @haberman @zhangskz 

Today I try master branch b1c0715, still get this error.

Any comment how to fix this ?

**Comment by haberman** [comment]
How are you building protobuf?

The `decode_fast.c` file is not enabled in any of our normal builds (Bazel, CMake, etc). Are you using a custom build setup?

**Comment by calvin2021y** [comment]
I use bazel:

```sh
bazel build //upb:gen_amalgamation
clang bazel-bin/upb/upb.c bazel-bin/upb/upb.h -DUPB_FASTTABLE_ENABLED -DUPB_ENABLE_FASTTABLE -c
```

The `upb_MiniTable` from `.upb_minitable.c` still has the fast field,  that is why I 

decode_fast/encode_fast will be removed ?  or temporarily unavailable?

**Comment by haberman** [comment]
> decode_fast/encode_fast will be removed ? or temporarily unavailable?

decode_fast is currently unmaintained. If and when there is a use case that needs the extra parsing speed (and can tolerate the larger code size), we may bring it back.

**Comment by calvin2021y** [comment]
Thanks for explain.

After I disable `FASTTABLE`,  get this error:

```sh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
tests_pbgen_plugin.exe: ~/src/upb/upb.c:7437: upb_Message *_upb_Decoder_NewSubMessage2(upb_Decoder *, const upb_MiniTable *, const upb_MiniTableField *, upb_TaggedMessagePtr *): Assertion `subl' failed.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7d75e8f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7d26fb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7d11472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7d11395 in __assert_fail_base (fmt=0x7ffff7e85a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555555afd0e <.L.str.397> "subl", file=file@entry=0x5555555aeada <.L.str.93> "~/src/upb/upb.c", line=line@entry=7437, function=function@entry=0x5555555ad3d3 <.L__PRETTY_FUNCTION__._upb_Decoder_NewSubMessage2> "upb_Message *_upb_Decoder_NewSubMessage2(upb_Decoder *, const upb_MiniTable *, const upb_MiniTableField *, upb_TaggedMessagePtr *)") at ./assert/assert.c:92
#5  0x00007ffff7d1feb2 in __GI___assert_fail (assertion=0x5555555afd0e <.L.str.397> "subl", file=0x5555555aeada <.L.str.93> "~/src/upb/upb.c", line=7437, function=0x5555555ad3d3 <.L__PRETTY_FUNCTION__._upb_Decoder_NewSubMessage2> "upb_Message *_upb_Decoder_NewSubMessage2(upb_Decoder *, const upb_MiniTable *, const upb_MiniTableField *, upb_TaggedMessagePtr *)") at ./assert/assert.c:101
#6  0x000055555564d824 in _upb_Decoder_NewSubMessage2 (d=0x7fffffffd298, subl=0x0, field=0x555555584360 <google.protobuf.compiler.plugin.CodeGeneratorRequest__fields+24>, target=0x555555659848) at ~/src/upb/upb.c:7437
#7  0x000055555564d31e in _upb_Decoder_NewSubMessage (d=0x7fffffffd298, subs=0x5555556555c8 <google.protobuf.compiler.plugin.CodeGeneratorRequest_submsgs>, field=0x555555584360 <google.protobuf.compiler.plugin.CodeGeneratorRequest__fields+24>, target=0x555555659848) at ~/src/upb/upb.c:7461
#8  0x000055555564cc6b in _upb_Decoder_DecodeToSubMessage (d=0x7fffffffd298, ptr=0x55555558920a "\b\005\020\034\030", msg=0x555555659820, subs=0x5555556555c8 <google.protobuf.compiler.plugin.CodeGeneratorRequest_submsgs>, field=0x555555584360 <google.protobuf.compiler.plugin.CodeGeneratorRequest__fields+24>, val=0x7fffffffd168, op=6) at ~/src/upb/upb.c:7916
#9  0x00005555556325cb in _upb_Decoder_DecodeKnownField (d=0x7fffffffd298, ptr=0x55555558920a "\b\005\020\034\030", msg=0x555555659820, layout=0x5555556555e0 <google__protobuf__compiler__CodeGeneratorRequest_msg_init>, field=0x555555584360 <google.protobuf.compiler.plugin.CodeGeneratorRequest__fields+24>, op=6, val=0x7fffffffd168) at ~/src/upb/upb.c:8387
#10 _upb_Decoder_DecodeMessage (d=0x7fffffffd298, ptr=0x55555558920a "\b\005\020\034\030", msg=0x555555659820, layout=0x5555556555e0 <google__protobuf__compiler__CodeGeneratorRequest_msg_init>) at ~/src/upb/upb.c:8506
#11 0x000055555564e504 in _upb_Decoder_DecodeTop (d=0x7fffffffd298, buf=0x5555555891c0 "\n\016api/auth.proto\n\020api/option.proto\n\023errorx/errors.proto\022\017error,prefix=v1\032\f\b\005\020\034\030", msg=0x555555659820, m=0x5555556555e0 <google__protobuf__compiler__CodeGeneratorRequest_msg_init>) at ~/src/upb/upb.c:8539
#12 0x000055555563279a in upb_Decoder_Decode (decoder=0x7fffffffd298, buf=0x5555555891c0 "\n\016api/auth.proto\n\020api/option.proto\n\023errorx/errors.proto\022\017error,prefix=v1\032\f\b\005\020\034\030", msg=0x555555659820, m=0x5555556555e0 <google__protobuf__compiler__CodeGeneratorRequest_msg_init>, arena=0x555555659920) at ~/src/upb/upb.c:8559
#13 0x0000555555609dbd in upb_Decode (buf=0x5555555891c0 "\n\016api/auth.proto\n\020api/option.proto\n\023errorx/errors.proto\022\017error,prefix=v1\032\f\b\005\020\034\030", size=109567, msg=0x555555659820, mt=0x5555556555e0 <google__protobuf__compiler__CodeGeneratorRequest_msg_init>, extreg=0x555555658e28, options=1, arena=0x555555659920) at ~/src/upb/upb.c:8595
```

error from : `UPB_ASSERT(subl);`

```c
static upb_Message* _upb_Decoder_NewSubMessage2(upb_Decoder* d,
                                                const upb_MiniTable* subl,
                                                const upb_MiniTableField* field,
                                                upb_TaggedMessagePtr* target) {
  UPB_ASSERT(subl);
  upb_Message* msg = _upb_Message_New(subl, &d->arena);
  if (!msg) _upb_Decoder_ErrorJmp(d, kUpb_DecodeStatus_OutOfMemory);

  // Extensions should not be unlinked. A message extension should not be
  // registered until its sub-message type is available to be linked.
  bool is_empty = UPB_PRIVATE(_upb_MiniTable_IsEmpty)(subl);
  bool is_extension = field->UPB_PRIVATE(mode) & kUpb_LabelFlags_IsExtension;
  UPB_ASSERT(!(is_empty && is_extension));

  if (is_empty && !(d->options & kUpb_DecodeOption_ExperimentalAllowUnlinked)) {
    _upb_Decoder_ErrorJmp(d, kUpb_DecodeStatus_UnlinkedSubMessage);
  }

  upb_TaggedMessagePtr tagged =
      UPB_PRIVATE(_upb_TaggedMessagePtr_Pack)(msg, is_empty);
  memcpy(target, &tagged, sizeof(tagged));
  return msg;
}

static upb_Message* _upb_Decoder_NewSubMessage(
    upb_Decoder* d, const upb_MiniTableSubInternal* subs,
    const upb_MiniTableField* field, upb_TaggedMessagePtr* target) {
  const upb_MiniTable* subl = _upb_MiniTableSubs_MessageByField(subs, field);
  return _upb_Decoder_NewSubMessage2(d, subl, field, target);
}

```

the last call to _upb_Decoder_DecodeKnownField, layout->full_name is `google.protobuf.compiler.CodeGeneratorRequest`

**Comment by calvin2021y** [comment]
try add some printf to find why:

```c
UPB_FORCEINLINE
const char* _upb_Decoder_DecodeKnownField(upb_Decoder* d, const char* ptr,
                                          upb_Message* msg,
                                          const upb_MiniTable* layout,
                                          const upb_MiniTableField* field,
                                          int op, wireval* val) {
  const upb_MiniTableSubInternal* subs = layout->UPB_PRIVATE(subs);
  uint8_t mode = field->UPB_PRIVATE(mode);
  upb_MiniTableSubInternal ext_sub;

  if (UPB_UNLIKELY(mode & kUpb_LabelFlags_IsExtension)) {
    const upb_MiniTableExtension* ext_layout =
        (const upb_MiniTableExtension*)field;
    upb_Extension* ext = UPB_PRIVATE(_upb_Message_GetOrCreateExtension)(
        msg, ext_layout, &d->arena);
    if (UPB_UNLIKELY(!ext)) {
      _upb_Decoder_ErrorJmp(d, kUpb_DecodeStatus_OutOfMemory);
    }
    d->unknown_msg = msg;
    msg = (upb_Message*)&ext->data;
    if (upb_MiniTableField_IsSubMessage(&ext->ext->UPB_PRIVATE(field))) {
      ext_sub.UPB_PRIVATE(submsg) =
          &ext->ext->UPB_PRIVATE(sub).UPB_PRIVATE(submsg);
    } else {
      ext_sub.UPB_PRIVATE(subenum) =
          ext->ext->UPB_PRIVATE(sub).UPB_PRIVATE(subenum);
    }
    subs = &ext_sub;
  }

  switch (mode & kUpb_FieldMode_Mask) {
    case kUpb_FieldMode_Array:
      return _upb_Decoder_DecodeToArray(d, ptr, msg, subs, field, val, op);
    case kUpb_FieldMode_Map:
      return _upb_Decoder_DecodeToMap(d, ptr, msg, subs, field, val);
    case kUpb_FieldMode_Scalar:
      printf("[%d] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar %p, field=%p %s , field=%p field=%ld\n", __LINE__, layout, layout->fields, layout->full_name, field, (field - layout->fields));
      return _upb_Decoder_DecodeToSubMessage(d, ptr, msg, subs, field, val, op);
    default:
      UPB_UNREACHABLE();
  }
}
```

```sh
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8e70 field=0
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8e7c field=1
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8e88 field=2
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8e94 field=3
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8ea0 field=4
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x555555657200, field=0x5555555a8e70 google.protobuf.FeatureSet , field=0x5555555a8eac field=5
[7291] _upb_MiniTableSubs_MessageByField submsg_index=1
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x5555556573e0, field=0x5555555a8ef0 google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault , field=0x5555555a8f08 field=2
[7918] _upb_Decoder_DecodeToSubMessage subs=0x5555556576e0
[7461]_upb_Decoder_NewSubMessage=0x5555556576e0
[7291] _upb_MiniTableSubs_MessageByField submsg_index=1
[7291] _upb_MiniTableSubs_MessageByField submsg_index=1
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x5555556573c0, field=0x5555555a8ec0 google.protobuf.FeatureSetDefaults , field=0x5555555a8ecc field=1
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x5555556573c0, field=0x5555555a8ec0 google.protobuf.FeatureSetDefaults , field=0x5555555a8ed8 field=2
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x5555556565f8, field=0x555555584ac0 google.protobuf.compiler.CodeGeneratorRequest , field=0x555555584acc field=1
[7291] _upb_MiniTableSubs_MessageByField submsg_index=0
[8390] _upb_Decoder_DecodeKnownField kUpb_FieldMode_Scalar 0x5555556565f8, field=0x555555584ac0 google.protobuf.compiler.CodeGeneratorRequest , field=0x555555584ad8 field=2
[7918] _upb_Decoder_DecodeToSubMessage subs=0x5555556565e0
[7461]_upb_Decoder_NewSubMessage=0x5555556565e0
[7291] _upb_MiniTableSubs_MessageByField submsg_index=0
```
