### ISSUE TITLE
[Bazel CI] bazel: artifact upload failed: file not found


### ISSUE THREAD

**Issue by sgowroji** [protocolbuffers/protobuf#17375]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3975#019095c1-0534-422c-a3cf-b6567e0540fb

 Platform: MacOS

 Logs: 
```
Traceback (most recent call last):
  File "/Users/buildkite/builds/bk-macos-pln3-xttt/bazel/bazel-at-head-plus-downstream/bazelci.py", line 4520, in <module>
    sys.exit(main())
  File "/Users/buildkite/builds/bk-macos-pln3-xttt/bazel/bazel-at-head-plus-downstream/bazelci.py", line 4488, in main
    execute_commands(
  File "/Users/buildkite/builds/bk-macos-pln3-xttt/bazel/bazel-at-head-plus-downstream/bazelci.py", line 1466, in execute_commands
    _ = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/buildkite/builds/bk-macos-pln3-xttt/bazel/bazel-at-head-plus-downstream/bazelci.py", line 2694, in upload_test_logs_from_bep
    execute_command(
  File "/Users/buildkite/builds/bk-macos-pln3-xttt/bazel/bazel-at-head-plus-downstream/bazelci.py", line 2757, in execute_command
    return subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp4aaff9gf/bazelci-agent', 'artifact', 'upload', '--debug', '--delay=5', '--mode=buildkite', '--build_event_json_file=/tmp/tmp4aaff9gf/test_bep.json']' returned non-zero exit status 1.
``` 
 
 CC Greenteam @comius

**Comment by sgowroji** [comment]
CC @meteorcloudy

**Comment by meteorcloudy** [comment]
This is a Bazel CI issue, not a protobuf issue, please close.
