### ISSUE TITLE
[Bazel CI] Error in resolve_tools: Pass an executable or tools argument to ctx.actions.run 


### ISSUE THREAD

**Issue by sgowroji** [protocolbuffers/protobuf#18328]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4128#0191f902-9764-49ee-9ba8-fad90dce3287

Platform: MacOS

Logs:

```
 ERROR: /Users/buildkite/builds/bk-macos-pln3-g50m/bazel-org-repo-root/protobuf/java/kotlin/BUILD.bazel:31:15: in kt_jvm_library rule //java/kotlin:only_for_use_in_proto_generated_code_its_generator_and_tests:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/aa3bb90c38b0f4c47984e8f6f52da588/external/rules_kotlin/kotlin/internal/jvm/impl.bzl", line 222, column 36, in kt_jvm_library_impl
		_kt_jvm_produce_jar_actions(ctx, "kt_jvm_library") if ctx.attr.srcs or ctx.attr.resources else export_only_providers(
	File "/private/var/tmp/_bazel_buildkite/aa3bb90c38b0f4c47984e8f6f52da588/external/rules_kotlin/kotlin/internal/jvm/compile.bzl", line 549, column 50, in kt_jvm_produce_jar_actions
		outputs_struct = _run_kt_java_builder_actions(
	File "/private/var/tmp/_bazel_buildkite/aa3bb90c38b0f4c47984e8f6f52da588/external/rules_kotlin/kotlin/internal/jvm/compile.bzl", line 729, column 31, in _run_kt_java_builder_actions
		_run_kt_builder_action(
	File "/private/var/tmp/_bazel_buildkite/aa3bb90c38b0f4c47984e8f6f52da588/external/rules_kotlin/kotlin/internal/jvm/compile.bzl", line 485, column 47, in _run_kt_builder_action
		tools, input_manifests = ctx.resolve_tools(
Error in resolve_tools: Pass an executable or tools argument to ctx.actions.run or ctx.actions.run_shell instead of calling ctx.resolve_tools.
Use --noincompatible_disallow_ctx_resolve_tools to temporarily disable this check.
(06:08:51) ERROR: /Users/buildkite/builds/bk-macos-pln3-g50m/bazel-org-repo-root/protobuf/java/kotlin/BUILD.bazel:31:15: Analysis of target '//java/kotlin:only_for_use_in_proto_generated_code_its_generator_and_tests' failed
Target //java/internal:java_version failed to build
(06:08:51) ERROR: Analysis of target '//java/kotlin:test_extensions' failed; build aborted: Analysis failed
(06:08:51) INFO: Elapsed time: 47.438s, Critical Path: 0.07s
(06:08:51) INFO: 1 process: 1 internal.
(06:08:51) ERROR: Build did NOT complete successfully
```

Culprit:

Steps:

```
 git clone https://github.com/google/protobuf
git reset 372ddb308be33fed837043a2446f7b2305dcb075  --hard
export USE_BAZEL_VERSION=7b8d07253adf84d5e3d46ac915a1440e518fab3c
bazel test //:all //java/... 
```

CC Greenteam @comius

**Comment by tjgq** [comment]
This has been fixed in rules_kotlin at head (the commit that fixed it was https://github.com/bazelbuild/rules_kotlin/commit/d5b03084392ba6e0c54391942ed1780543623920).

**Comment by sgowroji** [comment]
@haberman @mkruskal-google Could you please take a look at this [comment](https://github.com/protocolbuffers/protobuf/issues/18328#issuecomment-2355105043). Thanks!
