### ISSUE TITLE
java.lang.NoClassDefFoundError in Kotlin

### ISSUE THREAD

**Issue by GaatouCan** [protocolbuffers/protobuf#18533]
**What version of protobuf and what language are you using?**
Version: 4.28.2
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
Windows 11 x64

**What runtime / compiler are you using (e.g., python version or gcc version)**
liberica jdk 21.0.4+9-LTS

**What did you do?**
I am wanna use Protobuf in my Kotlin Client/Server project, as TCP/IP protocol.
The following is .proto file define
```proto
syntax = "proto3";

package proto.gen;

message GreetingRequest {
  string message = 1;
}

message GreetingResponse {
  string message = 1;
}
```

And the following is client code, the client code is not the focus, the focus is on the main function
```kotlin
package client

import base.VagrantCodec
import io.netty.bootstrap.Bootstrap
import io.netty.channel.ChannelFuture
import io.netty.channel.ChannelFutureListener
import io.netty.channel.ChannelInitializer
import io.netty.channel.ChannelOption
import io.netty.channel.nio.NioEventLoopGroup
import io.netty.channel.socket.nio.NioSocketChannel
import org.apache.logging.log4j.LogManager
import proto.gen.Greeting


class VagrantClient(val host: String, val port: Int) {
    fun start() {
        val worker = NioEventLoopGroup()

        try {
            val bootstrap = Bootstrap()
            bootstrap.group(worker).channel(NioSocketChannel::class.java)
                .remoteAddress(host, port)
                .option(ChannelOption.SO_KEEPALIVE, true)
                .option(ChannelOption.SO_REUSEADDR, true)
                .option(ChannelOption.TCP_NODELAY, true)
                .handler(object : ChannelInitializer<NioSocketChannel>() {
                    override fun initChannel(ch: NioSocketChannel) {
                        ch.pipeline()
                            .addLast(VagrantCodec())
                            .addLast(EchoClientHandler())
                    }
                })

            val future = bootstrap.connect().sync()

            future.addListener(object : ChannelFutureListener {

                @Throws(Exception::class)
                override fun operationComplete(future: ChannelFuture) {
                    if (future.isSuccess) {
//                        var req = CS_Greeting_Request.newBuilder()
//                        req.setMessage("Greeting From Client")
//                        var pkg = Package(1001, req.build().toByteArray())
//
//                        pkg.magic = PACKAGE_CLIENT_MAGIC_NUMBER
//                        future.channel().writeAndFlush(pkg).sync()
                    }
                }
            })

            future.channel().closeFuture().sync()
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            worker.shutdownGracefully().sync()
        }
    }

    companion object {

        val logger = LogManager.getLogger(VagrantClient::class.java)

        @Throws(Exception::class)
        @JvmStatic
        fun main(args: Array<String>) {
//            val host = args.getOrElse(0) { "localhost" }
//            val port = args.getOrElse(1) { "8080" }.toInt()
//            VagrantClient(host, port).start()
            val req = Greeting
                .GreetingRequest
                .newBuilder()
                .setMessage("Hello World")
                .build()
            println(req.message)
        }
    }
}
```
I have to say the IDEA tell me that I have imported the proto generated code and classes correctly, and and passed the compilation

The following is the gradle.build.kts file
```
plugins {
    kotlin("jvm") version "2.0.20"
    id("com.google.protobuf") version "0.9.4"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
    implementation(kotlin("reflect"))

    // https://mvnrepository.com/artifact/io.netty/netty-all
    implementation("io.netty:netty-all:4.1.113.Final")

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    implementation("org.apache.logging.log4j:log4j-core:2.24.0")

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation("org.apache.logging.log4j:log4j-api:2.24.0")

    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
    implementation("com.google.protobuf:protobuf-java:4.28.2")

    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util
    implementation("com.google.protobuf:protobuf-java-util:4.28.2")

    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-kotlin
    implementation("com.google.protobuf:protobuf-kotlin:4.28.2")
}

tasks.test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}
```
**What did you expect to see**
Maybe "Hello, woerld"

**What did you see instead?**
```
Exception in thread "main" java.lang.NoClassDefFoundError: proto/gen/Greeting$GreetingRequest
	at client.VagrantClient$Companion.main(VagrantClient.kt:71)
	at client.VagrantClient.main(VagrantClient.kt)
Caused by: java.lang.ClassNotFoundException: proto.gen.Greeting$GreetingRequest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 2 more
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I am use .bat to generate proto code, and I sure that use the same version protoc.exe and command is correctly both --java_out and  --kotlin_out

**Comment by JasonLunn** [comment]
This looks like a classpath issue. How are you informing gradle of where to look to find the generated classes?

**Comment by GaatouCan** [comment]
Sorry I'm a newbie in gradle and don't know much about found generated classes. The following is the project tree
![6c5339ed-9a98-4cf4-b3e0-78339caa60b8](https://github.com/user-attachments/assets/25595840-89a3-43b0-b7a7-3dcf5ea6ed40)
Maybe I can show you something else

**Comment by JasonLunn** [comment]
For networking applications of Protobuf Kotlin, I recommend that you check out https://github.com/grpc/grpc-kotlin/blob/master/examples/README.md

**Comment by GaatouCan** [comment]
Okay, I will check the doc and try it again, thx for your patient.
