### ISSUE TITLE
Python `SyntaxError` in `google/protobuf/service.py` in `5.29.0`

### ISSUE THREAD

**Issue by Avasam** [protocolbuffers/protobuf#19452]
**What version of protobuf and what language are you using?**
Version: 5.29.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.11.10

**What did you do?**
1. `python -m pip install protobuf==5.29`
2. `python -c 'import google.protobuf.service'`

**What did you expect to see**
Nothing / No error

**What did you see instead?**
```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Users\Avasam\Documents\Git\typeshed\.venv\Lib\site-packages\google\protobuf\service.py", line 78
    raise NotImplementedError
                             ^
IndentationError: unindent does not match any outer indentation level
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by Avasam** [comment]
I searched for `SyntaxError` but didn't find anything. But this issue already exists, oops! https://github.com/protocolbuffers/protobuf/issues/19430
