### ISSUE TITLE
[Ruby] google/protobuf/well_known_types is not included automatically

### ISSUE THREAD

**Issue by FX-HAO** [protocolbuffers/protobuf#3807]
```ruby
irb> Google::Protobuf::Struct.from_hash({})
NoMethodError: undefined method `from_hash' for Google::Protobuf::Struct:Class
	from /Users/haofuxin/shundaojia/shundao-backend/app/publishers/publisher/payment.rb:24:in `publish'
	from /Users/haofuxin/shundaojia/shundao-backend/app/services/payment_service.rb:11:in `publish_event'
	from (irb):3
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Users/haofuxin/shundaojia/shundao-backend/bin/rails:9:in `<top (required)>'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/haofuxin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

irb> require 'google/protobuf/well_known_types'
=> true
irb> Google::Protobuf::Struct.from_hash({})
=> <Google::Protobuf::Struct: fields: {}>
```

And need more documentation or where can i find it?

**Comment by haberman** [comment]
I'm not sure I understand the question. The `well_known_types` header is not included automatically, you have to include it yourself. When you include it, the `Google::Protobuf::Struct.from_hash` method is available.
