### ISSUE TITLE
[PHP] mergeFromJsonString can not unserialize maps with numeric keys

### ISSUE THREAD

**Issue by arnaud-lb** [protocolbuffers/protobuf#4765]
With the following proto:

``` proto
syntax = "proto3";

package test;

message Hello {
    map<string, string> m = 1;
};
```

The PHP implementation of protobuf has troubles decoding the following JSON message:

```
{"m":{"foo":"bar","123":"42"}}
```

The error is:

```
PHP Fatal error:  Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: String field only accepts string value in php/src/Google/Protobuf/Internal/Message.php:836
Stack trace:
#0 php/src/Google/Protobuf/Internal/Message.php(1116): Google\Protobuf\Internal\Message->convertJsonValueToProtoValue(123, Object(Google\Protobuf\Internal\FieldDescriptor), true)
#1 php/src/Google/Protobuf/Internal/Message.php(1086): Google\Protobuf\Internal\Message->mergeFromArrayJsonImpl(Array)
#2 php/src/Google/Protobuf/Internal/Message.php(1168): Google\Protobuf\Internal\Message->mergeFromJsonArray(Array)
#3 php/src/Google/Protobuf/Internal/Message.php(742): Google\Protobuf\Internal\Message->parseFromJsonStream(Object(Google\Protobuf\Internal\RawInputStream))
#4 bug/test.php(17): Google\Protobuf\Internal\Message->mergeFromJsonString('{"m":{"foo":"ba...')
#5 {main}
  thrown in php/src/Google/Protobuf/Internal/Message.php on line 836
```

The cause is that we decode the [JSON as array](https://github.com/google/protobuf/blob/f1911f37f817fb2dddbb07478bdcda526488fc55/php/src/Google/Protobuf/Internal/Message.php#L1159) before parsing it, and that PHP arrays always store numeric keys as integers, and everything else as strings. So, json decoding `{"123":"42"}` results in `[123 => "42"]` rather than `["123" => "42"]` (which is impossible in PHP).

**Comment by arnaud-lb** [comment]
Exactly, however json_decode() casts numeric keys back to int

**Comment by TeBoring** [comment]
I'll fix it.

**Comment by arnaud-lb** [comment]
Thanks ! I confirm that the issue is fixed.
