### ISSUE TITLE
[Java] got outofmemory when deserializing a large object

### ISSUE THREAD

**Issue by imsuperman0920** [protocolbuffers/protobuf#4858]
Hi all
I created a proto as below:

```
syntax = "proto3";
option java_package = "cn.com.cennavi.oem.common";
option java_outer_classname = "RInfoPB";

message RInfo {
    string dataVersion = 1;
    map<string, MapValue> map = 2;
}

message MapValue {
	map<string, string> map = 1;
}
```

I put data (240mb) in the pb object and serialized the object to a local file (590mb).
**The size doubled. Why it happened?**

Next, I convertered the local file to pb object, the Xms and Xmx both are 5g.
Finally, I got a outofmemory exception.

Is there something wrong with the usage ?

 BTW: the version of protobuf.jar is 3.6.0

Please help ~

**Comment by xfxyjwf** [comment]
Protobuf will add tag prefixes to data fields so the serialized data will be a bit larger. If your data fields are generally small (e.g., many string fields with 1 character), the data prefixes can be a significant part of the serialized bytes.

I don't know what it OOM though. It looks like you only have string fields and the memory used shouldn't be bloated too much. Also if you can serialize the data, I don't see why it can't parse it back. Are you keeping many proto objects at the same time?

**Comment by imsuperman0920** [comment]
@xfxyjwf Thank you for your message.
In the object, all fields (including map's key and value) are string and some values in the map may be little big (some coordinate sequence). Dose it affect the data parsing ?
I just deal single proto object when I parse it back~

**Comment by imsuperman0920** [comment]
_[root@localhost test]# java -Xms5g -Xmx5g -jar ProtobufTester.jar /APP/midmif/out_bak/Rbeijing_dir322.rinf_
```

解压缩完成, 耗时 [488] ms, 大小 [621043338] ~
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:845)
	at com.google.protobuf.WireFormat$Utf8Validation$2.readString(WireFormat.java:196)
	at com.google.protobuf.WireFormat.readPrimitiveField(WireFormat.java:245)
	at com.google.protobuf.FieldSet.readPrimitiveField(FieldSet.java:581)
	at com.google.protobuf.MapEntryLite.parseField(MapEntryLite.java:135)
	at com.google.protobuf.MapEntryLite.parseEntry(MapEntryLite.java:182)
	at com.google.protobuf.MapEntry.<init>(MapEntry.java:106)
	at com.google.protobuf.MapEntry.<init>(MapEntry.java:50)
	at com.google.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:70)
	at com.google.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:64)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
	at cn.com.cennavi.oem.common.RInfoPB$RInfo.<init>(RInfoPB.java:142)
	at cn.com.cennavi.oem.common.RInfoPB$RInfo.<init>(RInfoPB.java:109)
	at cn.com.cennavi.oem.common.RInfoPB$RInfo$1.parsePartialFrom(RInfoPB.java:906)
	at cn.com.cennavi.oem.common.RInfoPB$RInfo$1.parsePartialFrom(RInfoPB.java:1)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at cn.com.cennavi.oem.common.RInfoPB$RInfo.parseFrom(RInfoPB.java:414)
	at cn.com.cennavi.Toolkit.protobuf.Deserialize.main(Deserialize.java:18)
```

**Comment by xfxyjwf** [comment]
What's the memory usage when you serialize the proto object?

**Comment by panchenko** [comment]
I guess initial data structure reuses some string instances, so it's not that big in memory. When reading it from file an unique copy of each string is created and that uses much more memory.

**Comment by dankurka** [comment]
Looking at this without the data my best guess would be that strings are not interned and thus we see a lot of extra instances.

Can you provide a small repro case for this so that we can take a look at the heap?

**Comment by elharo** [comment]
can't reproduce; comment and reopen if more data is forthcoming
