### ISSUE TITLE
Error from google protobuf gem while running rake for installing grpc ruby gem 

### ISSUE THREAD

**Issue by rohitsakala** [protocolbuffers/protobuf#4893]
**What version of protobuf and what language are you using?**
Version: 3.6.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Linux - SUSE, s390x architecture

**What runtime / compiler are you using (e.g., python version or gcc version)**
Using rake to install grpc from source code.

**What did you do?**
1. git clone https://github.com/grpc/grpc.git
2. cd grpc/src/ruby
3. git submodule update --init
4. gem install bundle
5. bundle install
6. rake

**What did you expect to see**
Successful completion of command rake

**What did you see instead?**
```Running RuboCop...
Inspecting 63 files
...............................................................

63 files inspected, no offenses detected
/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb
/grpc/src/ruby/spec/channel_credentials_spec.rb:19: warning: already initialized constant CallCredentials
/grpc/src/ruby/spec/call_credentials_spec.rb:18: warning: previous definition of CallCredentials was here

An error occurred while loading ./src/ruby/spec/google_rpc_status_utils_spec.rb.
Failure/Error: Any = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.Any").msgclass

NoMethodError:
  undefined method `msgclass' for nil:NilClass
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:15:in `<module:Protobuf>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:14:in `<module:Google>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:13:in `<top (required)>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/googleapis-common-protos-types-1.0.1/lib/google/rpc/status_pb.rb:6:in `require'
# /usr/local/rvm/gems/ruby-2.3.1/gems/googleapis-common-protos-types-1.0.1/lib/google/rpc/status_pb.rb:6:in `<top (required)>'
# ./src/ruby/lib/grpc/google_rpc_status_utils.rb:16:in `require'
# ./src/ruby/lib/grpc/google_rpc_status_utils.rb:16:in `<top (required)>'
# ./src/ruby/spec/google_rpc_status_utils_spec.rb:16:in `require_relative'
# ./src/ruby/spec/google_rpc_status_utils_spec.rb:16:in `<top (required)>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1954:in `load'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1954:in `load_spec_file_handling_errors'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1496:in `block in load_spec_files'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `each'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `load_spec_files'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:100:in `setup'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'

Finished in 0.00014 seconds (files took 0.23957 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Coverage report generated for wrapper to /grpc/coverage. 334 / 1011 LOC (33.04%) covered.
/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb failed
```

**Comment by xfxyjwf** [comment]
Have you created an issue against grpc? This seems more like a grpc issue to me.

**Comment by rohitsakala** [comment]
Hi @xfxyjwf ,

Thanks for the reply. I created an issue in grpc. [Link](https://github.com/grpc/grpc/issues/15996).
