### ISSUE TITLE
Issue converting message to Json in Java/Python

### ISSUE THREAD

**Issue by Siddharthk** [protocolbuffers/protobuf#5151]
While using JsonFormat for converting message into JSON format, I am getting below error:

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/google.protobuf.StringValue
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:730)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$900(JsonFormat.java:568)
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:632)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:611)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)

Is this a bug? I have verified this both in Python and Java. Seems like its not able to find Any packing of StringValue.

Thanks,
Sid

**Comment by Siddharthk** [comment]
@xfxyjwf  Can you please help me out on this. Below is the snippet which is causing issue in jsonformat.java

/** Prints google.protobuf.Any */
    private void printAny(MessageOrBuilder message) throws IOException {
      if (Any.getDefaultInstance().equals(message)) {
        generator.print("{}");
        return;
      }
      Descriptor descriptor = message.getDescriptorForType();
      FieldDescriptor typeUrlField = descriptor.findFieldByName("type_url");
      FieldDescriptor valueField = descriptor.findFieldByName("value");
      // Validates type of the message. Note that we can't just cast the message
      // to com.google.protobuf.Any because it might be a DynamicMessage.
      if (typeUrlField == null
          || valueField == null
          || typeUrlField.getType() != FieldDescriptor.Type.STRING
          || valueField.getType() != FieldDescriptor.Type.BYTES) {
        throw new InvalidProtocolBufferException("Invalid Any type.");
      }
      String typeUrl = (String) message.getField(typeUrlField);
      String typeName = getTypeName(typeUrl);
      Descriptor type = registry.find(typeName);
      if (type == null) {
        throw new InvalidProtocolBufferException("Cannot find type for url: " + typeUrl);
      }
 
When typeName is google.protobuf.StringValue, the type is getting returned as null and therefore getting below exception:

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/google.protobuf.StringValue
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:765)

**Comment by haon4** [comment]
Can you call [`JsonFormat.usingTypeRegistry()`](https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L158), and make sure that you have all the Descriptors you are expecting to the TypeRegistry.Builder (see https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L479)

**Comment by haon4** [comment]
Please reopen if the above suggestion doesn't work.
