### ISSUE TITLE
ProtoMessage to Json Print resulting in Exception

### ISSUE THREAD

**Issue by Siddharthk** [protocolbuffers/protobuf#5174]
**I am having below proto message:**
message tempResponse {
  map<string, google.protobuf.Any> temp_response = 1;
}

**Below is the java code:**
import com.google.protobuf.StringValue;
import com.google.protobuf.Any;
import com.google.protobuf.util.JsonFormat;

private static JsonFormat.Printer printer = JsonFormat.printer();

StringValue.Builder str = StringValue.newBuilder();
	    str.setValue("sid");
	    Any any = null;
	    any = any.pack(str.build());
	    Map<String, Any> mp = new HashMap<>();
	    mp.put("id", any);
	    tempResponse tr= tempResponse.newBuilder().putAllTempResponse(mp).build();

	    System.out.println(printer.print(tr));

**Output:** 
com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/google.protobuf.StringValue
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:765)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$900(JsonFormat.java:600)
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:667)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:646)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1117)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:982)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printMapFieldValue(JsonFormat.java:972)

**Value of tr is:**

temp_response {
  key: "id"
  value {
    type_url: "type.googleapis.com/google.protobuf.StringValue"
    value: "\n\003sid"
  }
}

**Comment by hackerwins** [comment]
I tried to handle the problem.
```
            JsonFormat.TypeRegistry registry = JsonFormat.TypeRegistry.newBuilder()
                    .add(StringValue.getDescriptor())
                    .build();
            return JsonFormat
                    .printer()
                    .usingTypeRegistry(registry)
                    .omittingInsignificantWhitespace()
                    .print(messageOrBuilder);
```
But I got an another exception.

```
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.shouldDiscardUnknownFieldsProto3()Z
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:438)
	at com.google.protobuf.DynamicMessage$1.parsePartialFrom(DynamicMessage.java:297)
	at com.google.protobuf.DynamicMessage$1.parsePartialFrom(DynamicMessage.java:290)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:105)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:734)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$900(JsonFormat.java:568)
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:632)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:611)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:895)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:895)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:895)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:909)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:893)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:909)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:893)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1082)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:947)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:895)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:873)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:614)
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:263)
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:273)
```

**Comment by BSBandme** [comment]
Using JsonFormat.TypeRegistry should solve the problem for StringValue typeurl not found.

@hackerwins Tried to update your library to newest version.
