### ISSUE TITLE
JsonFormat parse failed when input includes space

### ISSUE THREAD

**Issue by thinkerou** [protocolbuffers/protobuf#5197]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
```
➜  karate-grpc-demo git:(master) ✗ protoc --version
libprotoc 3.5.1
```
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
```
Java
protobuf-maven-plugin
```

**What operating system (Linux, Windows, ...) and version?**
```
Mac
```

**What runtime / compiler are you using (e.g., python version or gcc version)**
```
➜  karate-grpc git:(master) ✗ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**What did you do?**
I define the following proto:
```
message AgainHelloRequest {
  string message = 1;
  string address = 2;
}
```

And my json file like:
```
[
  {
    "message": "Hello thinkerou",
    "address": "BeiJing"
  }
]
```

And my code like:
```java
    public String againGreet(String payload) {
        Gson gson = new Gson();
        List<Map<String, Object>> list = gson.fromJson(payload, List.class);
        System.out.println(list.get(0)); // print1

        AgainHelloRequest.Builder requestBuilder = AgainHelloRequest.newBuilder();
        try {
            JsonFormat.parser().merge(list.get(0).toString(), requestBuilder);
        } catch (InvalidProtocolBufferException e) {
            logger.log(Level.WARNING, "JsonFormat parse failed: {}", e);
        }
       // ...
    }
```
1. read json file
2. call againGreet using read json result

**What did you expect to see**
```
No exception
```

**What did you see instead?**
I found some exception, like:
```
15:20:28.042 [main] INFO  com.intuit.karate - [print] [
  {
    "message": "Hello thinkerou",
    "address": "BeiJing"
  }
]

{message=Hello thinkerou, address=BeiJing}
Sep 28, 2018 3:20:28 PM com.github.thinkerou.demo.helloworld.HelloWorldClient againGreet
警告: JsonFormat parse failed: {}
com.google.protobuf.InvalidProtocolBufferException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 17 path $.message
        at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1195)
        at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:370)
        at com.github.thinkerou.demo.helloworld.HelloWorldClient.againGreet(HelloWorldClient.java:90)
        at jdk.nashorn.internal.scripts.Script$10$\^eval\_.:program(<eval>:1)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at com.intuit.karate.ScriptBindings.eval(ScriptBindings.java:139)
        at com.intuit.karate.ScriptBindings.updateBindingsAndEval(ScriptBindings.java:134)
        at com.intuit.karate.ScriptBindings.evalInNashorn(ScriptBindings.java:119)
        at com.intuit.karate.Script.evalJsExpression(Script.java:371)
        at com.intuit.karate.Script.evalKarateExpression(Script.java:285)
        at com.intuit.karate.Script.evalKarateExpression(Script.java:171)
        at com.intuit.karate.Script.assign(Script.java:601)
        at com.intuit.karate.Script.assign(Script.java:527)
        at com.intuit.karate.StepDefs.def(StepDefs.java:309)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
        at com.intuit.karate.cucumber.CucumberUtils.runStep(CucumberUtils.java:201)
        at com.intuit.karate.cucumber.KarateRuntime.runStep(KarateRuntime.java:86)
        at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
        at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at com.intuit.karate.junit4.Karate.runChild(Karate.java:123)
        at com.intuit.karate.junit4.Karate.runChild(Karate.java:38)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at com.intuit.karate.junit4.Karate.run(Karate.java:131)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```

**Note**: If my input is `Hello` not `Hello thinkerou`(it includes space) it's ok.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by BSBandme** [comment]
I think you can't use toString() of the generated Map from gson as the json string. This will delete \"\" which will make the json string to be invalid.
