### ISSUE TITLE
Assertion failed | Unable to create JS response when nested objects are there

### ISSUE THREAD

**Issue by pallavJha** [protocolbuffers/protobuf#5317]
**Issue**: Object conversion fails when the nested object is not null. For example, when `dog` is null the `CatListResponse` is getting converted successfully while below error results when `dog` is not null.

```
ERROR goog.asserts.AssertionError {message: "Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", stack: "AssertionError: Assertion failed↵
    at new goog.a…ient.js:95:72)↵
    at Array.forEach (<anonymous>)"}message: "Assertion failed"messagePattern: "Assertion failed"reportErrorToServer: truestack: "AssertionError: Assertion failed↵
    at new goog.asserts.AssertionError (webpack-internal:///./node_modules/google-protobuf/google-protobuf.js:98:603)↵
    at Object.goog.asserts.doAssertFailure_ (webpack-internal:///./node_modules/google-protobuf/google-protobuf.js:99:126)↵
    at Object.goog.asserts.assert (webpack-internal:///./node_modules/google-protobuf/google-protobuf.js:99:385)↵
    at jspb.BinaryReader.readBool (webpack-internal:///./node_modules/google-protobuf/google-protobuf.js:356:226)↵
    at proto.project.Project.deserializeBinaryFromReader (webpack-internal:///./src/assets/stubs/project_pb.js:127:50)↵
    at jspb.BinaryReader.readMessage (webpack-internal:///./node_modules/google-protobuf/google-protobuf.js:347:329)↵
    at Function.proto.project.ProjectListResponse.deserializeBinaryFromReader (webpack-internal:///./protobuff/stubs/project_pb.js:656:14)↵
    at Function.proto.project.ProjectListResponse.deserializeBinary (webpack-internal:///./protobuff/stubs/project_pb.js:636:44)↵    at eval (webpack-internal:///./node_modules/grpc-web-client/dist/client.js:95:72)↵ 
    at Array.forEach (<anonymous>)"__proto__: goog.debug.Errorconstructor: ƒ (a,b)name: "AssertionError"__proto__: Errorconstructor: ƒ (a)name: "CustomError"__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()arguments: (...)caller: (...)length: 0name: "toString"__proto__: ƒ ()[[Scopes]]: Scopes[0]__proto__: Object
```
Command for proto generation
```bash
protoc --plugin=protoc-gen-ts=../node_modules/.bin/protoc-gen-ts \
     --ts_out=service=true:./stubs \
     --js_out=import_style=commonjs,binary:./stubs \
      *.proto
```

Go Version:
```go
go version go1.11 linux/amd64
```

Below are the proto files:

```grpc
// cat.proto
syntax = "proto3";
option go_package = "protobuff";
package project;
import "dog.proto";

message Cat{
    string id = 1;
    string name = 2;
    string country = 3;
    string healthFlag = 4;
    dog.Dog dog = 5;
    int64 instanceCount = 6;
}

message CatListResponse {
    repeated Cat cats= 1;
}

// dog.proto
syntax = "proto3";
option go_package = "protobuff";
package tenant;

message Dog{
    string id = 1;
    string name = 2;
    string alias = 3;
}
```

Below is that `go` struct.

```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cat.proto

package protobuff

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cat struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	HealthFlag           string   `protobuf:"bytes,4,opt,name=healthFlag,proto3" json:"healthFlag,omitempty"`
	Dog                  *Dog     `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	InstanceCount        int64    `protobuf:"varint,6,opt,name=instanceCount,proto3" json:"instanceCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cat) Reset()         { *m = Cat{} }
func (m *Cat) String() string { return proto.CompactTextString(m) }
func (*Cat) ProtoMessage()    {}
func (*Cat) Descriptor() ([]byte, []int) {
	return fileDescriptor_cat_4727c80a79f4dc24, []int{0}
}
func (m *Cat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cat.Unmarshal(m, b)
}
func (m *Cat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cat.Marshal(b, m, deterministic)
}
func (dst *Cat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cat.Merge(dst, src)
}
func (m *Cat) XXX_Size() int {
	return xxx_messageInfo_Cat.Size(m)
}
func (m *Cat) XXX_DiscardUnknown() {
	xxx_messageInfo_Cat.DiscardUnknown(m)
}

var xxx_messageInfo_Cat proto.InternalMessageInfo

func (m *Cat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cat) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Cat) GetHealthFlag() string {
	if m != nil {
		return m.HealthFlag
	}
	return ""
}

func (m *Cat) GetDog() *Dog {
	if m != nil {
		return m.Dog
	}
	return nil
}

func (m *Cat) GetInstanceCount() int64 {
	if m != nil {
		return m.InstanceCount
	}
	return 0
}
```

**Comment by pallavJha** [comment]
[Assertion failed | Unable to create JS response when nested objects are there #275
](https://github.com/improbable-eng/grpc-web/issues/275)

**Comment by roball24** [comment]
I'm running into the same issue nesting with `google.protobuf.Any`. Succeeding when the nested object is null, but failing when there is a value.
