### ISSUE TITLE
Javalite branch doesn't build with bazel 0.21.0

### ISSUE THREAD

**Issue by Monnoroch** [protocolbuffers/protobuf#5490]
In my `WORKSPACE` I have:

```
http_archive(
    name = "com_google_protobuf_javalite",
    sha256 = "d8a2fed3708781196f92e1e7e7e713cf66804bd2944894401057214aff4f468e",
    strip_prefix = "protobuf-5e8916e881c573c5d83980197a6f783c132d4276",
    urls = ["https://github.com/google/protobuf/archive/5e8916e881c573c5d83980197a6f783c132d4276.zip"],
)
```

With new Bazel version it fails to build:

```
ERROR: /home/monnoroch/.cache/bazel/_bazel_monnoroch/0a678f6ad8dbaaba9053e7774197befb/external/com_google_protobuf_javalite/BUILD:538:1: Traceback (most recent call last):
	File "/home/monnoroch/.cache/bazel/_bazel_monnoroch/0a678f6ad8dbaaba9053e7774197befb/external/com_google_protobuf_javalite/BUILD", line 538
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/monnoroch/.cache/bazel/_bazel_monnoroch/0a678f6ad8dbaaba9053e7774197befb/external/com_google_protobuf_javalite/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/monnoroch/.cache/bazel/_bazel_monnoroch/0a678f6ad8dbaaba9053e7774197befb/external/com_google_protobuf_javalite/protobuf.bzl", line 266, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
```

The error has been fixed for the master branch, but master branch doesn't support javalite.

Of course I can silence this by setting `--incompatible_package_name_is_a_function=false`, but this will be removed in future versions.

**Comment by acozzette** [comment]
Thanks @Monnoroch, this should be fixed now.
