### ISSUE TITLE
protobuf-3.6.1 doesn't build :protobuf with latest bazel (0.21.0)

### ISSUE THREAD

**Issue by unrstuart** [protocolbuffers/protobuf#5547]
3.6.1 - language agnostic, this is a build error
Linux amd64

Below is the error I see. If I change REPOSITORY_NAME to repository_name(), it then breaks again = )

Specifying the bazel flag allows the build to succeed, but one shouldn't have to do that. bazel build -c opt :protobuf should just work.

```
cpunerd@cpunerd:~/src/protobuf-3.6.1$ bazel build -c opt :protobuf
INFO: Invocation ID: 9f581ef9-5569-4cab-8de7-4e6b98b5b728
ERROR: /usr/local/google/home/cpunerd/src/protobuf-3.6.1/BUILD:573:1: Traceback (most recent call last):
	File "/usr/local/google/home/cpunerd/src/protobuf-3.6.1/BUILD", line 573
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/usr/local/google/home/cpunerd/src/protobuf-3.6.1/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/usr/local/google/home/cpunerd/src/protobuf-3.6.1/protobuf.bzl", line 269, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: error loading package '': Package '' contains errors
INFO: Elapsed time: 0.148s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
cpunerd@cpunerd:~/src/protobuf-3.6.1$ vim protobuf.bzl 
cpunerd@cpunerd:~/src/protobuf-3.6.1$ bazel build -c opt :protobuf
INFO: Invocation ID: 51c58852-f4ed-4078-9dad-83ae1474fabc
ERROR: /usr/local/google/home/cpunerd/src/protobuf-3.6.1/protobuf.bzl:269:39: name 'repository_name' is not defined (did you mean 'REPOSITORY_NAME'?)
ERROR: Skipping ':protobuf': error loading package '': Extension 'protobuf.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': Extension 'protobuf.bzl' has errors
INFO: Elapsed time: 0.168s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
cpunerd@cpunerd:~/src/protobuf-3.6.1$ 
```

**Comment by unrstuart** [comment]
(apologies for the strikethrough, must've been some MD formatting i wasn't aware of)

**Comment by redshirtrob** [comment]
You may want to have a look at #5418 and #5490. Looks like fixes are pending.

**Comment by perezd** [comment]
It seems like maven doesn't have an instance of v3.6.1.3 for protobuf-java that corresponds, can that be addressed? https://search.maven.org/search?q=g:com.google.protobuf

**Comment by perezd** [comment]
With Bazel 0.22 This error is now a major show stopper (unable to compile, full stop error), a corresponding jar distribution would be ideal to coincide with v3.6.1.3 tag.
