### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by harini2191** [protocolbuffers/protobuf#5560]
**What version of protobuf and what language are you using?**
  protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
Language: ANDROID_JAVA

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
ANDROID

**What did you do?**

**What did you expect to see**
Expecting the response after hitting the service but getting error. 

**What did you see instead?**

**ERROR_LOG**:
 W/System.err: java.lang.UnsupportedOperationException
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at io.grpc.examples.helloworld.EchoRequest.dynamicMethod(EchoRequest.java:282)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:336)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:1514)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:258)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:433)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at example.com.grpc_jav_sample.NewSampleActivity.requestExampleService(NewSampleActivity.java:59)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/System.err:     at example.com.grpc_jav_sample.NewSampleActivity.lambda$onCreate$0(NewSampleActivity.java:41)
2019-01-09 15:08:52.483 16339-16339/example.com.grpc_jav_sample W/S

My app.gradle.

apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "example.com.grpc_jav_sample"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.12.0'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            javalite {}
        }
        ofNonTest()*.plugins {
            grpc {
                // Options added to --grpc_out
                option 'lite'
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    // implementation files('libs/protobuf-java-3.6.1.jar')
    //  GRPC dependencies
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'io.grpc:grpc-protobuf-lite:1.14.0'
    implementation 'io.grpc:grpc-okhttp:1.14.0'
    implementation 'io.grpc:grpc-stub:1.14.0'
    implementation files('libs/protobuf-java-3.6.1.jar')
    //  dialog library
    implementation 'com.github.d-max:spots-dialog:0.7@aar'
    //implementation 'com.google.protobuf:protobuf-lite:3.0.1'
}
configurations {
    compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}

**While Debugging:**
While debugging this error i came to know there was an exception thrown in dynamic method with the name value "GET_MEMOIZED_IS_INITIALIZED" is showing.

This error already rised but the link they given is not proper.

[https://github.com/protocolbuffers/protobuf/issues/3879]
[https://github.com/grpc/grpc-java/issues/4099](url)

The above both are not working still i am facing the issue.

**Comment by hpsaturn** [comment]
I have the same issue on all GRPC request, when call build() in any proto request, for example:

``` java
ProvisionDevicesRequest request = ProvisionDevicesRequest.newBuilder()
                        .addDevices(Device.newBuilder()
                                .setMeta(DeviceMeta.newBuilder()
                                        .setPublicKey(public_key)
                                        .setType(type).build())
                        .build();
```

with it I have:

`W/System.err: java.lang.UnsupportedOperationException`

I have google protos common and my config is:

``` gradle
apply plugin: 'com.android.library'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion project.mCompileSdkVersion.toInteger()

    defaultConfig {
        minSdkVersion project.mMinSdkVersion.toInteger()
        targetSdkVersion project.mTargetSdkVersion.toInteger()
        versionCode project.mVersionCode.toInteger()
        versionName project.mVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            proto {
                srcDirs 'viewbuffers', 'businessapi'
            }
        }
    }

    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(path: ':libtoolscommon')

    implementation 'com.android.support:appcompat-v7:27.1.1'

    implementation "com.google.api.grpc:proto-google-common-protos:1.15.0"
    implementation 'io.grpc:grpc-okhttp:1.19.0'
    implementation 'io.grpc:grpc-protobuf:1.19.0'
    implementation 'io.grpc:grpc-stub:1.19.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.7.0"
    }
    plugins {
        javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.19.0' }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/build/generated"
}
```

**Comment by huy-lv** [comment]
I tried the above build.gradle but it didn't work. 
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "org.appspot.apprtc"
        minSdkVersion 16
        targetSdkVersion 28

        testApplicationId "org.appspot.apprtc.test"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
        dexOptions {
            matchingFallbacks = ['release', 'debug']
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    dependencies {
        implementation 'com.android.support:support-annotations:+'
        implementation 'com.google.protobuf:protobuf-java:3.7.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.7.0"
    }
    plugins {
        javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.19.0' }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/build/generated"
}

configurations {
    compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}
dependencies {
    implementation fileTree(include: ['autobanh.jar'], dir: '../autobanh')
    implementation 'org.webrtc:google-webrtc:1.0.27485'

//    implementation 'com.google.protobuf:protobuf-lite:3.0.1'
    // You need to build grpc-java to obtain these libraries below.
    implementation "com.google.api.grpc:proto-google-common-protos:1.15.0"
    implementation 'io.grpc:grpc-okhttp:1.19.0'
    implementation 'io.grpc:grpc-protobuf:1.19.0'
    implementation 'io.grpc:grpc-stub:1.19.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'
}
```

**Comment by harini2191** [comment]
> I tried the above build.gradle but it didn't work.
> 
> ```
> apply plugin: 'com.android.application'
> apply plugin: 'com.google.protobuf'
> 
> android {
>     compileSdkVersion 28
>     buildToolsVersion "28.0.3"
> 
>     defaultConfig {
>         applicationId "org.appspot.apprtc"
>         minSdkVersion 16
>         targetSdkVersion 28
> 
>         testApplicationId "org.appspot.apprtc.test"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
> 
>     buildTypes {
>         debug {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
>         }
>         dexOptions {
>             matchingFallbacks = ['release', 'debug']
>         }
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
>         }
>     }
> 
>     dependencies {
>         implementation 'com.android.support:support-annotations:+'
>         implementation 'com.google.protobuf:protobuf-java:3.7.1'
>     }
> 
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> }
> 
> protobuf {
>     protoc {
>         artifact = "com.google.protobuf:protoc:3.7.0"
>     }
>     plugins {
>         javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
>         grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.19.0' }
>     }
>     generateProtoTasks {
>         all().each { task ->
>             task.plugins {
>                 javalite {}
>                 grpc {
>                     // Options added to --grpc_out
>                     option 'lite'
>                 }
>             }
>         }
>     }
>     generatedFilesBaseDir = "$projectDir/build/generated"
> }
> 
> configurations {
>     compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
> }
> dependencies {
>     implementation fileTree(include: ['autobanh.jar'], dir: '../autobanh')
>     implementation 'org.webrtc:google-webrtc:1.0.27485'
> 
> //    implementation 'com.google.protobuf:protobuf-lite:3.0.1'
>     // You need to build grpc-java to obtain these libraries below.
>     implementation "com.google.api.grpc:proto-google-common-protos:1.15.0"
>     implementation 'io.grpc:grpc-okhttp:1.19.0'
>     implementation 'io.grpc:grpc-protobuf:1.19.0'
>     implementation 'io.grpc:grpc-stub:1.19.0'
>     implementation 'javax.annotation:javax.annotation-api:1.2'
> }
> ```

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.6.1'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.12.0'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            javalite {}
        }
        ofNonTest()*.plugins {
            grpc {
                // Options added to --grpc_out
                option 'lite'
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    //  GRPC dependencies
    implementation 'io.grpc:grpc-okhttp:1.14.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.14.0'
    implementation 'io.grpc:grpc-stub:1.14.0'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'com.google.api.grpc:googleapis-common-protos:0.0.3'
}
configurations {
    compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}

**Comment by huy-lv** [comment]
@harini2191  i tried your config but got this error, please tell me how, btw is there anyway to chat with you? skype or facebook? i have some question.
![image](https://user-images.githubusercontent.com/7688070/56577496-5c36d100-65f5-11e9-9bf7-8b15a0ff8ef2.png)

**Comment by harini2191** [comment]
> @harini2191 i tried your config but got this error, please tell me how, btw is there anyway to chat with you? skype or facebook? i have some question.
> ![image](https://user-images.githubusercontent.com/7688070/56577496-5c36d100-65f5-11e9-9bf7-8b15a0ff8ef2.png)

this error occured due to some other issue not due to protobuff.

**Comment by Sahil-DD9** [comment]
@BSBandme do we have some workaround/resolution for this issue? I am facing the same error.

**Comment by elharo** [comment]
I'm not sure there's a proto bug here. Do you have a simple test case that can reproduce this?

**Comment by elharo** [comment]
closing since we cannot reproduce and do not have a sample of code to cause this
