### ISSUE TITLE
google-protobuf 3.6.1 gem incompatible with Ruby 2.6.0

### ISSUE THREAD

**Issue by adrianomitre** [protocolbuffers/protobuf#5675]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Ubuntu (GNU/Linux distro)
Linux adriano-Latitude-5490 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

I discovered following [this guide](https://grpc.io/docs/tutorials/basic/ruby.html#example-code-and-setup)

Minimal steps to reproduce the error is the following:
1. install Ruby 2.6.0p0 and make it active (ex: `rbenv install 2.6.0`, then `rbenv local 2.6.0`)
2. gem install google-protobuf
3. ruby -e "require 'google/protobuf'"

**What did you expect to see**

No error.

**What did you see instead?**

``` shell
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/protobuf (LoadError)
	6: from -e:1:in `<main>'
	5: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from ~/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:48:in `<top (required)>'
	1: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/2.6/protobuf_c (LoadError)
	7: from -e:1:in `<main>'
	6: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	5: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	4: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	3: from ~/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:47:in `<top (required)>'
	2: from ~/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
	1: from ~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/protobuf_c (LoadError)
```

**Anything else we should know about your project / environment**

Also opened a bug report for Ruby: https://bugs.ruby-lang.org/issues/15585

**Comment by TeBoring** [comment]
We have released 3.7.0-rc2, which supports ruby 2.6
