### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by Futi7** [protocolbuffers/protobuf#5694]
## C:\tensorflow\models\research>python object_detection\model_main.py --pipeline_config_path=object_detection\training\ssd_mobilenet_v1_pets.config --model_dir=object_detection\images --num_train_steps=50000 --sample_1_of_n_eval_examples=1 --alsologtostderr
Traceback (most recent call last):
File "object_detection\model_main.py", line 26, in
from object_detection import model_lib
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\model_lib.py", line 27, in
from object_detection import eval_util
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\eval_util.py", line 27, in
from object_detection.metrics import coco_evaluation
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\metrics\coco_evaluation.py", line 22, in
from object_detection.utils import object_detection_evaluation
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\utils\object_detection_evaluation.py", line 39, in
from object_detection.utils import label_map_util
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\utils\label_map_util.py", line 21, in
from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'
----------------------------------------

I got this error.How can i fix it.I installed protobuf, compiled it, added to path.

Top-level directory:c:/tensorflow/models
OS:Windows 10
CPU:AMD A9 7th Gen.
GPU:AMD Radeon R5 M420 2GB
Using Python version:3.6
Protobuf version:3.4.0
Tensorflow installed from:pip
Tensorflow Version:1.12.0
Bazel version:N/A
CUDA/cuDNN version:N/A
Exact command:#from tensorflow/models/research/object_detection
python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config

**Comment by anandolee** [comment]
Have you contacted tensorflow. We do not know how model_main.py is using protobuf

**Comment by anandolee** [comment]
Closing it for clean up and looks like more relate to tensorflow usage issue. Feel free to reopen if needed.
