### ISSUE TITLE
ruby gem load error: cannot load such file -- google/2.6/protobuf_c with ruby 2.6.1p33

### ISSUE THREAD

**Issue by directionless** [protocolbuffers/protobuf#5701]
This appears to be a recurrence of https://github.com/protocolbuffers/protobuf/issues/3509

Folks have commented there, but it seems worth bringing this into it's own ticket.

I'm running on macosx, ruby 2.6.1. And I see this problem with google-protobuf 2.6.0, 2.6.1, and 3.5.1.2.

Notably, I can load the gem fine with 3.7.0.rc.2

```
$ ruby --version
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin17]

$ bundle exec ruby -e 'require "google/protobuf"; puts "hi"'
Traceback (most recent call last):
	3: from -e:1:in `<main>'
	2: from -e:1:in `require'
	1: from /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
/Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:48:in `require': cannot load such file -- google/2.6/protobuf_c (LoadError)
	4: from -e:1:in `<main>'
	3: from -e:1:in `require'
	2: from /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:47:in `<top (required)>'
	1: from /Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
/Users/seph/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:50:in `require': cannot load such file -- google/protobuf_c (LoadError)
```

**Comment by rurounijones** [comment]
Same issue on Linux with 3.6.1                                                                                                                                                                          

```
> bundle install
Using google-protobuf 3.6.1 (x86_64-linux)
Using googleapis-common-protos-types 1.0.3
```

```
Traceback (most recent call last):
        7: from bin/console:7:in `<main>'
        6: from bin/console:7:in `each'
        5: from bin/console:7:in `block in <main>'
        4: from bin/console:7:in `require'
        3: from /home/jjones/Programming/ganges/grpc-ruby-code/lib/product_pb.rb:4:in `<top (required)>'
        2: from /home/jjones/Programming/ganges/grpc-ruby-code/lib/product_pb.rb:4:in `require'
        1: from /home/jjones/.rvm/gems/ruby-2.6.1@grpc/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:48:in `<top (required)>'
/home/jjones/.rvm/gems/ruby-2.6.1@grpc/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:48:in `require': cannot load such file -- google/2.6/protobuf_c (LoadError)
        8: from bin/console:7:in `<main>'
        7: from bin/console:7:in `each'
        6: from bin/console:7:in `block in <main>'
        5: from bin/console:7:in `require'
        4: from /home/jjones/Programming/ganges/grpc-ruby-code/lib/product_pb.rb:4:in `<top (required)>'
        3: from /home/jjones/Programming/ganges/grpc-ruby-code/lib/product_pb.rb:4:in `require'
        2: from /home/jjones/.rvm/gems/ruby-2.6.1@grpc/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:47:in `<top (required)>'
        1: from /home/jjones/.rvm/gems/ruby-2.6.1@grpc/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
/home/jjones/.rvm/gems/ruby-2.6.1@grpc/gems/google-protobuf-3.6.1-x86_64-linux/lib/google/protobuf.rb:50:in `require': cannot load such file -- google/protobuf_c (LoadError)

```

**Comment by TeBoring** [comment]
I guess the problem is, before 3.7.0.rc.2, we never supported ruby 2.6.
Thus, for ruby 2.6, you have to use protobuf 3.7

**Comment by KLCrow** [comment]
I have the same error:
ruby-2.7.3
rails (4.2.11.1)
google-protobuf (3.15.8)
grpc (1.31.1)
 cannot load such file -- ..._pb (LoadError)
