### ISSUE TITLE
`pip install git+` failing. "Command "python setup.py egg_info" failed with error code 1"

### ISSUE THREAD

**Issue by thundernixon** [protocolbuffers/protobuf#5722]
I'm trying to install the latest version of Protobuf to get around a limitation in the current GA release which breaks on non-ASCII characters in Google Fonts `METADATA.pb` files (which are relatively common in designer names). This problem exists in Protobuf 3.6, but sounds like it has been fixed for the upcoming 3.7 release. However, I'm hoping to use the fix today to generate accurate `METADATA.pb` files.

### First attempt

I've tried to use `pip install git+https://github.com/protocolbuffers/protobuf.git`, but this is failing for me with the following output:

```bash
▶ pip3 install git+https://github.com/protocolbuffers/protobuf
---------------------------------------------------------------------------------------------
Collecting git+https://github.com/protocolbuffers/protobuf.git
  Cloning https://github.com/protocolbuffers/protobuf.git to /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-ctxaygel
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/stephennixon/Environments/gf/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-ctxaygel/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-ctxaygel/
```

I've done some troubleshooting, ensuring that I have the latest version of homebrew python and `setuptools`. Beyond that, I'm not finding much direction. 

The `git+` approach does work fine in this format for fontbakery (another tool I'm using in my current projects), so I don't _think_ I've made an obvious mistake in my basic syntax. 

### Second attempt

I've also tried to install by downloading the latest release candidate zip, then going into the `/python` directory of it and using `pip install .`. However, this yields the following error:

```bash
▶ pip install .
---------------------------------------------------------------------------------------------
Processing /Users/stephennixon/Downloads/protobuf-3.7.0-rc-2/python
Requirement already satisfied: six>=1.9 in /Users/stephennixon/Environments/gf/lib/python3.7/site-packages (from protobuf==3.7.0rc2) (1.12.0)
Requirement already satisfied: setuptools in /Users/stephennixon/Environments/gf/lib/python3.7/site-packages (from protobuf==3.7.0rc2) (40.8.0)
Building wheels for collected packages: protobuf
  Building wheel for protobuf (setup.py) ... error
  Complete output from command /Users/stephennixon/Environments/gf/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-b1nulsr8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-wheel-v8dsmklv --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  Generating google/protobuf/descriptor_pb2.py...
  Can't find required file: ../src/google/protobuf/descriptor.proto

  ----------------------------------------
  Failed building wheel for protobuf
  Running setup.py clean for protobuf
Failed to build protobuf
Installing collected packages: protobuf
  Found existing installation: protobuf 3.6.1
    Uninstalling protobuf-3.6.1:
      Successfully uninstalled protobuf-3.6.1
  Running setup.py install for protobuf ... error
    Complete output from command /Users/stephennixon/Environments/gf/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-b1nulsr8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-record-cb9ja53_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stephennixon/Environments/gf/bin/../include/site/python3.7/protobuf:
    running install
    running build
    running build_py
    Generating google/protobuf/descriptor_pb2.py...
    Can't find required file: ../src/google/protobuf/descriptor.proto

    ----------------------------------------
  Rolling back uninstall of protobuf
  Moving to /Users/stephennixon/Environments/gf/lib/python3.7/site-packages/google/protobuf/
   from /Users/stephennixon/Environments/gf/lib/python3.7/site-packages/google/~rotobuf
  Moving to /Users/stephennixon/Environments/gf/lib/python3.7/site-packages/protobuf-3.6.1-py3.7-nspkg.pth
   from /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-uninstall-m_ubk7p8/protobuf-3.6.1-py3.7-nspkg.pth
  Moving to /Users/stephennixon/Environments/gf/lib/python3.7/site-packages/protobuf-3.6.1.dist-info/
   from /Users/stephennixon/Environments/gf/lib/python3.7/site-packages/~rotobuf-3.6.1.dist-info
Command "/Users/stephennixon/Environments/gf/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-b1nulsr8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-record-cb9ja53_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stephennixon/Environments/gf/bin/../include/site/python3.7/protobuf" failed with error code 255 in /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-b1nulsr8/
```

---

Am I missing some way I could install the latest version of protobuf, or is this potentially something that could be a problem in the current Protobuf? I'm guessing the issue is something on my end, and if anyone is able to help me shed some light on how to resolve it, I would be very grateful!

**Comment by thundernixon** [comment]
I've also tried to `pip install` from the `/python` directory on GitHub, and this also fails, but gives a different error:

```bash
▶ pip install -U https://github.com/protocolbuffers/protobuf/tree/master/python
--------------------------------------------------------------------------------
Collecting https://github.com/protocolbuffers/protobuf/tree/master/python
  Downloading https://github.com/protocolbuffers/protobuf/tree/master/python
     \ 102kB 5.3MB/s
  Cannot unpack file /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-unpack-xvw_kvoe/python (downloaded from /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-wx_tfggb, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-req-build-wx_tfggb
```

**Comment by thundernixon** [comment]
After reading more about [version control support from Pip](https://pip.pypa.io/en/latest/reference/pip_install/#vcs-support), I've also tried:

```
pip install -U git+https://github.com/protocolbuffers/protobuf/#egg=pkg&subdirectory=python
```

...but this resulted in:

```bash
Collecting pkg from git+https://github.com/protocolbuffers/protobuf/#egg=pkg
  Cloning https://github.com/protocolbuffers/protobuf/ to /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-install-n257f2nu/pkg
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/stephennixon/Environments/gf/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-install-n257f2nu/pkg/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/04/h__ps70x2sv6yk_6ldwqj0600000gn/T/pip-install-n257f2nu/pkg/

[1]  + 51645 exit 1     pip install -U git+https://github.com/protocolbuffers/protobuf/#egg=pkg
```

**Comment by thundernixon** [comment]
OH. This was simpler than I expected.

Running `pip install protobuf==3.7.0rc2` seems to work. 

The metadata file for piece of data containing a non-ASCII character will now generate. 🤘
