### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.protobuf.GeneratedMessageLite$MethodToInvoke.ordinal()' on a null object reference

### ISSUE THREAD

**Issue by mikelehen** [protocolbuffers/protobuf#6149]
**What version of protobuf and what language are you using?**
Version: com.google.protobuf:protobuf-lite:3.0.1
Language: Java (Android)

**What operating system (Linux, Windows, ...) and version?**
Android 4.2.2, 5.1.1

**What did you do?**
A user of the Firestore SDK has [reported](https://github.com/firebase/firebase-android-sdk/issues/442) seeing the following crash:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.protobuf.GeneratedMessageLite$MethodToInvoke.ordinal()' on a null object reference
       at com.google.firebase.firestore.proto.MaybeDocument.dynamicMethod(com.google.firebase:firebase-firestore@@18.2.0:693)
       at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:288)
       at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1353)
       at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1432)
       at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1449)
       at com.google.firebase.firestore.proto.MaybeDocument.parseFrom(com.google.firebase:firebase-firestore@@18.2.0:380)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.decodeMaybeDocument(com.google.firebase:firebase-firestore@@18.2.0:162)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$getAllDocumentsMatchingQuery$2(com.google.firebase:firebase-firestore@@18.2.0:139)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache$$Lambda$3.accept(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@18.2.0:431)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getAllDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:125)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingCollectionQuery(com.google.firebase:firebase-firestore@@18.2.0:182)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:140)
       at com.google.firebase.firestore.local.SimpleQueryEngine.getDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:39)
       at com.google.firebase.firestore.local.LocalStore.executeQuery(com.google.firebase:firebase-firestore@@18.2.0:583)
       at com.google.firebase.firestore.core.SyncEngine.initializeViewAndComputeSnapshot(com.google.firebase:firebase-firestore@@18.2.0:189)
       at com.google.firebase.firestore.core.SyncEngine.listen(com.google.firebase:firebase-firestore@@18.2.0:179)
       at com.google.firebase.firestore.core.EventManager.addQueryListener(com.google.firebase:firebase-firestore@@18.2.0:91)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$6(com.google.firebase:firebase-firestore@@18.2.0:152)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@18.2.0:311)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@18.2.0:287)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@18.2.0)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@18.2.0:205)
       at java.lang.Thread.run(Thread.java:818)
```

**What did you expect to see**
No crash.

**What did you see instead?**
Crash.

**Anything else we should know about your project / environment**
We're not sure what might have caused this.  We'd like to know if there is any known circumstances where we would expect to see this error, or if it represents a bug in protobuf.

**Comment by BSBandme** [comment]
It looks like some problem with Proguard or mixed different versions' generated code and runtime library.

Is it possible to get the generated dynamicMethod code of com.google.firebase.firestore.proto.MaybeDocument for both unobfuscate and obfuscate version?

**Comment by mikelehen** [comment]
Thanks.  I'm not sure how to get the generated code.  If you know I can ask the developer (or feel free to chime in on https://github.com/firebase/firebase-android-sdk/issues/442).  In the meantime, I've asked if they could try disabling proguard to see if that makes a difference.

**Comment by mikelehen** [comment]
The developer reports that this only happened a single time for a single user and so I don't think it's a proguard issue (and likely isn't actionable in general).  If there aren't any other obvious theories for what would cause this to happen, I'm okay closing this.

**Comment by haon4** [comment]
OK, let's close this then.
