### ISSUE TITLE
TypeError: cannot make memory view because object does not have the buffer interface

### ISSUE THREAD

**Issue by orestis-ms** [protocolbuffers/protobuf#6157]
Version: master/v3.7.1
Language: Python
proto2

Linux
Python 2.7.12

I have a large .proto file that works well in C#. I want to use it in python. After compiling my .proto file I try to import the .py file. I get the exception below.

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Demo_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Demo_pb2.py", line 17860, in <module>
    '__module__' : 'Demo_pb2'
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.7.1-py2.7.egg/google/protobuf/internal/python_message.py", line 183, in __init__
    descriptor.GetOptions().message_set_wire_format):
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.7.1-py2.7.egg/google/protobuf/descriptor.py", line 160, in GetOptions
    self._serialized_options)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.7.1-py2.7.egg/google/protobuf/descriptor.py", line 926, in _ParseOptions
    message.ParseFromString(string)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.7.1-py2.7.egg/google/protobuf/message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.7.1-py2.7.egg/google/protobuf/internal/python_message.py", line 1121, in MergeFromString
    serialized = memoryview(serialized)
TypeError: cannot make memory view because object does not have the buffer interface
```

It corresponds to these lines in the .py file:
```CacheObjectId = _reflection.GeneratedProtocolMessageType('CacheObjectId', (_message.Message,), {
  'DESCRIPTOR' : _CACHEOBJECTID,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:CacheObjectId)
  })
_sym_db.RegisterMessage(CacheObjectId)
```
Overall, CacheObjectId is the first _message_ definition in the proto file, and the above snippet is the first in its group.

**Comment by connoranderson** [comment]
What ended up being the resolution to this issue?

**Comment by elharo** [comment]
Python 2 no longer supported
