### ISSUE TITLE
Unit test "testPrintUnknownFields" fails with i386 build

### ISSUE THREAD

**Issue by roehling** [protocolbuffers/protobuf#6205]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux 18.04 amd64

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 7.4
Python 2.7.15rc1
Python 3.6.7

**What did you do?**
I built the library in a 32-bit chroot on a 64-bit system to create i386 debian packages

**What did you expect to see**
The build succeeds as it does in the 64-bit build.

**What did you see instead?**
```
======================================================================
FAIL: testPrintUnknownFields (google.protobuf.internal.text_format_test.OnlyWorksWithProto2RightNowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/protobuf-3.8.0/python/google/protobuf/internal/text_format_test.py", line 847, in testPrintUnknownFields
    print_unknown_fields=True))
AssertionError: '1: 101\n12: 4636878028842991616\n14: "hello"\n15: "103"\n16 {\n  17: 104\n}\n18 {\n  1: 105\n}\n' != '1: 101\n12: 0\n14: "hello"\n15: "103"\n16 {\n  17: 104\n}\n18 {\n  1: 105\n}\n'

----------------------------------------------------------------------
Ran 816 tests in 1.507s

FAILED (failures=1, skipped=10)
```

**Comment by GreenReaper** [comment]
The 2.7 build is [failing on other 32-bit Debian ports too](https://buildd.debian.org/status/package.php?p=protobuf&suite=experimental): x32, armhf/el, powepc and hppa

On such platforms C 'long' (which [Python used as regular 'int' in 2.x](https://www.python.org/dev/peps/pep-0237/)) is likely to be 32-bit, like C 'int'. 4636878028842991616 is too big to be a 32-bit integer - you need a 'long long' (Python 2.7's 'long int').

If such a large value is being round-tripped or interpreted through a 'long' that is only 32-bits, that might explain the issue. Especially since the least significant bits of the above integer are all zero.

I don't have *any* experience with protobuf, or for that matter Python's interaction with native code, so take this with a huge grain of salt, but after wandering around for a few hours I found [this code](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/pyext/unknown_fields.cc#L272):
```
static PyObject* GetData(PyUnknownFieldRef* self, void *closure) {
  const UnknownField* field = GetUnknownField(self);
  if (field == NULL) {
    return NULL;
  }
  PyObject* data = NULL;
  switch (field->type()) {
    case UnknownField::TYPE_VARINT:
      data = PyInt_FromLong(field->varint());
      break;
    case UnknownField::TYPE_FIXED32:
      data = PyInt_FromLong(field->fixed32());
      break;
    case UnknownField::TYPE_FIXED64:
      data = PyInt_FromLong(field->fixed64());
      break;
[...]
```
Shouldn't at least some of those PyInt_FromLong calls be PyLong_FromLongLong? [Message::InternalGetScalar](https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/pyext/message.cc#L2172) uses them - and the basic idea of extracting a 32-bit integer from a variable-length or 64-bit integer seems off.

**Comment by anandolee** [comment]
Thank you @GreenReaper 

@roehling are you happy to help create a fix to it according to @GreenReaper 's reply? I do not have 32-bit machine to reproduce the error

**Comment by roehling** [comment]
Sure! I can prepare a PR and refer to this issue.

**Comment by marxenegls** [comment]
exact same issue on python3/armhf  
FAIL: testPrintUnknownFields (google.protobuf.internal.text_format_test.OnlyWorksWithProto2RightNowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/protobuf-3.11.2/python/google/protobuf/internal/text_format_test.py", line 924, in testPrintUnknownFields
    print_unknown_fields=True))
AssertionError: '  1: 101\n  12: 4636878028842991616\n  14: "hello"\n  15:[55 chars] }\n' != '  1: 101\n  12: 0\n  14: "hello"\n  15: "103"\n  16 {\n  [37 chars] }\n'
    1: 101
-   12: 4636878028842991616
+   12: 0
    14: "hello"
    15: "103"
    16 {
      17: 104
    }
    18 {
      1: 105
    }

**Comment by SLOG-IAM** [comment]
Thank you @roehling

**Comment by dodinhphat** [comment]
Thank you @roehling
