### ISSUE TITLE
Protobuf-Java-Lite and Protobuf-Java dependency problems with 3.8

### ISSUE THREAD

**Issue by DanFTRX** [protocolbuffers/protobuf#6249]
**What version of protobuf and what language are you using?**
Version: v3.8.0
Language: Java

**What operating system (Linux, Windows, ...) and version?** N\A

**What runtime / compiler are you using (e.g., python version or gcc version)** Android Studio 3.2.0

**What did you do?**
1. Create a project that depends on protobuf-javalite
2. Add a dependency on [Roboletric](https://github.com/robolectric/robolectric) (which depends on [Accessibility-Test-Framework-for-Android](https://github.com/google/Accessibility-Test-Framework-for-Android), which depends on protobuf-java-2.6.1)
3. Create a unit test that uses a generated protobuf message
ex:
```Java
    @Test
    public void ProtoLite()
    {
        Example.ProtoTest test = (Example.ProtoTest)Example.ProtoTest.newBuilder()
                .setField("test")
                .setId(1)
                .buildPartial();
    }
```
4. Compile and run the unit test.

**What did you expect to see**
I would expect the unit test to run on the protobuf-javalite runtime I specified rather than the protobuf-java runtime transitively inherited from the dependency chain.

**What did you see instead?**
When run via Android Studio, the tests throw an exception 
```
java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V

	at com.example.Example$ProtoTest.<clinit>(Example.java:335)
	at com.example.ExampleUnitTest.addition_isCorrect(ExampleUnitTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The unit test is running against the 2.6.1 protobuf-java runtime from the robolectric dependency rather than the 3.8.0 protobuf-javalite runtime intended and set in the gradle file.

I've attached an example project to demonstrate the issue.
[Example.zip](https://github.com/protocolbuffers/protobuf/files/3282921/Example.zip)

**Comment by DanFTRX** [comment]
It seems this problem only exists when you are relying on transitive dependencies to supply the protobuf-javalite runtime.  If I add an explicit "implementation 'com.google.protobuf:protobuf-java:3.8.0'" into the project, the issue goes away.  

Additionally I realized my ExampleProject didn't actually exhibit the issues I described by the time I stripped away all the fluff.

**Comment by Clement-Jean** [comment]
@DanFTRX I currently have the same problem, did you find a solution ?

**Comment by DanFTRX** [comment]
@Clement-Jean Yeah, just explicitly exclude the protobuf package in gradle when including the library.

``` 
   testImplementation ("org.robolectric:robolectric:${rootProject.ext.robolectricVersion}") {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
    }
```
