### ISSUE TITLE
IndexOutOfBoundsException when parsing an invalid message

### ISSUE THREAD

**Issue by alpire** [protocolbuffers/protobuf#6425]
**What version of protobuf and what language are you using?**
Version: 3.7.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
MacOS Mojave

**What runtime / compiler are you using (e.g., python version or gcc version)**
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)

**What did you do?**
1. Get the AddressBook proto file from the java tutorial https://developers.google.com/protocol-buffers/docs/javatutorial & compile it with `protoc -I. --java_out=. address-book.proto`
2. Create Main.java:

```java
import com.example.tutorial.AddressBookProtos.AddressBook;
import com.example.tutorial.AddressBookProtos.Person;

class Main {
    public static void main(String[] args) throws Throwable {
        AddressBook addressBook = AddressBook.parseFrom(new byte[]{0xa, (byte)0xff, (byte)0xff, (byte)0xff, (byte)0xff, 0x57, (byte)0xf2, 0x00, (byte)0x99, 0x4c});
    }
}
```

3. Run it `java -cp .:protobuf-java-3.7.1.jar Main.java` to reproduce the exception

**What did you expect to see**
I expected to see a `com.google.protobuf.InvalidProtocolBufferException`, a `com.google.protobuf.TextFormat.InvalidEscapeSequenceException`, or a `com.google.protobuf.TextFormat.ParseException`

**What did you see instead?**

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: End index: 9763 >= 10
        at com.google.protobuf.ByteString.checkRange(ByteString.java:1249)
        at com.google.protobuf.ByteString.copyFrom(ByteString.java:352)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:899)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:506)
        at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:298)
        at com.example.tutorial.AddressBookProtos$Person.<init>(AddressBookProtos.java:151)
        at com.example.tutorial.AddressBookProtos$Person.<init>(AddressBookProtos.java:85)
        at com.example.tutorial.AddressBookProtos$Person$1.parsePartialFrom(AddressBookProtos.java:2010)
        at com.example.tutorial.AddressBookProtos$Person$1.parsePartialFrom(AddressBookProtos.java:2004)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:883)
        at com.example.tutorial.AddressBookProtos$AddressBook.<init>(AddressBookProtos.java:2104)
        at com.example.tutorial.AddressBookProtos$AddressBook.<init>(AddressBookProtos.java:2061)
        at com.example.tutorial.AddressBookProtos$AddressBook$1.parsePartialFrom(AddressBookProtos.java:2802)
        at com.example.tutorial.AddressBookProtos$AddressBook$1.parsePartialFrom(AddressBookProtos.java:2796)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.example.tutorial.AddressBookProtos$AddressBook.parseFrom(AddressBookProtos.java:2274)
        at Main.main(Main.java:6)
```

**Anything else we should know about your project / environment**

This input was found with fuzzing. I have a couple more exceptions similar to that one, so let me know if those parsing bugs are of interest to you!

**Comment by alpire** [comment]
Fuzzing found a similar stacktrace that probably stems from the same bug. I thought I'd include the testcase for completeness.

**Runnable testcase**

```java
import com.example.tutorial.AddressBookProtos.AddressBook;
import com.example.tutorial.AddressBookProtos.Person;

class Main {
  public static void main(String[] args) throws Throwable {
    AddressBook addressBook = AddressBook.parseFrom(new byte[]{0x18, (byte)0x7f, 0x0a, 0x3, (byte)0xe8, 0x3, 0, 0xa, (byte)0xff, (byte)0xff, (byte)0xff, (byte)0xff, 0x7, 0xa, (byte)0xef, (byte)0xff, (byte)0xff, (byte)0xff, 0x7, 0});
  }
}
```

**Stacktrace**

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Beginning index larger than ending index: 19, -2147483646
        at com.google.protobuf.ByteString.checkRange(ByteString.java:1245)
        at com.google.protobuf.ByteString.copyFrom(ByteString.java:352)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:899)
        at com.example.tutorial.AddressBookProtos$Person.<init>(AddressBookProtos.java:125)
        at com.example.tutorial.AddressBookProtos$Person.<init>(AddressBookProtos.java:85)
        at com.example.tutorial.AddressBookProtos$Person$1.parsePartialFrom(AddressBookProtos.java:2010)
        at com.example.tutorial.AddressBookProtos$Person$1.parsePartialFrom(AddressBookProtos.java:2004)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:883)
        at com.example.tutorial.AddressBookProtos$AddressBook.<init>(AddressBookProtos.java:2104)
        at com.example.tutorial.AddressBookProtos$AddressBook.<init>(AddressBookProtos.java:2061)
        at com.example.tutorial.AddressBookProtos$AddressBook$1.parsePartialFrom(AddressBookProtos.java:2802)
        at com.example.tutorial.AddressBookProtos$AddressBook$1.parsePartialFrom(AddressBookProtos.java:2796)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.example.tutorial.AddressBookProtos$AddressBook.parseFrom(AddressBookProtos.java:2274)
        at Main.main(Main.java:6)
```

**Comment by elharo** [comment]
I was not able to immediately reproduce this at head. I suspect it's been fixed in the time since it was reported, but if not please comment and I'll take another look.

**Comment by elharo** [comment]
I believe this was reported internally as b/183776425 and fixed there.
