### ISSUE TITLE
error: when installing from setup.py  enum_type_wrapper.EnumTypeWrapper(_IS)  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MLDPEngineer** [protocolbuffers/protobuf#6500]
**When installing the protobuf:**
`https://github.com/protocolbuffers/protobuf.git
cd protobuf/python
python setup.py build 
python setup.py test
`

**The error:**
`running build_ext
Traceback (most recent call last):
  File "setup.py", line 284, in <module>
    ext_modules=ext_module_list,
  File "/home/protus/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/protus/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/protus/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/protus/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/protus/anaconda3/lib/python3.7/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/home/protus/anaconda3/lib/python3.7/site-packages/setuptools/command/test.py", line 251, in run_tests
    exit=False,
  File "/home/protus/anaconda3/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/protus/anaconda3/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/home/protus/anaconda3/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/home/protus/anaconda3/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/protus/anaconda3/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/protus/anaconda3/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/protus/anaconda3/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/protus/anaconda3/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/protus/Downloads/protobuf/python/google/protobuf/internal/descriptor_pool_test2_pb2.py", line 17, in <module>
    from google.protobuf.internal import more_messages_pb2 as google_dot_protobuf_dot_internal_dot_more__messages__pb2
  File "/home/protus/Downloads/protobuf/python/google/protobuf/internal/more_messages_pb2.py", line 49
    is = enum_type_wrapper.EnumTypeWrapper(_IS)
     ^
SyntaxError: invalid syntax
`

**After that:**
`python setup.py install`

**Another error:**
`...
byte-compiling build/bdist.linux-x86_64/egg/google/protobuf/internal/more_messages_pb2.py to more_messages_pb2.cpython-37.pyc
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/more_messages_pb2.py", line 49
    is = enum_type_wrapper.EnumTypeWrapper(_IS)
     ^
SyntaxError: invalid syntax
...`
`...Extracting protobuf-3.9.1-py3.7.egg to /home/protus/anaconda3/lib/python3.7/site-packages
  File "/home/protus/anaconda3/lib/python3.7/site-packages/protobuf-3.9.1-py3.7.egg/google/protobuf/internal/more_messages_pb2.py", line 49
    is = enum_type_wrapper.EnumTypeWrapper(_IS)
     ^
SyntaxError: invalid syntax
...`

**System is:**

Protobuf: 3.9.1
Language: Python 3.7.3
Ubuntu 18.04.3 LTS
gcc: 7.4.0
setuptools: 41.0.1

**I need to install only from setup.py, not from pip.**

**Comment by spacecraft1013** [comment]
I have the same issue. Has anyone found a fix yet?

**Comment by davidwlewis** [comment]
There's an enum ([here](https://github.com/protocolbuffers/protobuf/blob/a62ee83401cb28052342c3833dcdb552e9c5a8ca/python/google/protobuf/internal/more_messages.proto#L56)) called "is" which generates invalid python since its a keyword.

**Comment by romainletendart** [comment]
The issue seems to be fixed from 3.11.3 onwards.
