### ISSUE TITLE
Android 5.0 java.lang.NoSuchMethodError: No virtual method putBoolean(Ljava/lang/Object;JZ)

### ISSUE THREAD

**Issue by grill2010** [protocolbuffers/protobuf#6551]
**What version of protobuf and what language are you using?**
v3.8.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Android 5.0

**What runtime / compiler are you using (e.g., python version or gcc version)**
I used the [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin)

**What did you do?**
The project compiled fine however during runtime I git the java.lang.NoSuchMethodError exception when I try to parse one of my messages.

**What did you expect to see**
Not an Exception like on my other Android devices (I tested on two others Android 9 and android 8). Sorry I know this is not very detailed but I do not have an idea what might be wrong.

**What did you see instead?**

> 08-22 15:54:24.216 24624-24728/psplay.grill.com E/AndroidRuntime: FATAL EXCEPTION: Thread-2041
    Process: psplay.grill.com, PID: 24624
    java.lang.NoSuchMethodError: No virtual method putBoolean(Ljava/lang/Object;JZ)V in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
        at com.google.protobuf.UnsafeUtil$JvmMemoryAccessor.putBoolean(UnsafeUtil.java:620)
        at com.google.protobuf.UnsafeUtil.putBoolean(UnsafeUtil.java:143)
        at com.google.protobuf.MessageSchema.parseProto2Message(MessageSchema.java:4968)
        at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5398)
        at com.google.protobuf.ArrayDecoders.decodeMessageField(ArrayDecoders.java:246)
        at com.google.protobuf.MessageSchema.parseProto2Message(MessageSchema.java:4988)
        at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5398)
        at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1552)
        at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1652)

it happened on the method _com.google.protobuf.GeneratedMessageLite.parseFrom_

**Anything else we should know about your project / environment**

I attached my gradle file.
[build.zip](https://github.com/protocolbuffers/protobuf/files/3530529/build.zip)

**Comment by grill2010** [comment]
Sure, but in the meantime I have upgraded to protobuf v3.9.1. But what I noticed is that the code for _getMemoryAccessor_ which should return the specific Android memory accessors is different than yours. Mine looks like this:

```
/** Get a {@link MemoryAccessor} appropriate for the platform, or null if not supported. */
  private static MemoryAccessor getMemoryAccessor() {
    if (UNSAFE == null) {
      return null;
    }
    return new JvmMemoryAccessor(UNSAFE);
  }
```

So there is no check and the Android64MemoryAccessor and Android32MemoryAccessor classes do not exist at all. It is part of this [commit](https://github.com/protocolbuffers/protobuf/commit/4f02f056b5cea99052bfdfb6698afe47a3cf2964) which is only a couple of days old so I think there is not yet a release version which contains this update yet. Or do I miss something?

**Comment by grill2010** [comment]
Okay no problem. Thanks for your help.
Looking forward to the next release.

**Comment by DysaniazzZ** [comment]
when will the next release be available? @rafi-kamal @TeBoring

**Comment by rafi-kamal** [comment]
I'm still working on it. RC1 should be available in a day or two.

**Comment by grill2010** [comment]
Tried it now with two older Android devices (Samsung Galaxy S4 with Android 5.0. and another Samsung phone with Android 6.0.1)
The [release candidate ](https://github.com/protocolbuffers/protobuf/releases/tag/v3.10.0-rc1) seems to have fixed the issue. Thank you very much.

**Comment by yanbober** [comment]
i have the same issues, float and boolean is boom!

**Comment by grill2010** [comment]
@yanbober update to the newest version. I used v3.10.0-rc1 and it worked for me.
