### ISSUE TITLE
Cannot deserialize empty strings as Map values in JavaScript

### ISSUE THREAD

**Issue by paambaati** [protocolbuffers/protobuf#6642]
**What version of protobuf and what language are you using?**
Version: v3.9.1
Language: Javascript

**What operating system (Linux, Windows, ...) and version?**
macOS Mojave 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple LLVM version 10.0.1 (`clang-1001.0.46.4`)
Target: x86_64-apple-darwin18.7.0

**What did you do?**
I'm using generated static bindings from https://github.com/liftbridge-io/liftbridge-grpc/blob/5694b15f251d2ff16d7d4c3e8d944aab327d3ef0/api.proto#L93-L104 to create a Liftbridge Node.js client that will create a stream and publish some messages and subscribe to them (Liftbridge is a kind of lightweight Kafka), and I run into an `Failed to parse server response` error consistently whenever I try to consume the [`Subscribe` stream](https://github.com/liftbridge-io/liftbridge-grpc/blob/0877a0cacb7a721e2e19280cff126dc2ed51912d/api.proto#L129).

**Steps to reproduce the behavior**
1. `docker run -p 4222:4222 -ti nats:latest --debug --trace` in a window.
2. `go get github.com/liftbridge-io/go-liftbridge` and then `$GOPATH/bin/liftbridge --raft-bootstrap-seed --nats-servers nats://localhost:4222 --level debug` in another window.
3. Clone my repo from `https://github.com/paambaati/node-liftbridge.git` in yet another window.
	1. `yarn install` or `npm install`
	2. `yarn run debug` or `npm run debug` to run the debug script that reproduces this issue.

The [debug script](https://github.com/paambaati/node-liftbridge/blob/master/src/debug.ts) attempts to create a new stream, then publish a few messages, then subscribes to the same stream (subject) and then publishes a few more messages.

**What did you expect to see**
Each published message should be printed to console ([see relevant lines](https://github.com/paambaati/node-liftbridge/blob/ad04598126778c5944d5b78a5f153ccc927b1378/src/debug.ts#L37-L42)).

**What did you see instead?**
```
[AssertionError]: Assertion failed
    at new goog.asserts.AssertionError ~/node-liftbridge/node_modules/google-protobuf/google-protobuf.js:79:876)
    at Object.goog.asserts.doAssertFailure_ ~/node-liftbridge/node_modules/google-protobuf/google-protobuf.js:80:257)
    at Object.goog.asserts.assert [as assert] ~/node-liftbridge/node_modules/google-protobuf/google-protobuf.js:81:83)
    at Function.jspb.Map.deserializeBinary ~/node-liftbridge/node_modules/google-protobuf/google-protobuf.js:275:277)
    at ~/node-liftbridge/grpc/generated/api_pb.js:2259:18
    at jspb.BinaryReader.readMessage ~/node-liftbridge/node_modules/google-protobuf/google-protobuf.js:249:329)
    at Function.proto.proto.Message.deserializeBinaryFromReader ~/node-liftbridge/grpc/generated/api_pb.js:2258:14)
    at Function.proto.proto.Message.deserializeBinary ~/node-liftbridge/grpc/generated/api_pb.js:2214:30)
    at deserialize_proto_Message ~/node-liftbridge/grpc/generated/api_grpc_pb.js:59:25)
    at ~/node-liftbridge/node_modules/grpc/src/common.js:38:12
    at ~/node-liftbridge/node_modules/grpc/src/client_interceptors.js:689:22 {
  message: 'Assertion failed',
  reportErrorToServer: true,
  messagePattern: 'Assertion failed'
}
```

The problem is when the headers map has an undefined value. The Go client reads it as an empty string (`headers:<key:"reply" value:"" >`) while `protobuf` reads it as `undefined`, and hence the assertion error.

**Related issues**
1. https://github.com/grpc/grpc-node/issues/1022
2. https://github.com/protobufjs/protobuf.js/issues/1293

**Anything else we should know about your project / environment**
1. The static bindings were generated by a script - [see relevant command here](https://github.com/paambaati/node-liftbridge/blob/ad04598126778c5944d5b78a5f153ccc927b1378/scripts/generate_grpc_code.sh#L48-L56). The bindings are checked-in at [`grpc/generated`](https://github.com/paambaati/node-liftbridge/tree/master/grpc/generated).

2. The Go version of the client I'm developing (see [go-liftbridge](https://github.com/liftbridge-io/go-liftbridge)) can in fact `Subscribe` to the messages `Publish`ed by my Node.js debug script and print all the `Message`s correctly! I used the example subscribe program at [`liftbridge-io/go-liftbridge:example/lift-sub/subscribe.go@master`](https://github.com/liftbridge-io/go-liftbridge/blob/master/example/lift-sub/subscribe.go) to verify this 😮

3. I ran a full verbose trace of my debug script, and here's the output — https://gist.github.com/paambaati/7884b119eee47fafa436f74db8b59edc. I've padded the debug script's stdout with a lot of new lines so it is a little easier to separate them from the GRPC traces.

**Comment by paambaati** [comment]
After some more debugging, it looks like the issue is because the method parameters in the generated ` _pb.js` file are different from what's expected by protobuf.

```javascript
proto.proto.Message.deserializeBinaryFromReader = function(msg, reader) {
// ...
   case 7:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        // NOTICE THE NUMBER OF ARGUMENTS HERE -->>
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readBytes, null, "");
      });
      break;
// ...
}
```

Note that the call to `jspb.Map.deserializeBinary` only has **6** arguments in the generated `_pb.js` file, while https://github.com/protocolbuffers/protobuf/blob/8e6141a63dd2c54baff48d284bdede6a9ec56266/js/map.js#L474-L476 expects **7**. The 7th argument is the default for the map's `value` field.

Is this a bug, or is there a way to coerce the default value to an `""` from the `.proto` file? AFAIK, there's no default values in Proto3.

@murgatroid99 @TeBoring @BSBandme @xfxyjwf @haberman Thoughts?

**Comment by paambaati** [comment]
@anandolee @TeBoring @BSBandme @xfxyjwf @haberman Thoughts?

**Comment by paambaati** [comment]
@anandolee @TeBoring @BSBandme @xfxyjwf @haberman Thoughts? If you can help me find where the `_pb.js` generation from the `map.js` file happens, I will happily send a PR.

**Comment by paambaati** [comment]
@anandolee @TeBoring @BSBandme @xfxyjwf @haberman Thoughts? If you can help me find where the `_pb.js` generation from the `map.js` file happens, I will happily send a PR.

**Comment by paambaati** [comment]
@anandolee @TeBoring @BSBandme @xfxyjwf @haberman Thoughts? If you can help me find where the `_pb.js` generation from the `map.js` file happens, I will happily send a PR.

**Comment by paambaati** [comment]
https://github.com/protobufjs/protobuf.js/pull/1348 should fix this.
