### ISSUE TITLE
C# NullReference on FileDescriptor.CustomOptions

### ISSUE THREAD

**Issue by nagytech** [protocolbuffers/protobuf#6829]
**What version of protobuf and what language are you using?**
Version: master/3.10.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
OSX 10.14.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
.NET Core 3.0
Google.Protobuf 3.10.1
protoc 3.10.0

**What did you do?**

1. Create a new proto file

greet.proto
```proto
syntax = "proto3";

// toggle the commented line below to fix/break the reference
// option csharp_namespace = "protobuf_null_reference";

package Greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```

2. Compile it: `protoc --csharp_out=.  greet.proto`

3. Create a csharp project and reference the class

greet.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="google.protobuf" Version="3.10.1" />
  </ItemGroup>

</Project>

```

Program.cs
```csharp
using System.Diagnostics;

namespace protobuf_null_reference
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var descr = Greet.GreetReflection.Descriptor;
            Debug.Assert(descr != null);
            Debug.Assert(descr.CustomOptions == null);  // Exception thrown
            Debug.Assert(descr?.CustomOptions == null); // Would also throw exception
        }
    }

}
```

4. `dotnet run`

Steps to reproduce the behavior using .NET core template:
1. `dotnet new grpc`
2. Remove the custom `option` line from `Protos\greet.proto`
3. Add `using Greet;` where necessary to rejoin the references.
4. Add code from static Main above.
5. `dotnet run`

**What did you expect to see**

In C#, we can generally access a class instance property that is `null` without having an exception thrown.  Even if the `CustomOptions` property of the `FileDescriptor` is `null`, I should be able to check the value without having to catch an exception.  So, expected behaviour would be that `CustomOptions` should support null coalesced execution of the code.

**What did you see instead?**

Null reference exception when attempting to check if `CustomOptions` is null.

```
$ dotnet run 
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Protobuf.Reflection.FileDescriptor.get_CustomOptions()
   at protobuf_null_reference.Program.Main(String[] args) in /Users/jnagy/source/protobuf-null-reference/Program.cs:line 11
```

**Anything else we should know about your project / environment**

I've traced the issue to a missed coalesce within the `CustomOptions` accessor and will link the PR shortly.

**Comment by nagytech** [comment]
I just had a look at the 3.10.1 release, and thought I would update libprotoc to 3.10.1.  And, that apparently solved the issue.  But, now I'm getting #6822 all over the place.

So, I'll close this one and head over there.
