### ISSUE TITLE
libprotobuf.so asserts in static initialization

### ISSUE THREAD

**Issue by yurivict** [protocolbuffers/protobuf#6835]
Preloading this library with a simple empty executable (or with any executable) prints this:
```
$ LD_PRELOAD=/usr/local/lib/libprotobuf.so.20.0.2 ./m
[libprotobuf FATAL google/protobuf/generated_message_util.cc:818] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
Abort trap
```

protobuf-3.9.2,1 on FreeBSD 12

**Comment by yurivict** [comment]
```
Breakpoint 1, __cxa_throw (thrown_exception=0x800240080, tinfo=0x800a392a0 <typeinfo for google::protobuf::FatalException>, dest=0x8006efa00 <google::protobuf::FatalE[60/63]
n::~FatalException()>) at /usr/src/contrib/libcxxrt/exception.cc:793
(gdb) bt
#0  __cxa_throw (thrown_exception=0x800240080, tinfo=0x800a392a0 <typeinfo for google::protobuf::FatalException>, dest=0x8006efa00 <google::protobuf::FatalException::~FatalE
xception()>) at /usr/src/contrib/libcxxrt/exception.cc:793
#1  0x00000008006ef6e7 in google::protobuf::internal::LogMessage::Finish (this=0x7fffffffd7b8) at google/protobuf/stubs/common.cc:258
#2  0x00000008006eeb49 in google::protobuf::internal::LogFinisher::operator= (this=0x7fffffffd7b0, other=...) at google/protobuf/stubs/common.cc:266
#3  0x0000000800735915 in google::protobuf::internal::InitSCCImpl (scc=0x800a27168 <scc_info_Any_google_2fprotobuf_2fany_2eproto>) at google/protobuf/generated_message_util.
cc:817
#4  0x0000000800789d10 in google::protobuf::internal::InitSCC (scc=0x800a27168 <scc_info_Any_google_2fprotobuf_2fany_2eproto>) at ./google/protobuf/generated_message_util.h:
220
#5  0x00000008008972d8 in google::protobuf::(anonymous namespace)::AddDescriptorsImpl (table=0x800a39e68 <descriptor_table_google_2fprotobuf_2fany_2eproto>) at google/protob
uf/generated_message_reflection.cc:2373
#6  0x0000000800897294 in google::protobuf::internal::AddDescriptors (table=0x800a39e68 <descriptor_table_google_2fprotobuf_2fany_2eproto>) at google/protobuf/generated_mess
age_reflection.cc:2414
#7  0x0000000800788060 in __cxx_global_var_init () at google/protobuf/any.pb.cc:82
#8  0x0000000800789a29 in _GLOBAL__sub_I_any.pb.cc () from /usr/local/lib/libprotobuf.so.20
#9  0x000000080020e46e in objlist_call_init (list=<optimized out>, lockstate=<optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:2723
#10 0x000000080020d1d2 in _rtld (sp=<optimized out>, exit_proc=0x7fffffffe800, objp=0x7fffffffe808) at /usr/src/libexec/rtld-elf/rtld.c:765
```

**Comment by yurivict** [comment]
You can't throw exceptions in a global initialization context.

**Comment by elharo** [comment]
I'm surprised it's throwing exceptions ever. Google C++ tends not to use themm

**Comment by yurivict** [comment]
protobuf-3.17.3 doesn't have this problem any more.
