### ISSUE TITLE
js: omitted zero map values (as serialized by protobuf-c) cannot be deserialized

### ISSUE THREAD

**Issue by schiffermtq** [protocolbuffers/protobuf#7086]
Version: 3.11.2
Language: JavaScript
OS: Ubuntu 18.04

**What did you do?**
Take the following .proto definition:
```protobuf
syntax = "proto3";
message MapThing {
	map<string,uint64> values = 1;
}
```
and the message corresponding to the following JSON structure:
```json
{
	"values": {
		"foo": 0
	}
}
```

Depending on the protobuf implementation used, this message may be serialized in two different ways. I also used https://github.com/jmendeth/protobuf-inspector to look at the encoded data.

A) (Golang, C++)
```
0a 07 0a 03 66 6f 6f 10 00
```
```
root:
    1 <chunk> = message(1 <chunk> = "foo", 2 <varint> = 0)
```

B) (protobuf-c)
```
0a 05 0a 03 66 6f 6f
```
```
root:
    1 <chunk> = message(1 <chunk> = "foo")
```

1. Take the message B) and deserialize using JS protobuf implementation (google-protobuf):
```js
const {MapThing} = require('./foo_pb');
const data = Uint8Array.from([0x0a, 0x05, 0x0a, 0x03, 0x66, 0x6f, 0x6f])
MapThing.deserializeBinary(data);
```
2. Library will fail with an assertion:
```
/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:81
jspb.BinaryConstants.TWO_TO_32=4294967296;jspb.BinaryConstants.TWO_TO_52=4503599627370496;jspb.BinaryConstants.TWO_TO_63=0x7fffffffffffffff;jspb.BinaryConstants.TWO_TO_64=1.8446744073709552E19;jspb.BinaryConstants.ZERO_HASH="\x00\x00\x00\x00\x00\x00\x00\x00";goog.dom={};goog.dom.NodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};goog.debug={};goog.debug.Error=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,goog.debug.Error);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.reportErrorToServer=!0};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){goog.debug.Error.call(this,goog.asserts.subs_(a,b));this.messagePattern=a};goog.inhe
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.doAssertFailure_ (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:82:257)
    at Object.goog.asserts.assert (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:83:83)
    at Function.jspb.Map.deserializeBinary (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:411:272)
    at /home/schifferm/em/test/pbjs/test_pb.js:467:18
    at jspb.BinaryReader.readMessage (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:384:329)
    at proto.GDR.deserializeBinaryFromReader (/home/schifferm/em/test/pbjs/test_pb.js:466:14)
    at jspb.BinaryReader.readMessage (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:384:329)
    at Function.jspb.Map.deserializeBinary (/home/schifferm/em/test/pbjs/node_modules/google-protobuf/google-protobuf.js:411:202)
    at /home/schifferm/em/test/pbjs/test_pb.js:110:18
```

Message A) can be deserialized without issues.

It is unclear to me whether serialization B) is actually valid or if protobuf-c is at fault, but the other implementations I tested (Golang, Python) can read it without issues.

**Comment by schiffermtq** [comment]
As it turns out, the issue was not in the google-protobuf JS library, but in the generated code - and my *protoc* was still on version 3.6.1, as I installed it from a Ubuntu APT repo.

With protoc from the protobuf master, the issue disappears. I assume it was fixed in 4f02f056b5.
