### ISSUE TITLE
C# - Unexpected end of document in state exception when calling Parse

### ISSUE THREAD

**Issue by fagnercarvalho** [protocolbuffers/protobuf#7245]
Protobuf version: v3.11.4.
Language: C#
OS: Windows 10
.NET version: .NET Core 3.1

- Run the DialogFlow .NET client sample for .NET Core in https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html;

I'm getting two exceptions when calling the `Parse` method:

```
Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
```

This seems to be happening because the `Parse` method is synchronous. Do you have any plans for when the async version of this method is going to developed?

Also, if I work around this issue I get:

```
Unexpected end of document in state: StartOfDocument

   at Google.Protobuf.JsonTokenizer.JsonTextTokenizer.ValidateState(State validStates, String errorPrefix)
   at Google.Protobuf.JsonTokenizer.JsonTextTokenizer.NextImpl()
   at Google.Protobuf.JsonTokenizer.Next()
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, TextReader jsonReader)
   at Google.Protobuf.JsonParser.Parse[T](TextReader jsonReader)
```

Here is the JSON I'm trying to parse:

```
{
  "responseId": "55727bcc-7d89-4fd5-8c1f-20f9e4d8d19c-7f245a81",
  "queryResult": {
    "queryText": "Meu nome é Fagner",
    "parameters": {
      "name": "Fagner"
    },
    "allRequiredParamsPresent": true,
    "fulfillmentMessages": [{
      "text": {
        "text": [""]
      }
    }],
    "outputContexts": [{
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/actions_capability_account_linking",
      "parameters": {
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }, {
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/actions_capability_audio_output",
      "parameters": {
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }, {
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/actions_capability_media_response_audio",
      "parameters": {
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }, {
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/actions_capability_screen_output",
      "parameters": {
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }, {
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/google_assistant_input_type_voice",
      "parameters": {
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }, {
      "name": "projects/<project id>/agent/sessions/<session id>/contexts/__system_counters__",
      "lifespanCount": 1,
      "parameters": {
        "no-input": 0.0,
        "no-match": 0.0,
        "name": "Fagner",
        "name.original": "Fagner"
      }
    }],
    "intent": {
      "name": "projects/<project id>/agent/intents/<session id>",
      "displayName": "greetings-intent"
    },
    "intentDetectionConfidence": 1.0,
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "source": "google",
    "version": "2",
    "payload": {
      "user": {
        "locale": "en-US",
        "lastSeen": "2020-02-22T23:44:35Z",
        "userVerificationStatus": "VERIFIED"
      },
      "conversation": {
        "conversationId": "<conversation id>",
        "type": "ACTIVE",
        "conversationToken": "[\"__system_counters__\"]"
      },
      "inputs": [{
        "intent": "actions.intent.TEXT",
        "rawInputs": [{
          "inputType": "VOICE",
          "query": "Meu nome é Fagner"
        }],
        "arguments": [{
          "name": "text",
          "rawText": "Meu nome é Fagner",
          "textValue": "Meu nome é Fagner"
        }]
      }],
      "surface": {
        "capabilities": [{
          "name": "actions.capability.ACCOUNT_LINKING"
        }, {
          "name": "actions.capability.AUDIO_OUTPUT"
        }, {
          "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
        }, {
          "name": "actions.capability.SCREEN_OUTPUT"
        }]
      },
      "isInSandbox": true,
      "availableSurfaces": [{
        "capabilities": [{
          "name": "actions.capability.WEB_BROWSER"
        }, {
          "name": "actions.capability.AUDIO_OUTPUT"
        }, {
          "name": "actions.capability.SCREEN_OUTPUT"
        }]
      }],
      "requestType": "SIMULATOR"
    }
  },
  "session": "projects/<project id>/agent/sessions/<session id>"
}
```

This was reported in the DialogFlow .NET repo too. The link for the issue: https://github.com/googleapis/google-cloud-dotnet/issues/4407.

**Comment by jskeet** [comment]
For diagnostic purposes, if you call `ReadToEnd()` on the reader, what happens? Is it possible something else is reading the request stream first? (That would explain this error.)

**Comment by fagnercarvalho** [comment]
`ReadToEnd()` is working fine.

Moreover, I can't reproduce the issue in `Parse` anymore. I was reading the stream first by calling `ReadToEndAsync` for testing purposes (and this was a silly mistake) but I only started calling `ReadToEndAsync` after getting the "Unexpected end of document in state: StartOfDocument" in `Parse` so I really not sure why I can't reproduce this anymore.

Since you said in https://github.com/googleapis/google-cloud-dotnet/issues/4407 that the protobuf team is working on the asynchronous methods I believe we can close this as a non-issue?

**Comment by jskeet** [comment]
Yes, let's close this as a non-issue for now.
