### ISSUE TITLE
UnsupportedOperationException in Android64MemoryAccessor.getByte

### ISSUE THREAD

**Issue by eoger** [protocolbuffers/protobuf#7422]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: Java

Using `com.google.protobuf:protobuf-javalite:3.11.4` and `com.google.protobuf:protoc:3.11.4` plugins.

**What operating system (Linux, Windows, ...) and version?**

Android

I'm getting an exception trying to parse a proto2 message:

```
java.lang.UnsupportedOperationException
    at com.google.protobuf.UnsafeUtil$Android64MemoryAccessor.getByte(UnsafeUtil.java:716)
    at com.google.protobuf.UnsafeUtil.getByte(UnsafeUtil.java:255)
    at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readRawVarint32(CodedInputStream.java:1719)
    at com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder.readTag(CodedInputStream.java:1337)
    at com.google.protobuf.CodedInputStreamReader.getFieldNumber(CodedInputStreamReader.java:81)
    at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3862)
    at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3844)
    at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1532)
    at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1695)
    at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1688)
```

What I have noticed is the regression happens from `protobuf-javalite` version 3.10.0 onwards, 3.9.2 doesn't have this bug.

[Android64MemoryAccessor#getByte](https://github.com/protocolbuffers/protobuf/blob/f494cb222d1b10a56273c07a3f5991b4b107958b/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L716) gets used, but the implementation throws by default. Maybe `getByte` shouldn't get used at all?

**Comment by eoger** [comment]
I have also noticed that `Android64MemoryAccessor` and friends [got introduced between 3.9.2 and 3.10.0](https://github.com/protocolbuffers/protobuf/compare/v3.9.2...v3.10.0#diff-6c9e043b78f78efc096211703bb7fa4a).

**Comment by eoger** [comment]
I think I figured it out: I was feeding [GeneratedMessageLite#parseFrom](https://github.com/protocolbuffers/protobuf/blob/2db0e9812a8774f5266370b7a6eae4e4e5a2cdd0/java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java#L1690-L1693) with an [`UnsafeDirectNioDecoder`](https://github.com/protocolbuffers/protobuf/blob/e667bf6eaaa2fb1ba2987c6538df81f88500d030/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L186). However, on Android [`supportsUnsafeByteBufferOperations`](https://github.com/protocolbuffers/protobuf/blob/2228af689f5ff4d929c85079025c49f6945b136a/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L387-L389) should actually return `false` because the AndroidXMemoryAccessors [do not support unsafe ByteBuffer operations](https://github.com/protocolbuffers/protobuf/blob/2228af689f5ff4d929c85079025c49f6945b136a/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L714-L742).

I will post a PR correcting the issue.

**Comment by elharo** [comment]
That code has been refactored a lot. I think this is fixed, but if you still see it comment and I'll reopen.
