### ISSUE TITLE
C# ARM64

### ISSUE THREAD

**Issue by turowicz** [protocolbuffers/protobuf#7544]
I get the following error when loading the library on an ARM64 device:

```
Error loading native library "/app/libgrpc_csharp_ext.x64.so". 
System.IO.IOException: Error loading native library "/app/libgrpc_csharp_ext.x64.so". 
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
```

**Comment by turowicz** [comment]
Any idea how can I compile it so it loads the `.arm64.so` file?

**Comment by turowicz** [comment]
Wrong repository :D
