### ISSUE TITLE
error: while installing from setup.py : is = enum_type_wrapper.EnumTypeWrapper(_IS)

### ISSUE THREAD

**Issue by AnveshakR** [protocolbuffers/protobuf#7659]
**What version of protobuf and what language are you using?**
Version: 3.11.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Pop!_OS 20.04 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.10

**What did you do?**
1) in protobuf-3.11.0/python
2) python setup.py test

**What did you see instead?**
running test
running egg_info
creating protobuf.egg-info
writing protobuf.egg-info/PKG-INFO
writing dependency_links to protobuf.egg-info/dependency_links.txt
writing namespace_packages to protobuf.egg-info/namespace_packages.txt
writing requirements to protobuf.egg-info/requires.txt
writing top-level names to protobuf.egg-info/top_level.txt
writing manifest file 'protobuf.egg-info/SOURCES.txt'
reading manifest file 'protobuf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'google/protobuf/internal/*.proto'
warning: no previously-included files matching '*_test.py' found under directory 'google'
warning: no previously-included files matching '*_test.proto' found under directory 'google'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'protobuf.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 284, in <module>
    ext_modules=ext_module_list,
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/mustangboss8055/.pyenv/versions/3.6.10/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/mustangboss8055/Documents/protobuf-3.11.0/python/google/protobuf/internal/descriptor_pool_test2_pb2.py", line 16, in <module>
    from google.protobuf.internal import more_messages_pb2 as google_dot_protobuf_dot_internal_dot_more__messages__pb2
  File "/home/mustangboss8055/Documents/protobuf-3.11.0/python/google/protobuf/internal/more_messages_pb2.py", line 48
    is = enum_type_wrapper.EnumTypeWrapper(_IS)
     ^
SyntaxError: invalid syntax

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by AnveshakR** [comment]
its been 4 damned years
