### ISSUE TITLE
npm install protobuf fails to install the module

### ISSUE THREAD

**Issue by protofolius** [protocolbuffers/protobuf#7753]
**What version of protobuf and what language are you using?**
Version: protobuf 0.11.1 , nodejs 8.10.0 , npm 3.5.2

**What operating system (Linux, Windows, ...) and version?**
ubuntu 18.04 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
python

**What did you do?**
npm install protobuf

**What did you expect to see**
a proper compile and installation of the module

**What did you see instead?**
`protobuf_for_node.target.mk:101: recipe for target 'Release/obj.target/protobuf_for_node/protobuf_for_node.o' failed
make: *** [Release/obj.target/protobuf_for_node/protobuf_for_node.o] Error 1
make: Leaving directory '/usr/share/npm/node_modules/protobuf/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-112-generic
gyp ERR! command "/usr/bin/node" "/usr/share/npm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/share/npm/node_modules/protobuf
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm@3.5.2 /usr/share/npm
├── line-reader-sync@0.1.0  extraneous
└── sync-request@6.1.0  extraneous

npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "protobuf"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! protobuf@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobuf@0.11.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/npm/node_modules/npm-debug.log
`

**Anything else we should know about your project / environment**
npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "bugs" "protobuf"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by protofolius** [comment]
[logfile.txt](https://github.com/protocolbuffers/protobuf/files/4977348/logfile.txt)
