### ISSUE TITLE
UnknownField.MergeFrom(UnknownField) does not properly handle default input

### ISSUE THREAD

**Issue by maxbl4** [protocolbuffers/protobuf#7797]
**What version of protobuf and what language are you using?**
Version: 3.11.3. but the issue is the same in master
Language: C#

**What operating system (Linux, Windows, ...) and version? 
Windows 2004

**What runtime / compiler are you using (e.g., python version or gcc version)**
.Net core 3.1.302

**What did you do?**
```
var f = new UnknownField();
f.MergeFrom(new UnknownField());
```
Expected: operation succeded
Actual: Exception is thrown
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Protobuf.UnknownField.AddAll[T](List`1 current, IList`1 extras)
   at Google.Protobuf.UnknownField.MergeFrom(UnknownField other)
   at Google.Protobuf.UnknownFieldSet.MergeField(Int32 number, UnknownField field)
   at Google.Protobuf.UnknownFieldSet.MergeFrom(UnknownFieldSet other)
   at Google.Protobuf.UnknownFieldSet.MergeFrom(UnknownFieldSet unknownFields, UnknownFieldSet other)
```
This is because of bug in AddAll method, it does not check the Other list for null, but check for .Count right from the start
https://github.com/protocolbuffers/protobuf/blob/389bd06d0a637d3fd1aded7de59a12ed8f83baad/csharp/src/Google.Protobuf/UnknownField.cs#L218

**Comment by CauhxMilloy** [comment]
This would be fixed in https://github.com/protocolbuffers/protobuf/pull/7328.
