### ISSUE TITLE
Android L: No virtual method getBoolean(Ljava/lang/Object;J)Z in class Lsun/misc/Unsafe

### ISSUE THREAD

**Issue by tundratier** [protocolbuffers/protobuf#7867]
**What version of protobuf and what language are you using?**
Version: 3.8.0 (via gradle plugin com.google.protobuf:protoc:3.8.0)
Language: Java (Android)

**What operating system (Linux, Windows, ...) and version?**
Execution: Android L (API 21)
Compiler: Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
Gradle Integration configured for javalite compiler:
- Plugin: com.google.protobuf:protobuf-gradle-plugin:0.8.13
- Compiler: com.google.protobuf:protoc:3.8.0
- Runtime Dependency: com.google.protobuf:protobuf-javalite:3.9.1

**What did you do?**
1. Decode any message on Android L

**What did you expect to see**
That the message is correctly decoded.

**What did you see instead?**
Runtime Error:
```
09-02 09:34:07.103 7608-7631/my.package.com E/Tag: redacted
NoSuchMethodError: No virtual method getBoolean(Ljava/lang/Object;J)Z in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
        at com.google.protobuf.UnsafeUtil$JvmMemoryAccessor.getBoolean(UnsafeUtil.java:615)
        at com.google.protobuf.UnsafeUtil.getBoolean(UnsafeUtil.java:139)
        at com.google.protobuf.MessageSchema.isFieldPresent(MessageSchema.java:5777)
        at com.google.protobuf.MessageSchema.getSerializedSizeProto3(MessageSchema.java:2036)
        at com.google.protobuf.MessageSchema.getSerializedSize(MessageSchema.java:1411)
        at com.google.protobuf.GeneratedMessageLite.getSerializedSize(GeneratedMessageLite.java:272)
        at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:69)
```

**Comment by tundratier** [comment]
I could isolate the issue to bool fields.

This does not work:
```
message DataModel {
    bool foo = 1;
}
```

This does work:
```
message DataModel {
    string foo = 1;
}
```

**Comment by tundratier** [comment]
I just found the release 3.13.0 of the protobuf-javalite library fixes the issue.
Please update your documentation on https://github.com/protocolbuffers/protobuf/blob/v3.9.0/java/lite.md accordingly.

**Comment by Zhang-person** [comment]
I meet the same problem. and thanks for your answer!
