### ISSUE TITLE
PHP: Assertion Failed / Segmentation fault on 3.17.1

### ISSUE THREAD

**Issue by zeriyoshi** [protocolbuffers/protobuf#8659]
**What version of protobuf and what language are you using?**
Version: 3.17.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Debian GNU/Linux 10
Alpine Linux 3.11

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.3.25 (alpine)
PHP 7.4.19 (alpine / debian)

**What did you do?**

## Google's officially Spanner example for PHP:

1. install gRPC extension (version: 1.38.0)
2. install protobuf extension (version: 3.17.1)
3. Setup and start Spanner emulator.
4. Try Google's officially Cloud Spanner sample for PHP (https://cloud.google.com/spanner/docs/getting-started/php)
5. get ABRT

## OSS Spanner codes:

1. Execute laravel-spanner test (with spanner-emulator)

```
$ git clone https://github.com/colopl/laravel-spanner
$ cd laravel-spanner
$ make build
$ make test
```

2. get SYSABRT

## SEGV on REAL Spanner environment.
(SEGV only appear in Real Spanner environments currently.)

1. clone and install workaround repo: https://github.com/zeriyoshi/protobuf/tree/fix_invalid_pointer_access
2. Execute REAL Spanner queries.
3. get SYSSEGV

**What did you expect to see**
non SEGV/ABRT

**What did you see instead?**
```
Thread 1 "php" received signal SIGSEGV, Segmentation fault.
0x00007ffff6b5c191 in _upb_msg_getraw (msg=0x60adecd3, f=f@entry=0x5555565a2730) at /root/protobuf/php/ext/google/protobuf/php-upb.h:1200
1200      return field->label >= UPB_LABEL_REPEATED;
```

```
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

php: /tmp/pear/temp/protobuf/php-upb.c:4942: upb_fielddef_default: Assertion `!upb_fielddef_issubmsg(f)' failed.
Aborted
ERROR: 134
make: *** [test] Error 134
```

**Anything else we should know about your project / environment**
~~We have found the cause and will submit a patch later.~~

**Comment by zeriyoshi** [comment]
crash log from gdb:
```
Thread 1 "php" received signal SIGSEGV, Segmentation fault.
0x00007ffff6b5c191 in _upb_msg_getraw (msg=0x60adecd3, f=f@entry=0x5555565a2730) at /root/protobuf/php/ext/google/protobuf/php-upb.h:1200
1200      return field->label >= UPB_LABEL_REPEATED;
```

**Comment by zeriyoshi** [comment]
backtrace:
```
(gdb) backtrace
#0  0x00007ffff6bb1191 in _upb_msg_getraw (msg=0x143ea8369d170b7e, f=f@entry=0x555556562110) at /root/protobuf/php/ext/google/protobuf/php-upb.h:1200
#1  0x00007ffff6bb488a in upb_msg_get (msg=<optimized out>, f=f@entry=0x555556562110) at /root/protobuf/php/ext/google/protobuf/php-upb.c:6788
#2  0x00007ffff6ba3578 in Message_get (intern=intern@entry=0x7fffdbc583c0, f=0x555556562110, rv=rv@entry=0x7ffff7622f60) at /root/protobuf/php/ext/google/protobuf/message.c:137
#3  0x00007ffff6ba35fb in Message_read_property (obj=<optimized out>, member=<optimized out>, type=<optimized out>, cache_slot=<optimized out>, rv=0x7ffff7622f60) at /root/protobuf/php/ext/google/protobuf/message.c:342
#4  0x0000555555a00aaf in execute_ex ()
#5  0x00005555559a75d2 in zend_generator_resume ()
```

**Comment by zeriyoshi** [comment]
PHP 7.3.28 (latest 7.3.x) It was debug build and SEGV backtrace was output by gdb:

```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...
(gdb) run quickstart.php
Starting program: /usr/local/bin/php quickstart.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4c16700 (LWP 369164)]
[New Thread 0x7ffff4415700 (LWP 369165)]
[New Thread 0x7ffff3c14700 (LWP 369166)]
php: /home/vagrant/protobuf/php/ext/google/protobuf/php-upb.c:4942: upb_fielddef_default: Assertion `!upb_fielddef_issubmsg(f)' failed.

Thread 1 "php" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7743859 in __GI_abort () at abort.c:79
#2  0x00007ffff7743729 in __assert_fail_base (fmt=0x7ffff78d9588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff4d1a7e8 "!upb_fielddef_issubmsg(f)", 
    file=0x7ffff4d17c38 "/home/vagrant/protobuf/php/ext/google/protobuf/php-upb.c", line=4942, function=<optimized out>) at assert.c:92
#3  0x00007ffff7754f36 in __GI___assert_fail (assertion=0x7ffff4d1a7e8 "!upb_fielddef_issubmsg(f)", file=0x7ffff4d17c38 "/home/vagrant/protobuf/php/ext/google/protobuf/php-upb.c", line=4942, 
    function=0x7ffff4d1be20 <__PRETTY_FUNCTION__.9584> "upb_fielddef_default") at assert.c:101
#4  0x00007ffff4d068bc in upb_fielddef_default (f=0x555556706520) at /home/vagrant/protobuf/php/ext/google/protobuf/php-upb.c:4942
#5  0x00007ffff4d0bf8c in upb_msg_get (msg=0x555556562408, f=0x555556706520) at /home/vagrant/protobuf/php/ext/google/protobuf/php-upb.c:6791
#6  0x00007ffff4ceb56f in Message_get (intern=0x7ffff2e3c880, f=0x555556706520, rv=0x7fffffff9be0) at /home/vagrant/protobuf/php/ext/google/protobuf/message.c:137
#7  0x00007ffff4cf3735 in zim_google_protobuf_Value_getStructValue (execute_data=0x7ffff56203a0, return_value=0x7ffff5620050) at /home/vagrant/protobuf/php/ext/google/protobuf/wkt.inc:1309
#8  0x0000555555c69926 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /home/vagrant/php-src/Zend/zend_vm_execute.h:1106
#9  0x0000555555cd719c in execute_ex (ex=0x7ffff2e7d580) at /home/vagrant/php-src/Zend/zend_vm_execute.h:55527
#10 0x0000555555c411ca in zend_generator_resume (orig_generator=0x7ffff2e7d100) at /home/vagrant/php-src/Zend/zend_generators.c:809
#11 0x0000555555c41448 in zend_generator_ensure_initialized (generator=0x7ffff2e7d100) at /home/vagrant/php-src/Zend/zend_generators.c:855
#12 0x0000555555c415a5 in zim_Generator_valid (execute_data=0x7ffff561f500, return_value=0x7ffff561f4f0) at /home/vagrant/php-src/Zend/zend_generators.c:900
#13 0x0000555555c69926 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /home/vagrant/php-src/Zend/zend_vm_execute.h:1106
#14 0x0000555555cd719c in execute_ex (ex=0x7ffff561f460) at /home/vagrant/php-src/Zend/zend_vm_execute.h:55527
#15 0x0000555555be627d in zend_call_function (fci=0x7fffffffa200, fci_cache=0x7fffffffa1e0) at /home/vagrant/php-src/Zend/zend_execute_API.c:756
#16 0x0000555555a80c6b in zif_call_user_func_array (execute_data=0x7ffff561f3f0, return_value=0x7ffff561f350) at /home/vagrant/php-src/ext/standard/basic_functions.c:4942
#17 0x0000555555c68f85 in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /home/vagrant/php-src/Zend/zend_vm_execute.h:896
#18 0x0000555555cd717a in execute_ex (ex=0x7ffff2e4ac00) at /home/vagrant/php-src/Zend/zend_vm_execute.h:55519
#19 0x0000555555c411ca in zend_generator_resume (orig_generator=0x7ffff2e0b380) at /home/vagrant/php-src/Zend/zend_generators.c:809
#20 0x0000555555c41448 in zend_generator_ensure_initialized (generator=0x7ffff2e0b380) at /home/vagrant/php-src/Zend/zend_generators.c:855
#21 0x0000555555c414a1 in zend_generator_rewind (generator=0x7ffff2e0b380) at /home/vagrant/php-src/Zend/zend_generators.c:864
#22 0x0000555555c425c3 in zend_generator_iterator_rewind (iterator=0x7ffff3228f80) at /home/vagrant/php-src/Zend/zend_generators.c:1157
#23 0x0000555555c67515 in zend_fe_reset_iterator (array_ptr=0x7ffff561f0e0, by_ref=0) at /home/vagrant/php-src/Zend/zend_execute.c:3267
#24 0x0000555555cb7fe7 in ZEND_FE_RESET_R_SPEC_CV_HANDLER () at /home/vagrant/php-src/Zend/zend_vm_execute.h:37546
#25 0x0000555555cdbd04 in execute_ex (ex=0x7ffff561f030) at /home/vagrant/php-src/Zend/zend_vm_execute.h:59367
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x0000555555cddbe1 in zend_execute (op_array=0x7ffff5681300, return_value=0x0) at /home/vagrant/php-src/Zend/zend_vm_execute.h:60935
#27 0x0000555555bfe788 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /home/vagrant/php-src/Zend/zend.c:1568
#28 0x0000555555b6220f in php_execute_script (primary_file=0x7fffffffcd50) at /home/vagrant/php-src/main/main.c:2637
#29 0x0000555555ce09f3 in do_cli (argc=2, argv=0x555556551f60) at /home/vagrant/php-src/sapi/cli/php_cli.c:1000
#30 0x0000555555ce1bee in main (argc=2, argv=0x555556551f60) at /home/vagrant/php-src/sapi/cli/php_cli.c:1396
```

**Comment by haberman** [comment]
Confirmed, thanks for the thorough report. I'll have a fix for this shortly.

**Comment by zeriyoshi** [comment]
I was able to confirm the fix. Thanks!
