### ISSUE TITLE
Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by CoolCoderSJ** [protocolbuffers/protobuf#8733]
**What version of protobuf and what language are you using?**
Version: master/v3.17
Language: Python

**What operating system (Linux, Windows, ...) and version?**: Ubuntu 18.04.5 AND Windows 7

**What runtime / compiler are you using (e.g., python version or gcc version)**: Python 3.8.2

**What did you do?**
1. Go to the Releases Page and download the Windows compiler.
2. Add the /bin folder to PATH
3. Use the compiler to compile /include/google/api.proto into ` api_pb2.py `
4. This file outputs an error on Ubuntu machines, but not Windows

**What did you expect to see**
The file should import properly

**What did you see instead?**
```
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/snow_pyrepl/__init__.py", line 8, in <module>
    from snow_pyrepl.api_pb2 import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/snow_pyrepl/api_pb2.py", line 31, in <module>
    _descriptor.EnumValueDescriptor(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 694, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
Previous solutions say to rename the file to ` api_pb2.py `, however my file is already named that.

**Comment by CoolCoderSJ** [comment]
Compiling with Stackless Python and uninstalling/installing protobuf from PyPI about a 100 times seemed to have worked
