### ISSUE TITLE
Kokoro job for continuous benchmarks is broken on master by recent JS changes.

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#8747]
This is the first failing build:
https://source.cloud.google.com/results/invocations/7416b136-a366-472c-ad3b-0890c6fb9493/targets (from Jun 2 2021)

The rootcause is probably this PR:
https://github.com/protocolbuffers/protobuf/pull/8610 (it was green before and started failing right after it got merged).

@kjin @TeBoring  can you please help fixing this?

**Comment by jtattermusch** [comment]
CC @fowles

**Comment by jtattermusch** [comment]
```
/tmpfs/src/github/protobuf/js/node_modules/yargs-parser/build/index.cjs:997
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/tmpfs/src/github/protobuf/js/node_modules/yargs-parser/build/index.cjs:997:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmpfs/src/github/protobuf/js/node_modules/yargs/build/index.cjs:2855:16)
    at Module._compile (module.js:573:30)

[15:34:35] '<anonymous>' errored after 309 ms
[15:34:35] Error: Command failed: sh -c ./node_modules/.bin/closure-make-deps --closure-path=. --file=node_modules/google-closure-library/closure/goog/deps.js binary/arith.js binary/constants.js binary/decoder.js binary/encoder.js binary/reader.js binary/utils.js binary/writer.js debug.js map.js message.js node_loader.js test_bootstrap.js > deps.js
/tmpfs/src/github/protobuf/js/node_modules/yargs-parser/build/index.cjs:997
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/tmpfs/src/github/protobuf/js/node_modules/yargs-parser/build/index.cjs:997:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmpfs/src/github/protobuf/js/node_modules/yargs/build/index.cjs:2855:16)
    at Module._compile (module.js:573:30)

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[15:34:35] 'deps' errored after 393 ms
[15:34:35] 'test_closure' errored after 477 ms
[15:34:35] 'test' errored after 479 ms
npm ERR! Test failed.  See above for more details.
```

**Comment by perezd** [comment]
are we running an old version of nodejs as part of the build/run script?

**Comment by jtattermusch** [comment]
> are we running an old version of nodejs as part of the build/run script?

yes, perhaps. I wasn't able to find the place where node gets installed in the benchmarks job.
What is the range of supported versions at this point?

**Comment by kjin** [comment]
I saw that @acozzette rebuilt the docker image in #8661. My suspicion is that npm wasn't actually updated because the `npm` package in the debian apt repository itself is obsolete, and doesn't get updated at all. This is probably also true of Node.js -- an outdated version gets installed as a dependency of outdated npm.

To fix this, the Dockerfile should not install npm via apt-get, and instead install Node.js (npm should come with it) in a different way. [NodeSource provides distributions for Debian/Ubuntu](https://github.com/nodesource/distributions/blob/master/README.md#deb), but I'm not sure what the best practice is for getting these distributions in the Docker image.
