### ISSUE TITLE
[python] enums with field named `DESCRIPTOR` generate broken python

### ISSUE THREAD

**Issue by nipunn1313** [protocolbuffers/protobuf#8803]
**What did you do?**

Generate
```
package p;

enum E {
    FOO = 0;
    BAR = 1
    DESCRIPTOR = 2;
}
```
Then in a shell
```
>>> from p_pb2 import E
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "p_pb2.py", line 419, in <module>
    DESCRIPTOR.message_types_by_name['E'] = _E
AttributeError: 'int' object has no attribute 'message_types_by_name'
```

**What did you expect to see**

Either protoc should failfast, or the generated code should work in some capacity.

**Comment by nipunn1313** [comment]
for some detail, what's happening here is that the module level descriptor for `p` (`p.DESCRIPTOR`) is getting overwritten with a global enum variable `DESCRIPTOR = 2`, hence the error above.

I can think of a couple options

- Make it illegal to define a field named DESCRIPTOR, since it seems like it would break generated code across several languages. Not sure how practical this is.
- Produce a warning when generating python code with DESCRIPTOR, and suppress generation of `DESCRIPTOR = 2` line.
