### ISSUE TITLE
InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field

### ISSUE THREAD

**Issue by codefish1** [protocolbuffers/protobuf#8995]
We are loading a schema descriptor file using

`final var descriptor = FileDescriptorProto.parseFrom(inputStream)`

the input stream is streaming from an S3 implementation but I don't think thats causing it.

This worked fine on 3.17.2 however the patch for 3.17.3 has broken it.   I've tracked it down to this line

https://github.com/protocolbuffers/protobuf/blob/909a0f36a10075c4b4bc70fdee2c7e32dd612a72/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L2407

What appears to happen is it's got to the end of the file and pops the old limit back on, so the final check then throws the error.  Since it's reached the end of the file but we've not hit the limit yet

```
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:107)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2427)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1281)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1201)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4888)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4882)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:339)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2308)
```

**Comment by perezd** [comment]
are you able to provide a reproducer?

**Comment by codefish1** [comment]
Spent some time trying to create a producer I would be able to share and worked out that if I change

`final var descriptor = FileDescriptorProto.parseFrom(schema);`
to
`final var descriptor = DescriptorProtos.FileDescriptorSet.parseFrom(inputStream).getFile(0);`

that it works.  Obviously I need a better way than just blindly assuming the first file is there and the one I want.
