### ISSUE TITLE
Enums are failing during runtime - java.lang.RuntimeException: Generated message class missing method "valueOf".

### ISSUE THREAD

**Issue by ravenspree** [protocolbuffers/protobuf#9079]
**What version of protobuf and what language are you using?**
Version: 3.15.3
Language:Java

**What runtime / compiler are you using
- Java

**What did you do?**

1. Created a grpc service, exposing a simple GET API with an enum in the request and response object
2. Created a REST client that can convert the grpc response into JSON response using JsonFormat class from `com.google.protobuf.util.JSONFormat` from `protobuf-java-util-3.15.3`

The service is working fine in local mac machine but fails to run in the cloud kubernetes env with the below error on hitting the endpoint. 

This is the simple enum 

```enum ResponseStatus {
  SUCCESS = 0;
  FAILED = 1;
  PARTIAL = 2;
}

message Response {
  ResponseStatus responseStatus = 1;
  string message = 2;
  int32 errorCode = 3;
}

rpc TestGetEndpoint(TestGetEndpointRequest)
      returns (TestGetEndpointResponse);

at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularEnumFieldAccessor.<init>(GeneratedMessageV3.java:2747)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1973)
at com.ss.Response.internalGetFieldAccessorTable(Response.java:98)
at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762)
at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:371)
at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:381)
at com.ss.util.ProtoJsonUtil.toJson(ProtoJsonUtil.java:20)
at com.ss.client.GalleryClient.testGalleryEndpoint(GalleryClient.java:65)
at java.lang.reflect.Method.invoke(Method.java:566)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
... 17 more
Caused by: java.lang.NoSuchMethodException: com.ss.ResponseStatus.valueOf(com.google.protobuf.Descriptors$EnumValueDescriptor)
at java.lang.Class.getMethod(DynamicHub.java:1121)
at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
```

I expect the run time not to look for `valueOf` method instead of `forNumber` in the generated proto classes as it is deprecated and it is not longer required. 

Every time I hit the grpc service endpoint that has an enum in the request, the java runtime is expecting valueOf() method from enum

I am running this grpc service in Quarkus framework

**Comment by perezd** [comment]
Can you confirm you are using the exact same runtime on both environments? These potentially feels like a mismatch between a compiler's generated output and a runtime not matching.

**Comment by perezd** [comment]
@ravenspree Yes, potentially. This is especially possible if it works in one environment and not another.

**Comment by elharo** [comment]
I'm not sure this is a gRPC problem. I suspect @perezd 's first suggestion is correct. There are two environments here and the remote environment has an older version of protobuf than the local. I'm not sure there's enough details in this report to fully analyze this, but it should be possible for the reporter to fix this by syncing the versions between the environments.
