### ISSUE TITLE
Is FileDescriptorSet functionality available in Ruby?

### ISSUE THREAD

**Issue by i0jupiter** [protocolbuffers/protobuf#9142]
**What version of protobuf and what language are you using?**
Version: 3.17.x
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
OSX, 11.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby-2.6.3

**What did you do?**
1. Wrote a proto
2. Generated code along using `--descriptor_set_out=set.txt`
3. Tried to create a new `FileDecriptorSet`. 

**What did you expect to see**
A new `FileDescriptorSet` object.

**What did you see instead?**
```
2.6.3 :114 > fl = File.open("<full path to set.txt>", "r")
 => #<File:path/to/set.txt>

2.6.3 :115 > Google::Protobuf::FileDescriptor.new(file: fl, package: "tutorial")
Traceback (most recent call last):
       16: from ~/.rvm/gems/ruby-2.6.3/bin/bundle:23:in `<main>'
       15: from ~/.rvm/gems/ruby-2.6.3/bin/bundle:23:in `load'
       14: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
       13: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
       12: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
       11: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in `start'
       10: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        9: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
        8: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        7: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        6: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        5: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:494:in `console'
        4: from ~/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/cli/console.rb:19:in `run'
        3: from (irb):115
        2: from (irb):115:in `new'
        1: from (irb):115:in `initialize'
ArgumentError (wrong number of arguments (given 1, expected 3))
```

**Anything else we should know about your project / environment**
Is this API supposed to be available In Ruby or Python or Go?

**Comment by i0jupiter** [comment]
For anyone who stumbles on this, part of the solution is in the mailing list post.
