### ISSUE TITLE
CI failures for Ruby (irb gem missing)

### ISSUE THREAD

**Issue by perezd** [protocolbuffers/protobuf#9303]
Found in CI logs:

```
cd tmp/x86_64-darwin/protobuf_c/2.4.0
/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/google/protobuf_c/extconf.rb
/Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:276:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'irb (~> 1.1, < 1.2.0)' in locally installed gems. (Bundler::GemNotFound)
The source contains the following versions of 'irb': 1.0.0
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:251:in `each'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:251:in `verify_gemfile_dependencies_are_found!'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:48:in `start'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:23:in `resolve'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:264:in `resolve'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:467:in `materialize'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:185:in `specs'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:233:in `specs_for'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:18:in `setup'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler.rb:150:in `setup'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/ui/shell.rb:136:in `with_level'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/ui/shell.rb:88:in `silence'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/kbuilder/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
*** ../../../../ext/google/protobuf_c/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../ext/google/protobuf_c
	--curdir
	--ruby=/Users/kbuilder/.rake-compiler/ruby/x86_64-darwin/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
rake aborted!
Command failed with status (1): [/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin...]
/Users/kbuilder/.rvm/gems/ruby-2.6.3/gems/rake-compiler-1.1.2/lib/rake/extensiontask.rb:216:in `block (2 levels) in define_compile_tasks'
/Users/kbuilder/.rvm/gems/ruby-2.6.3/gems/rake-compiler-1.1.2/lib/rake/extensiontask.rb:213:in `block in define_compile_tasks'
/Users/kbuilder/.rvm/gems/ruby-2.6.3/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => native => native:x86_64-darwin => native:google-protobuf:x86_64-darwin => tmp/x86_64-darwin/stage/lib/google/2.4/protobuf_c.bundle => copy:protobuf_c:x86_64-darwin:2.4.0 => tmp/x86_64-darwin/protobuf_c/2.4.0/protobuf_c.bundle => tmp/x86_64-darwin/protobuf_c/2.4.0/Makefile
(See full trace by running task with --trace)
+ ls pkg
ls: pkg: No such file or directory


[ID: 4668672] Build finished after 1365 secs, exit value: 1
```

Seems like a gem is missing from the local context, how are these normally managed?

**Comment by perezd** [comment]
This appears to be related: https://github.com/protocolbuffers/protobuf/pull/8565

**Comment by haberman** [comment]
@dazuma FYI

Sounds like it might be time to drop Ruby 2.4 support. Pinning to irb 1.1 was solely for the benefit of Ruby 2.4. But per https://www.ruby-lang.org/en/downloads/branches/, Ruby 2.4 has been eol since March 2020 (over a year ago).

**Comment by dazuma** [comment]
I'd be supportive of dropping 2.4 at this time. Our cadence on the client library side has generally been to try to support versions for 10-11 months after the EOL date (i.e. until we're able to support the next new version after that EOL date). So client libraries officially dropped 2.4 early this year as soon as we got 3.0 support stable, and we expect to drop 2.5 support around the same time next year once 3.1 support is stable.

**Comment by haberman** [comment]
We dropped 2.3 and 2.4 here: https://github.com/protocolbuffers/protobuf/pull/9311
