### ISSUE TITLE
Test setup failure with OpenJDK 1.17

### ISSUE THREAD

**Issue by opoplawski** [protocolbuffers/protobuf#9477]
**What version of protobuf and what language are you using?**
Version: 3.19.4
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Fedora Rawhide

**What runtime / compiler are you using (e.g., python version or gcc version)**
OpenJDK 1.17

**What did you do?**
Build with
xmvn --batch-mode --offline -f java/pom.xml verify org.fedoraproject.xmvn:xmvn-mojo:install org.fedoraproject.xmvn:xmvn-mojo:javadoc org.fedoraproject.xmvn:xmvn-mojo:builddep

**What did you expect to see**
No errors

**What did you see instead?**
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.protobuf.RepeatedFieldBuilderV3Test
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in com.google.protobuf.RepeatedFieldBuilderV3Test
[INFO] Running com.google.protobuf.WireFormatLiteTest
[INFO] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.246 s - in com.google.protobuf.WireFormatLiteTest
[INFO] Running com.google.protobuf.ServiceTest
[ERROR] Tests run: 7, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.081 s <<< FAILURE! - in com.google.protobuf.ServiceTest
[ERROR] com.google.protobuf.ServiceTest.testGetPrototype  Time elapsed: 0.038 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.google.protobuf.ServiceTest.testGetPrototype(ServiceTest.java:107)
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @353b36e8
	at com.google.protobuf.ServiceTest.testGetPrototype(ServiceTest.java:107)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @353b36e8
	at com.google.protobuf.ServiceTest.testGetPrototype(ServiceTest.java:107)
[ERROR] com.google.protobuf.ServiceTest.testCallMethod  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
	at com.google.protobuf.ServiceTest.testCallMethod(ServiceTest.java:83)
```

**Anything else we should know about your project / environment**
Fedora has just bumped the default Java to OpenJDK 1.17 which appears to have triggered this failure.

**Comment by perezd** [comment]
OK, I think we need to increase our testing matrix to include JDK17. I don't think we designate actual support for it anywhere presently.

**Comment by elharo** [comment]
Looks like an error in the mocking framework. Likely it's doing something weird (as expected for mocking frameworks) that trips over the enhanced protections in JDK 17.

**Comment by elharo** [comment]
I think we can just update this one test and then remove EasyMock completely:

javatests/com/google/protobuf/ServiceTest.java

I don't see it used anywhere else.

**Comment by elharo** [comment]
I think @darly fixed this a few months ago
