### ISSUE TITLE
Calling `to_json` on a Hash that contains a protobuf message value raises an ArgumentError

### ISSUE THREAD

**Issue by lukad** [protocolbuffers/protobuf#9500]
**What version of protobuf and what language are you using?**
Version: 3.19.4
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**

Macos 12.0.1

**What runtime / compiler are you using (e.g., python version or gcc version)**

Ruby 3.1.0

**What did you do?**

When calling `to_json` on a Hash or Array that contains a protobuf message an `ArgumentError` is raised (`Expected hash arguments. (ArgumentError)`).

I've created this minimal reproducable example:

``` ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'google-protobuf', '= 3.19.4'
end

require 'json'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('msg.proto', syntax: :proto3) do
    add_message 'Msg' do
      optional :some_field, :string, 1, json_name: 'some_field'
    end
  end
end

Msg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('Msg').msgclass
msg = Msg.new(some_field: 'some_value')

puts msg.to_json
puts({ msg: msg }.to_json)
```

**What did you expect to see**

```
{"some_field":"some_value"}
{"msg": {"some_field": "some_value"}}
```

**What did you see instead?**

```
{"some_field":"some_value"}
/Users/luka/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-protobuf-3.19.4/lib/google/protobuf/message_exts.rb:44:in `encode_json': Expected hash arguments. (ArgumentError)
	from /Users/luka/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-protobuf-3.19.4/lib/google/protobuf/message_exts.rb:44:in `to_json'
	from bug.rb:24:in `to_json'
	from bug.rb:24:in `<main>'
```

**Comment by lukad** [comment]
After some digging I found out that the options being passed to [`#to_json`](https://github.com/protocolbuffers/protobuf/blob/8bfa7d00839a31e898a496ef4472b7ce211d543a/ruby/lib/google/protobuf/message_exts.rb#L43-L45) are a `json::Ext::Generator::State` object. This class implements [`#to_h`](https://apidock.com/ruby/JSON/Ext/Generator/State/to_h) and can be used as Hash arguments instead of raising.

Not sure if this is the right way. Would love to get some feedback on my PR #9513 and possibly get this issue resolved.
