### ISSUE TITLE
rake gem:windows fails.

### ISSUE THREAD

**Issue by Alacrious** [protocolbuffers/protobuf#9540]
**What version of protobuf and what language are you using?**
Version: master
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc:9.3

**What did you do?**
I want to compile it for windows. When I do rake gem:windows it fails
Just do rake gem:native

**What did you expect to see**
It should build.

**What did you see instead?**
`Gem::InvalidSpecificationException: ["lib/google/protobuf/descriptor_pb.rb", "lib/google/protobuf/duration_pb.rb", "lib/google/protobuf/empty_pb.rb", "lib/goo
gle/protobuf/field_mask_pb.rb", "lib/google/protobuf/source_context_pb.rb", "lib/google/protobuf/struct_pb.rb", "lib/google/protobuf/timestamp_pb.rb", "lib/go
ogle/protobuf/type_pb.rb", "lib/google/protobuf/wrappers_pb.rb"] are not files
/usr/local/rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => pkg/google-protobuf-3.19.4-x64-mingw32.gem
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v /home/ubuntu/repos/sentio-protobuf/ruby:/home/ubuntu/repos/sentio-protobuf/ruby -e UID\=1000 -e GID\=1000 -e US
ER\=ubuntu -e GROUP\=ubuntu -e GEM_PRIVATE_KEY_PASSPHRASE -e ftp_proxy -e http_proxy -e https_proxy -e RCD_HOST_RUBY_PLATFORM\=x86_64-linux -e RCD_HOST_RUBY_V
ERSION\=2.5.0 -e RCD_IMAGE\=larskanis/rake-compiler-dock-mri-x64-mingw32:1.2.0 -w /home/ubuntu/repos/sentio-protobuf/ruby --rm -i -t larskanis/rake-compiler-d
ock-mri-x64-mingw32:1.2.0 runas sigfw bash -c \ \ \ \ \ \ \ \ bundle\ \&\&\ \ \ \ \ \ \ \ \ IN_DOCKER\=true\ rake\ native:x64-mingw32\ pkg/google-protobuf-3.1
9.4-x64-mingw32.gem\ RUBY_CC_VERSION\=3.0.0:2.7.0:2.6.0:2.5.0'
']
/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-compiler-dock-1.2.0/lib/rake_compiler_dock/starter.rb:97:in `block in exec'
/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-compiler-dock-1.2.0/lib/rake_compiler_dock/starter.rb:47:in `each'
/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-compiler-dock-1.2.0/lib/rake_compiler_dock/starter.rb:47:in `exec'
/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-compiler-dock-1.2.0/lib/rake_compiler_dock/starter.rb:14:in `sh'
/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-compiler-dock-1.2.0/lib/rake_compiler_dock.rb:46:in `sh'
/home/ubuntu/repos/sentio-protobuf/ruby/Rakefile:126:in `block (2 levels) in <top (required)>'
/home/ubuntu/repos/sentio-protobuf/ruby/Rakefile:125:in `each'`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
I have cloned the repo and created a new repo. I just want to know why it is not building.

**Anything else we should know about your project / environment**

**Comment by Alacrious** [comment]
I need to change the gemspec.
