### ISSUE TITLE
ClassCastException in toString() for MapEntry with oneof field

### ISSUE THREAD

**Issue by dsyer** [protocolbuffers/protobuf#9619]
**What version of protobuf and what language are you using?**
Version: 3.18.0
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Go to https://github.com/scratches/protobuf-bug
2. Clone project and run tests
3. See error

**What did you expect to see**
Green tests

**What did you see instead?**

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
 at com.google.protobuf.TextFormat$Printer.printFieldValue(TextFormat.java:541)
 at com.google.protobuf.TextFormat$Printer.printSingleField(TextFormat.java:743)
 at com.google.protobuf.TextFormat$Printer.printField(TextFormat.java:443)
 at com.google.protobuf.TextFormat$Printer.printMessage(TextFormat.java:705)
 at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:353)
 at com.google.protobuf.TextFormat$Printer.printFieldValue(TextFormat.java:597)
 at com.google.protobuf.TextFormat$Printer.printSingleField(TextFormat.java:743)
 at com.google.protobuf.TextFormat$Printer.printField(TextFormat.java:435)
 at com.google.protobuf.TextFormat$Printer.printMessage(TextFormat.java:705)
 at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:353)
 at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:339)
 at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:606)
 at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
 ...
```

It looks like `TextFormat$Printer` is doing something funky with the `MapEntry` (using the metadata from the value, not the entry itself or something).

N.B. it's the same object structure as you would get with `Struct` (which has a `map<string,Value>`) but there is a special case in the `TextFormat$Printer` for those types so the error doesn't happen there.

**Comment by elharo** [comment]
I can reproduce this at head. Looks like the FieldDescriptor might be picking up the type of the first field in the oneof rather than the actual type.

**Comment by elharo** [comment]
Might require fixing #7452 and b/124347790

**Comment by dsyer** [comment]
Bump

**Comment by elharo** [comment]
Auto-closing legitimate issues because no one is working on them right this minute dramatically reduces product quality and team velocity. It wastes developers' times by making them rediscover and re-report the same bugs over and over. It demoralizes and discourages external contributors. Google has a lot of good practices for software development. This isn't one of them. Bug bankruptcy is one of Google's worst practices for software development. This issue was confirmed and reproduced. If you can verify it is now fixed, close it. Otherwise don't. 

When I was on the protobuf team, I personally read every single issue in this repo, more than once. I closed, classified, and fixed as appropriate. There aren't that many and it isn't that hard, especially if you make a point of staying on top of newly filed issues.

**Comment by dsyer** [comment]
Bump please

**Comment by dsyer** [comment]
Bump. Sigh.

**Comment by dsyer** [comment]
bump again. sigh again.

**Comment by dsyer** [comment]
re-bump. re-sigh.

**Comment by dsyer** [comment]
re-bump

**Comment by esrauchg** [comment]
Sorry, this issue got into a state where literally no one was seeing any of the bumps/comments.

I'm marking this as untriaged to get this back into our normal weekly triage process.

**Comment by esrauchg** [comment]
We will triage in our normal process again, but I went ahead and looked at the repo and it relates to using reflection on Map fields.

Reflection on map fields is unfortunately a topic which has problems at a system design level (not just in Java but at least also in C++). The duality of Map being represented as a repeated field or a map representation doesn't really work out over the reflective usecases. This narrow issue might have a mitigation, but at least the broader situation of that topic does have bugs that are effectively unfixable as a bug fix, and would require API change or significant implementation change to avoid.

We tentatively intend to entirely redo how maps are exposed in reflection as the holistic fix, but its not staffed at this time.

We can look closer but this might end up in a "bug which unfortunately is wontfix until Map reflection is redone" state.

Sorry again about it getting stuck in an autoclose loop to not get this information sooner.

**Comment by esrauchg** [comment]
I went ahead and tried to reproduce this internally and wasn't able to reproduce the failure.

One thing that jumps out to me is the repro has this line:
```
MapEntry<String, GenericValue> entry = MapEntry.newDefaultInstance(GenericValue.getDescriptor(),
				FieldType.STRING, "", FieldType.MESSAGE, null);
```

The last argument should really be GenericValue.getDefaultInstance() not null; it would reasonably likely breaks our internal invariants if you pass null there.

I'll note that this function is probably not defensive against such things because this is really an 'internal API' which is only public because generated code has to use it. See comment at the top of MapEntry which says "Protobuf internal. Users shouldn't use this class."

It seems reasonably likely that this was incidentally/accidentally resolved in the past 3 years to me; @dsyer can you see if this does reproduces for you on protobuf-java 4.30?

**Comment by dsyer** [comment]
You were right: upgrading to 4.30.2 fixed the issue (even without the non-null last argument).
